# Corporate Announcement Event Study

## 1. Project Overview

This project analyzes how stock prices and trading volume react to corporate announcements over short intraday horizons.

The analysis examines:
- 5-minute
- 30-minute
- 60-minute

post-announcement windows across different corporate announcement categories.

The objective is to identify whether different types of announcements are associated with statistically significant changes in stock returns and trading activity.

## 2. Business Questions

1. Do corporate announcements generate abnormal short-term stock returns?
2. Does the market reaction differ by announcement type?
3. How does trading volume change following announcements?
4. Are the observed effects statistically significant after correcting for multiple comparisons?
5. Are the findings robust to extreme observations?

# 3. Data Loading

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\piyus\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: numpy in C:\Users\piyus\AppData\Roaming\Python\Python314\site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\piyus\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\piyus\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\piyus\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.5
NumPy version: 2.5.2

In [4]:
print("hello")

hello

In [5]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()
DATA_DIR = PROJECT_ROOT / "data"

print("Project folder:", PROJECT_ROOT)
print("Data folder:", DATA_DIR)

Project folder: C:\IndoThai_Quant_Assessment
Data folder: C:\IndoThai_Quant_Assessment\data

In [6]:
import os

print(os.getcwd())

C:\IndoThai_Quant_Assessment

In [7]:
files = list(DATA_DIR.iterdir())

for file in files:
    print(file.name)

.ipynb_checkpoints
corporate_announcements.csv
corporate_announcements.jsonl
HAL.csv
HDFCBANK.csv
metadata.json
NYKAA.csv
RELIANCE.csv
RVNL.csv

In [8]:
from pathlib import Path

PROJECT_ROOT = Path(r"C:\IndoThai_Quant_Assessment")
DATA_DIR = PROJECT_ROOT / "data"

print("Project folder:", PROJECT_ROOT)
print("Data folder:", DATA_DIR)
print("Data folder exists:", DATA_DIR.exists())

Project folder: C:\IndoThai_Quant_Assessment
Data folder: C:\IndoThai_Quant_Assessment\data
Data folder exists: True

In [9]:
files = list(DATA_DIR.iterdir())

for file in files:
    print(file.name)

.ipynb_checkpoints
corporate_announcements.csv
corporate_announcements.jsonl
HAL.csv
HDFCBANK.csv
metadata.json
NYKAA.csv
RELIANCE.csv
RVNL.csv

In [10]:
announcements = pd.read_csv(
    DATA_DIR / "corporate_announcements.csv"
)

print("Rows:", len(announcements))
print("Columns:", len(announcements.columns))

Rows: 2530
Columns: 28

# 4. Data Cleaning and Validation

In [11]:
announcements.head()

,NEWSID,SCRIP_CD,XML_NAME,NEWSSUB,DT_TM,NEWS_DT,CRITICALNEWS,ANNOUNCEMENT_TYPE,QUARTER_ID,FILESTATUS,...,SLONGNAME,AGENDA_ID,News_submission_dt,DissemDT,TimeDiff,Fld_Attachsize,SUBCATNAME,BSENewsid,Investor_Presentation,AUDIO_VIDEO_FILE
0,d4395f8a-6089-4a17-8dec-385a6acb2b67,500180,ANN_500180_D4395F8A-6089-4A17-8DEC-385A6ACB2B67,Announcement under Regulation 30 (LODR)-Credit...,2026-08-19T23:19:39.42,2026-08-19T23:19:39.42,1,A,NaN,N,...,HDFC Bank Ltd,46,2026-08-19T23:19:39,2026-08-19T23:19:39.42,00:00:00,967155.0,Credit Rating,NaN,NaN,NaN
1,391541fa-8d4b-41b6-9304-1e15bed1d5d8,500180,ANN_500180_391541FA-8D4B-41B6-9304-1E15BED1D5D8,Intimation Under Securities And Exchange Board...,2026-08-19T22:52:54.67,2026-08-19T22:52:54.67,0,A,NaN,N,...,HDFC Bank Ltd,1,2026-08-19T22:52:54,2026-08-19T22:52:54.67,00:00:00,618910.0,General,NaN,NaN,NaN
2,989d8d2f-2b08-4a1c-8d43-f55bae61c178,500325,ANN_500325_989D8D2F-2B08-4A1C-8D43-F55BAE61C178,Update On Institutional Investors'' Meeting - ...,2026-08-18T20:06:38.747,2026-08-18T20:06:38.747,0,A,NaN,N,...,Reliance Industries Ltd,1,2026-08-18T20:06:38,2026-08-18T20:06:38.747,00:00:00,238773.0,General,NaN,NaN,NaN
3,b0bc3391-c0aa-44d6-be8d-a10b20b10247,500325,ANN_500325_B0BC3391-C0AA-44D6-BE8D-A10B20B10247,"News Clarification - ""SC Slaps Rs 10 Lakh Fine...",2026-08-18T17:44:19.31,2026-08-18T17:44:19.31,0,A,NaN,N,...,Reliance Industries Ltd,1,2026-08-18T17:44:19,2026-08-18T17:44:19.31,00:00:00,275828.0,General,NaN,NaN,NaN
4,32de7735-b8e6-4653-b377-0c5762be73af,542649,ANN_542649_32DE7735-B8E6-4653-B377-0C5762BE73AF,Announcement under Regulation 30 (LODR)-Earnin...,2026-08-18T14:24:13.29,2026-08-18T14:24:13.29,0,A,NaN,N,...,Rail Vikas Nigam Ltd,157,2026-08-18T14:24:13,2026-08-18T14:24:13.29,00:00:00,602505.0,Earnings Call Transcript,NaN,NaN,NaN

In [12]:
announcements.info()

<class 'pandas.DataFrame'>
RangeIndex: 2530 entries, 0 to 2529
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NEWSID                 2530 non-null   str
 1   SCRIP_CD               2530 non-null   int64
 2   XML_NAME               2530 non-null   str
 3   NEWSSUB                2530 non-null   str
 4   DT_TM                  2530 non-null   str
 5   NEWS_DT                2530 non-null   str
 6   CRITICALNEWS           2530 non-null   int64
 7   ANNOUNCEMENT_TYPE      2530 non-null   str
 8   QUARTER_ID             0 non-null      float64
 9   FILESTATUS             2530 non-null   str
 10  ATTACHMENTNAME         2510 non-null   str
 11  MORE                   383 non-null    str
 12  HEADLINE               2530 non-null   str
 13  CATEGORYNAME           2530 non-null   str
 14  OLD                    2530 non-null   int64
 15  RN                     2530 non-null   int64
 16  PDFFLAG                2530 non-null   int64
 17  NSURL                  2530 non-null   str
 18  SLONGNAME              2530 non-null   str
 19  AGENDA_ID              2530 non-null   int64
 20  News_submission_dt     2502 non-null   str
 21  DissemDT               2530 non-null   str
 22  TimeDiff               2502 non-null   str
 23  Fld_Attachsize         2504 non-null   float64
 24  SUBCATNAME             2526 non-null   str
 25  BSENewsid              51 non-null     str
 26  Investor_Presentation  51 non-null     str
 27  AUDIO_VIDEO_FILE       51 non-null     str
dtypes: float64(2), int64(6), str(20)
memory usage: 553.6 KB

In [13]:
missing = announcements.isna().sum()

missing[missing > 0].sort_values(ascending=False)

QUARTER_ID               2530
Investor_Presentation    2479
BSENewsid                2479
AUDIO_VIDEO_FILE         2479
MORE                     2147
News_submission_dt         28
TimeDiff                   28
Fld_Attachsize             26
ATTACHMENTNAME             20
SUBCATNAME                  4
dtype: int64

In [14]:
announcements.columns.tolist()

['NEWSID',
 'SCRIP_CD',
 'XML_NAME',
 'NEWSSUB',
 'DT_TM',
 'NEWS_DT',
 'CRITICALNEWS',
 'ANNOUNCEMENT_TYPE',
 'QUARTER_ID',
 'FILESTATUS',
 'ATTACHMENTNAME',
 'MORE',
 'HEADLINE',
 'CATEGORYNAME',
 'OLD',
 'RN',
 'PDFFLAG',
 'NSURL',
 'SLONGNAME',
 'AGENDA_ID',
 'News_submission_dt',
 'DissemDT',
 'TimeDiff',
 'Fld_Attachsize',
 'SUBCATNAME',
 'BSENewsid',
 'Investor_Presentation',
 'AUDIO_VIDEO_FILE']

In [15]:
print("Duplicate NEWSID:", announcements["NEWSID"].duplicated().sum())

print(
    "Duplicate complete rows:",
    announcements.duplicated().sum()
)

Duplicate NEWSID: 0
Duplicate complete rows: 0

In [16]:
duplicate_ids = announcements[
    announcements["NEWSID"].duplicated(keep=False)
].sort_values("NEWSID")

duplicate_ids[["NEWSID", "SCRIP_CD", "DT_TM", "DissemDT", "HEADLINE"]]

Empty DataFrame
Columns: [NEWSID, SCRIP_CD, DT_TM, DissemDT, HEADLINE]
Index: []

In [17]:
announcements["SCRIP_CD"].value_counts()

SCRIP_CD
500325    844
500180    607
542649    464
543384    339
541154    276
Name: count, dtype: int64

In [18]:
print(announcements[["DT_TM", "DissemDT"]].head(10).to_string())

                     DT_TM                 DissemDT
0   2026-08-19T23:19:39.42   2026-08-19T23:19:39.42
1   2026-08-19T22:52:54.67   2026-08-19T22:52:54.67
2  2026-08-18T20:06:38.747  2026-08-18T20:06:38.747
3   2026-08-18T17:44:19.31   2026-08-18T17:44:19.31
4   2026-08-18T14:24:13.29   2026-08-18T14:24:13.29
5  2026-08-17T17:18:06.063  2026-08-17T17:18:06.063
6  2026-08-16T19:43:27.497  2026-08-16T19:43:27.497
7   2026-08-14T18:22:56.08   2026-08-14T18:22:56.08
8  2026-08-14T17:45:54.693  2026-08-14T17:45:54.693
9  2026-08-14T14:10:20.837  2026-08-14T14:10:20.837

In [19]:
print("DT_TM missing:", announcements["DT_TM"].isna().sum())
print("DissemDT missing:", announcements["DissemDT"].isna().sum())

DT_TM missing: 0
DissemDT missing: 0

In [20]:
print("Duplicate NEWSID:", announcements["NEWSID"].duplicated().sum())
print("Duplicate complete rows:", announcements.duplicated().sum())

Duplicate NEWSID: 0
Duplicate complete rows: 0

In [21]:
announcements["SCRIP_CD"].value_counts()

SCRIP_CD
500325    844
500180    607
542649    464
543384    339
541154    276
Name: count, dtype: int64

In [22]:
print(announcements[["DT_TM", "DissemDT"]].head(10).to_string())

print("DT_TM missing:", announcements["DT_TM"].isna().sum())
print("DissemDT missing:", announcements["DissemDT"].isna().sum())

                     DT_TM                 DissemDT
0   2026-08-19T23:19:39.42   2026-08-19T23:19:39.42
1   2026-08-19T22:52:54.67   2026-08-19T22:52:54.67
2  2026-08-18T20:06:38.747  2026-08-18T20:06:38.747
3   2026-08-18T17:44:19.31   2026-08-18T17:44:19.31
4   2026-08-18T14:24:13.29   2026-08-18T14:24:13.29
5  2026-08-17T17:18:06.063  2026-08-17T17:18:06.063
6  2026-08-16T19:43:27.497  2026-08-16T19:43:27.497
7   2026-08-14T18:22:56.08   2026-08-14T18:22:56.08
8  2026-08-14T17:45:54.693  2026-08-14T17:45:54.693
9  2026-08-14T14:10:20.837  2026-08-14T14:10:20.837
DT_TM missing: 0
DissemDT missing: 0

# 5. Event Identification and Alignment

In [23]:
announcements["DT_TM"] = pd.to_datetime(
    announcements["DT_TM"],
    errors="coerce"
)

announcements["DissemDT"] = pd.to_datetime(
    announcements["DissemDT"],
    errors="coerce"
)

print(announcements[["DT_TM", "DissemDT"]].dtypes)

DT_TM       datetime64[us]
DissemDT    datetime64[us]
dtype: object

In [24]:
errors="coerce"

In [25]:
print("Invalid DT_TM:", announcements["DT_TM"].isna().sum())
print("Invalid DissemDT:", announcements["DissemDT"].isna().sum())

Invalid DT_TM: 11
Invalid DissemDT: 11

In [26]:
invalid_timestamps = announcements[
    announcements["DT_TM"].isna() |
    announcements["DissemDT"].isna()
]

print(invalid_timestamps[
    ["NEWSID", "SCRIP_CD", "DT_TM", "DissemDT", "HEADLINE"]
].to_string(index=False))

                              NEWSID  SCRIP_CD DT_TM DissemDT                                                                                                                                                            HEADLINE
3d966192-56c7-43da-a66a-fd14983a6ad0    541154   NaT      NaT                                                                                                                                            announcement is attached
476d5e4c-6000-48b4-88d0-91abb12761c0    500180   NaT      NaT                                                                                                                  Issuance of USD 750 Million Senior Unsecured Bonds
67d695b2-863a-41c9-bb89-da579b4ab29c    542649   NaT      NaT                                                                                           Annual Secretarial Compliance Report for the year ended 31st March, 2026.
e1a2519b-7bf6-4ad8-9fe2-c784eb5f819c    543384   NaT      NaT                                                                                             Newspaper clipping regarding 12th Annual General Meeting of the Company
9bba9b09-e6d6-4052-a053-b998f7a007f4    542649   NaT      NaT            Information regarding arbitration application no. 33/2019 between Krishnapatnam Railway Company Limited (KRCL) (a SPV of RVNL) and Ministry of Railways.
58e2a704-4f7e-4dc1-a665-403cf6fd6e32    542649   NaT      NaT                                                            Rail Vikas Nigam Limited emerges as the Lowest Bidder (L1) from SER HQ-ELECTRICAL/SOUTH EASTERN RAILWAY.
7c58cbc0-452d-4f4f-bcbb-0f217291a7b6    500180   NaT      NaT       The Exchange has received the disclosure under Regulation 29(1) of SEBI (Substantial Acquisition of Shares & Takeovers) Regulations, 2011 for SBI Mutual Fund
d2a03ad3-7fc3-40ac-b54b-e1d8d2ffc6bf    541154   NaT      NaT                                                                                                                                            announcement is attached
e0c214b5-1763-43bd-8e4f-e67043b910a2    542649   NaT      NaT The Board of Directors of RVNL has approved the appointment of Shri Vivek Kumar Gupta as Additional Director w.e.f. 12th December, 2023 (date of allotment of DIN).
198970bb-92aa-44f7-8840-f5d0a0b1054b    500325   NaT      NaT           We enclose the information regarding loss of share certificate(s) for 2,991 shares received from the shareholder(s) of the Company on September 26, 2023.
e4ab8af8-afe7-4c56-8482-afe95459f7bd    542649   NaT      NaT                                                                                Letter of Acceptance (LOA) received from Madhya Gujarat Vij Company Limited (MGVCL).

In [27]:
raw_announcements = pd.read_csv(
    DATA_DIR / "corporate_announcements.csv"
)

raw_announcements["DT_TM_parsed"] = pd.to_datetime(
    raw_announcements["DT_TM"],
    errors="coerce"
)

raw_announcements["DissemDT_parsed"] = pd.to_datetime(
    raw_announcements["DissemDT"],
    errors="coerce"
)

invalid = raw_announcements[
    raw_announcements["DT_TM_parsed"].isna() |
    raw_announcements["DissemDT_parsed"].isna()
]

print("Invalid rows:", len(invalid))

print(
    invalid[
        ["NEWSID", "DT_TM", "DissemDT", "HEADLINE"]
    ].to_string(index=False)
)

Invalid rows: 11
                              NEWSID               DT_TM            DissemDT                                                                                                                                                            HEADLINE
3d966192-56c7-43da-a66a-fd14983a6ad0 2026-07-17T16:03:54 2026-07-17T16:03:54                                                                                                                                            announcement is attached
476d5e4c-6000-48b4-88d0-91abb12761c0 2026-06-16T22:39:07 2026-06-16T22:39:07                                                                                                                  Issuance of USD 750 Million Senior Unsecured Bonds
67d695b2-863a-41c9-bb89-da579b4ab29c 2026-05-29T18:56:28 2026-05-29T18:56:28                                                                                           Annual Secretarial Compliance Report for the year ended 31st March, 2026.
e1a2519b-7bf6-4ad8-9fe2-c784eb5f819c 2024-08-21T13:04:56 2024-08-21T13:04:56                                                                                             Newspaper clipping regarding 12th Annual General Meeting of the Company
9bba9b09-e6d6-4052-a053-b998f7a007f4 2024-07-19T12:31:08 2024-07-19T12:31:08            Information regarding arbitration application no. 33/2019 between Krishnapatnam Railway Company Limited (KRCL) (a SPV of RVNL) and Ministry of Railways.
58e2a704-4f7e-4dc1-a665-403cf6fd6e32 2024-06-21T15:11:53 2024-06-21T15:11:53                                                            Rail Vikas Nigam Limited emerges as the Lowest Bidder (L1) from SER HQ-ELECTRICAL/SOUTH EASTERN RAILWAY.
7c58cbc0-452d-4f4f-bcbb-0f217291a7b6 2024-06-21T14:08:07 2024-06-21T14:08:07       The Exchange has received the disclosure under Regulation 29(1) of SEBI (Substantial Acquisition of Shares & Takeovers) Regulations, 2011 for SBI Mutual Fund
d2a03ad3-7fc3-40ac-b54b-e1d8d2ffc6bf 2024-05-16T14:16:12 2024-05-16T14:16:12                                                                                                                                            announcement is attached
e0c214b5-1763-43bd-8e4f-e67043b910a2 2023-12-12T18:30:10 2023-12-12T18:30:10 The Board of Directors of RVNL has approved the appointment of Shri Vivek Kumar Gupta as Additional Director w.e.f. 12th December, 2023 (date of allotment of DIN).
198970bb-92aa-44f7-8840-f5d0a0b1054b 2023-09-27T17:18:45 2023-09-27T17:18:45           We enclose the information regarding loss of share certificate(s) for 2,991 shares received from the shareholder(s) of the Company on September 26, 2023.
e4ab8af8-afe7-4c56-8482-afe95459f7bd 2023-09-01T22:56:48 2023-09-01T22:56:48                                                                                Letter of Acceptance (LOA) received from Madhya Gujarat Vij Company Limited (MGVCL).

In [28]:
announcements["DT_TM"] = pd.to_datetime(
    announcements["DT_TM"],
    format="mixed",
    errors="coerce"
)

announcements["DissemDT"] = pd.to_datetime(
    announcements["DissemDT"],
    format="mixed",
    errors="coerce"
)

In [29]:
print("Invalid DT_TM:", announcements["DT_TM"].isna().sum())
print("Invalid DissemDT:", announcements["DissemDT"].isna().sum())

Invalid DT_TM: 11
Invalid DissemDT: 11

In [30]:
raw_announcements = pd.read_csv(
    DATA_DIR / "corporate_announcements.csv"
)

print(raw_announcements.shape)

(2530, 28)

In [31]:
raw_announcements["DT_TM"] = pd.to_datetime(
    raw_announcements["DT_TM"],
    format="ISO8601",
    errors="coerce"
)

raw_announcements["DissemDT"] = pd.to_datetime(
    raw_announcements["DissemDT"],
    format="ISO8601",
    errors="coerce"
)

In [32]:
print("Invalid DT_TM:", raw_announcements["DT_TM"].isna().sum())
print("Invalid DissemDT:", raw_announcements["DissemDT"].isna().sum())

Invalid DT_TM: 0
Invalid DissemDT: 0

In [33]:
announcements = raw_announcements.copy()

print("Rows:", len(announcements))
print("Columns:", len(announcements.columns))

Rows: 2530
Columns: 28

In [34]:
print("Earliest announcement:")
print(announcements["DissemDT"].min())

print("\nLatest announcement:")
print(announcements["DissemDT"].max())

Earliest announcement:
2023-08-21 18:16:15.450000

Latest announcement:
2026-08-19 23:19:39.420000

In [35]:
time_difference = (
    announcements["DissemDT"] -
    announcements["DT_TM"]
)

print(time_difference.describe())

count                      2530
mean     0 days 00:00:00.000150
std      0 days 00:00:00.006110
min             0 days 00:00:00
25%             0 days 00:00:00
50%             0 days 00:00:00
75%             0 days 00:00:00
max      0 days 00:00:00.307000
dtype: object

In [36]:
different_timestamps = (
    announcements["DT_TM"] != announcements["DissemDT"]
).sum()

print(
    "Announcements where DT_TM and DissemDT differ:",
    different_timestamps
)

Announcements where DT_TM and DissemDT differ: 24

In [37]:
different = announcements[
    announcements["DT_TM"] != announcements["DissemDT"]
]

print(
    different[
        [
            "SCRIP_CD",
            "DT_TM",
            "DissemDT",
            "TimeDiff",
            "HEADLINE"
        ]
    ].to_string(index=False)
)

 SCRIP_CD                   DT_TM                DissemDT TimeDiff                                                                                                                                                                                            HEADLINE
   541154 2026-08-04 10:49:02.237 2026-08-04 10:49:02.240 00:00:00                                                                                                                                                                               Announcement attached
   500180 2026-03-16 17:28:11.197 2026-03-16 17:28:11.200 00:00:00                                                                                                                                                   Allotment of 1630554 equity shares under ESOP/RSU
   500325 2026-02-11 19:28:12.147 2026-02-11 19:28:12.150 00:00:00   This is further to the disclosure dated February 6, 2026 made by the Company. We wish to inform you that the Company executives participated in the Institutional Investors'' Meeting - Axis ....
   543384 2025-12-26 21:30:45.100 2025-12-26 21:30:45.103 00:00:00                                                                                            Please find enclosed herewith outcome of Postal Ballot containing scrutinizers report and voting results
   542649 2025-12-22 15:00:06.070 2025-12-22 15:00:06.073 00:00:01                                                                            Demand Notice received from the Office of the Assistant Commissioner (ST), Alwarpet, South-I, Chennai South, Tamil Nadu.
   541154 2025-09-26 15:01:13.347 2025-09-26 15:01:13.350 00:00:00                                                                                                                                                                              Attachment as Attached
   500325 2025-09-09 20:06:33.200 2025-09-09 20:06:33.203 00:00:00     This is further to the disclosure dated September 3, 2025 made by the Company. We wish to inform that the Company executives participated in the Institutional Investors'' Meeting - CITIC ....
   500180 2025-09-01 17:46:13.547 2025-09-01 17:46:13.550 00:00:00                                                                                                                   Intimation of resignation of the Chief of Internal Vigilance of HDFC Bank Limited
   500180 2025-06-08 18:06:50.853 2025-06-08 18:06:50.857 00:00:00                                                                                      Disclosure under Regulation 30 of the SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015
   542649 2025-05-29 18:19:54.977 2025-05-29 18:19:54.980 00:00:00                                                                                                              Rail Vikas Nigam Limited (RVNL) signed MoU with M/s Texmaco Rail & Engineering Limited
   542649 2025-03-24 12:50:33.160 2025-03-24 12:50:33.163 00:00:01                                                                                                                                   Intimation regarding Change in the Senior Management- Resignation
   500325 2024-12-12 16:49:08.093 2024-12-12 16:49:08.097 00:00:01                                            We enclose the information regarding loss of share certificate(s) for 3,413 shares received from the shareholder(s) of the Company on December 11, 2024.
   542649 2024-11-26 15:26:48.417 2024-11-26 15:26:48.420 00:00:00                                                                                                                                            Letter of Acceptance received from South Central Railway
   500180 2024-10-29 09:17:33.927 2024-10-29 09:17:33.930 00:00:00                Grant of stock options under Employee Stock Option Scheme - ESOS 58 and Restricted Stock Units under Employee''s Stock Incentive Master Scheme - 2022 - RSU 009, RSU 010 and RSU 011
   500325 2024-09-23 18:19:00.480 2024-09-23 18:19:00.483 00:00:00 This is to inform you that the advertisement for "Extension of last date for payment of unpaid call money by holders of partly paid-up equity shares" has been published, in English language, ....
   542649 2024-08-27 11:25:35.760 2024-08-27 11:25:35.763 00:00:00                                                                                                                   Rail Vikas Nigam Limited emerges as the Lowest Bidder (L1) from Southern Railway.
   543384 2024-08-13 16:14:03.190 2024-08-13 16:14:03.497 00:00:00                                                                                                                                                                      Investor presentation attached
   500180 2024-07-23 17:23:08.487 2024-07-23 17:23:08.490 00:00:00                                                                                                                                                             Intimation of Loss of Share Certificate
   500325 2024-07-12 12:56:44.093 2024-07-12 12:56:44.097 00:00:01                                                    Disclosure under Regulation 30 of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015
   541154 2024-06-04 16:14:51.417 2024-06-04 16:14:51.420 00:00:00                                                                                                                                                                               Announcement attached
   541154 2024-05-13 10:33:41.433 2024-05-13 10:33:41.437 00:00:00                                                                                                                                                                               Announcement attached
   543384 2024-03-21 10:59:06.467 2024-03-21 10:59:06.470 00:00:00                                                                                                                                                             Intimation of closure of trading window
   541154 2024-03-01 15:01:39.523 2024-03-01 15:01:39.527 00:00:00                                                                                                                                                                            Announcement is attached
   541154 2023-10-04 17:31:35.723 2023-10-04 17:31:35.727 00:00:00                                                                                                                                                                            Announcement as attached

In [38]:
print(time_difference.describe())

count                      2530
mean     0 days 00:00:00.000150
std      0 days 00:00:00.006110
min             0 days 00:00:00
25%             0 days 00:00:00
50%             0 days 00:00:00
75%             0 days 00:00:00
max      0 days 00:00:00.307000
dtype: object

In [39]:
hour_counts = (
    announcements["DissemDT"]
    .dt.hour
    .value_counts()
    .sort_index()
)

print(hour_counts.to_string())

DissemDT
0       9
1       1
2       2
6       2
7       6
8      24
9      50
10     56
11     70
12    107
13     98
14    149
15    201
16    330
17    339
18    403
19    307
20    144
21    104
22     84
23     44

In [40]:
print("Earliest:", announcements["DissemDT"].min())
print("Latest:", announcements["DissemDT"].max())

Earliest: 2023-08-21 18:16:15.450000
Latest: 2026-08-19 23:19:39.420000

In [41]:
reliance = pd.read_csv(
    DATA_DIR / "RELIANCE.csv"
)

print("Rows:", len(reliance))
print("Columns:", len(reliance.columns))

Rows: 277510
Columns: 7

In [42]:
print(reliance.columns.tolist())

['date', 'open', 'high', 'low', 'close', 'volume', 'oi']

In [43]:
print(reliance.head().to_string())

                         date    open    high     low   close    volume  oi
0  2023-08-21T09:15:00.000000  1270.0  1274.5  1267.5  1271.5  298148.0   0
1  2023-08-21T09:16:00.000000  1271.4  1271.5  1268.2  1270.0   91462.0   0
2  2023-08-21T09:17:00.000000  1270.1  1274.5  1269.7  1274.0   87564.0   0
3  2023-08-21T09:18:00.000000  1274.0  1277.7  1274.0  1277.0  125296.0   0
4  2023-08-21T09:19:00.000000  1277.0  1277.3  1274.0  1274.5   53530.0   0

In [44]:
reliance.info()

<class 'pandas.DataFrame'>
RangeIndex: 277510 entries, 0 to 277509
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    277510 non-null  str
 1   open    277510 non-null  float64
 2   high    277510 non-null  float64
 3   low     277510 non-null  float64
 4   close   277510 non-null  float64
 5   volume  277510 non-null  float64
 6   oi      277510 non-null  int64
dtypes: float64(5), int64(1), str(1)
memory usage: 14.8 MB

In [45]:
missing_reliance = reliance.isna().sum()

print(
    missing_reliance[
        missing_reliance > 0
    ].sort_values(ascending=False).to_string()
)

Series([], )

In [46]:
print(
    "Duplicate complete rows:",
    reliance.duplicated().sum()
)

Duplicate complete rows: 0

In [47]:
reliance["date"] = pd.to_datetime(
    reliance["date"],
    format="ISO8601",
    errors="coerce"
)

print("Invalid dates:", reliance["date"].isna().sum())
print(reliance["date"].dtype)

Invalid dates: 0
datetime64[us]

In [48]:
print("Earliest bar:", reliance["date"].min())
print("Latest bar:", reliance["date"].max())

Earliest bar: 2023-08-21 09:15:00
Latest bar: 2026-08-19 15:29:00

In [49]:
print(
    "Duplicate timestamps:",
    reliance["date"].duplicated().sum()
)

Duplicate timestamps: 0

In [50]:
invalid_ohlc = reliance[
    (reliance["high"] < reliance["open"]) |
    (reliance["high"] < reliance["close"]) |
    (reliance["low"] > reliance["open"]) |
    (reliance["low"] > reliance["close"]) |
    (reliance["high"] < reliance["low"])
]

print("Invalid OHLC rows:", len(invalid_ohlc))

Invalid OHLC rows: 0

In [51]:
print("Zero-volume bars:", (reliance["volume"] == 0).sum())
print("Negative-volume bars:", (reliance["volume"] < 0).sum())

print("Non-positive open:", (reliance["open"] <= 0).sum())
print("Non-positive high:", (reliance["high"] <= 0).sum())
print("Non-positive low:", (reliance["low"] <= 0).sum())
print("Non-positive close:", (reliance["close"] <= 0).sum())

Zero-volume bars: 190
Negative-volume bars: 0
Non-positive open: 0
Non-positive high: 0
Non-positive low: 0
Non-positive close: 0

In [52]:
print(
    "Earliest time:",
    reliance["date"].dt.time.min()
)

print(
    "Latest time:",
    reliance["date"].dt.time.max()
)

Earliest time: 09:15:00
Latest time: 19:14:00

In [53]:
reliance["date"].diff()

0                    NaT
1        0 days 00:01:00
2        0 days 00:01:00
3        0 days 00:01:00
4        0 days 00:01:00
               ...
277505   0 days 00:01:00
277506   0 days 00:01:00
277507   0 days 00:01:00
277508   0 days 00:01:00
277509   0 days 00:01:00
Name: date, Length: 277510, dtype: timedelta64[us]

In [54]:
stock_files = {
    "RELIANCE": "RELIANCE.csv",
    "HDFCBANK": "HDFCBANK.csv",
    "NYKAA": "NYKAA.csv",
    "RVNL": "RVNL.csv",
    "HAL": "HAL.csv"
}

stocks = {}

for ticker, filename in stock_files.items():
    df = pd.read_csv(DATA_DIR / filename)

    df["date"] = pd.to_datetime(
        df["date"],
        format="ISO8601",
        errors="coerce"
    )

    stocks[ticker] = df

    print(
        ticker,
        "| Rows:", len(df),
        "| Invalid dates:", df["date"].isna().sum(),
        "| Duplicate timestamps:", df["date"].duplicated().sum(),
        "| Missing values:", df.isna().sum().sum()
    )

RELIANCE | Rows: 277510 | Invalid dates: 0 | Duplicate timestamps: 0 | Missing values: 0
HDFCBANK | Rows: 277510 | Invalid dates: 0 | Duplicate timestamps: 0 | Missing values: 0
NYKAA | Rows: 277508 | Invalid dates: 0 | Duplicate timestamps: 0 | Missing values: 0
RVNL | Rows: 277509 | Invalid dates: 0 | Duplicate timestamps: 0 | Missing values: 0
HAL | Rows: 277510 | Invalid dates: 0 | Duplicate timestamps: 0 | Missing values: 0

In [55]:
for ticker, df in stocks.items():

    invalid_ohlc = (
        (df["high"] < df["open"]) |
        (df["high"] < df["close"]) |
        (df["low"] > df["open"]) |
        (df["low"] > df["close"]) |
        (df["high"] < df["low"])
    )

    print(
        ticker,
        "| Invalid OHLC:", invalid_ohlc.sum(),
        "| Zero volume:", (df["volume"] == 0).sum(),
        "| Negative volume:", (df["volume"] < 0).sum()
    )

RELIANCE | Invalid OHLC: 0 | Zero volume: 190 | Negative volume: 0
HDFCBANK | Invalid OHLC: 1 | Zero volume: 187 | Negative volume: 0
NYKAA | Invalid OHLC: 0 | Zero volume: 191 | Negative volume: 0
RVNL | Invalid OHLC: 0 | Zero volume: 191 | Negative volume: 0
HAL | Invalid OHLC: 1 | Zero volume: 187 | Negative volume: 0

In [56]:
for ticker, df in stocks.items():

    df = df.sort_values("date").copy()

    df["trading_date"] = df["date"].dt.date

    gaps = (
        df.groupby("trading_date")["date"]
        .apply(lambda x: x.sort_values().diff().dropna().dt.total_seconds().gt(60).sum())
        .sum()
    )

    print(ticker, "| Gaps > 1 minute:", int(gaps))

RELIANCE | Gaps > 1 minute: 4
HDFCBANK | Gaps > 1 minute: 4
NYKAA | Gaps > 1 minute: 4
RVNL | Gaps > 1 minute: 3
HAL | Gaps > 1 minute: 4

In [57]:
for ticker, df in stocks.items():

    invalid_ohlc = (
        (df["high"] < df["open"]) |
        (df["high"] < df["close"]) |
        (df["low"] > df["open"]) |
        (df["low"] > df["close"]) |
        (df["high"] < df["low"])
    )

    if invalid_ohlc.any():
        print("\n", ticker)
        print(
            df.loc[
                invalid_ohlc,
                ["date", "open", "high", "low", "close", "volume", "oi"]
            ].to_string(index=False)
        )

 HDFCBANK
               date  open  high   low  close   volume  oi
2024-06-25 09:15:00 835.6 839.8 837.4  839.6 370096.0   0

 HAL
               date   open   high    low  close  volume  oi
2024-06-25 09:15:00 5375.0 5368.0 5347.6 5368.0 72552.0   0

In [58]:
for ticker, df in stocks.items():

    zero_volume = df[df["volume"] == 0]

    print(
        "\n", ticker,
        "| Zero-volume rows:", len(zero_volume)
    )

    print(
        zero_volume[
            ["date", "open", "high", "low", "close", "volume"]
        ].head(5).to_string(index=False)
    )

 RELIANCE | Zero-volume rows: 190
               date    open    high     low   close  volume
2024-04-23 10:54:00 1473.60 1473.60 1473.60 1473.60     0.0
2024-09-30 15:27:00 1476.00 1476.00 1476.00 1476.00     0.0
2024-10-01 13:29:00 1465.70 1465.70 1465.70 1465.70     0.0
2024-12-17 10:07:00 1252.80 1252.80 1252.80 1252.80     0.0
2024-12-23 13:28:00 1215.35 1215.35 1215.35 1215.35     0.0

 HDFCBANK | Zero-volume rows: 187
               date  open  high   low  close  volume
2024-04-23 10:54:00 755.7 755.7 755.7  755.7     0.0
2024-04-25 09:34:00 756.8 756.8 756.6  756.8     0.0
2024-09-30 15:06:00 865.6 865.6 865.6  865.6     0.0
2025-03-11 10:42:00 845.2 845.2 845.2  845.2     0.0
2025-03-11 11:24:00 844.0 844.0 844.0  844.0     0.0

 NYKAA | Zero-volume rows: 191
               date   open   high    low  close  volume
2023-11-01 11:05:00 140.35 140.35 140.35 140.35     0.0
2023-11-01 12:51:00 139.35 139.35 139.35 139.35     0.0
2024-04-23 10:50:00 169.95 170.00 169.95 169.95     0.0
2024-08-20 12:13:00 192.33 192.33 192.32 192.32     0.0
2024-09-30 15:06:00 195.47 195.47 195.47 195.47     0.0

 RVNL | Zero-volume rows: 191
               date   open   high    low  close  volume
2024-04-23 10:50:00 264.65 264.65 264.60 264.60     0.0
2024-09-30 15:27:00 533.85 533.85 533.85 533.85     0.0
2024-10-01 13:29:00 525.45 525.45 525.45 525.45     0.0
2024-12-17 10:07:00 473.30 473.30 473.30 473.30     0.0
2024-12-23 13:28:00 432.00 432.00 432.00 432.00     0.0

 HAL | Zero-volume rows: 187
               date    open    high     low   close  volume
2024-04-23 10:54:00 3793.50 3793.50 3793.50 3793.50     0.0
2024-04-25 09:34:00 4017.00 4017.95 4015.95 4017.95     0.0
2024-09-30 15:06:00 4412.75 4412.75 4412.75 4412.75     0.0
2025-03-11 10:42:00 3428.75 3428.75 3428.75 3428.75     0.0
2025-03-11 11:24:00 3436.90 3436.90 3436.90 3436.90     0.0

In [59]:
for ticker, df in stocks.items():

    df = df.sort_values("date").copy()

    diff = df["date"].diff()

    gaps = df.loc[
        diff > pd.Timedelta(minutes=1),
        ["date"]
    ].copy()

    gaps["previous_bar"] = df["date"].shift(1).loc[gaps.index]
    gaps["gap_minutes"] = (
        gaps["date"] - gaps["previous_bar"]
    ).dt.total_seconds() / 60

    print("\n", ticker)
    print(gaps.to_string(index=False))

 RELIANCE
               date        previous_bar  gap_minutes
2023-08-22 09:15:00 2023-08-21 15:29:00       1066.0
2023-08-23 09:15:00 2023-08-22 15:29:00       1066.0
2023-08-24 09:15:00 2023-08-23 15:29:00       1066.0
2023-08-25 09:15:00 2023-08-24 15:29:00       1066.0
2023-08-28 09:15:00 2023-08-25 15:29:00       3946.0
2023-08-29 09:15:00 2023-08-28 15:29:00       1066.0
2023-08-30 09:15:00 2023-08-29 15:29:00       1066.0
2023-08-31 09:15:00 2023-08-30 15:29:00       1066.0
2023-09-01 09:15:00 2023-08-31 15:29:00       1066.0
2023-09-04 09:15:00 2023-09-01 15:29:00       3946.0
2023-09-05 09:15:00 2023-09-04 15:29:00       1066.0
2023-09-06 09:15:00 2023-09-05 15:29:00       1066.0
2023-09-07 09:15:00 2023-09-06 15:29:00       1066.0
2023-09-08 09:15:00 2023-09-07 15:29:00       1066.0
2023-09-11 09:15:00 2023-09-08 15:29:00       3946.0
2023-09-12 09:15:00 2023-09-11 15:29:00       1066.0
2023-09-13 09:15:00 2023-09-12 15:29:00       1066.0
2023-09-14 09:15:00 2023-09-13 15:29:00       1066.0
2023-09-15 09:15:00 2023-09-14 15:29:00       1066.0
2023-09-18 09:15:00 2023-09-15 15:29:00       3946.0
2023-09-20 09:15:00 2023-09-18 15:29:00       2506.0
2023-09-21 09:15:00 2023-09-20 15:29:00       1066.0
2023-09-22 09:15:00 2023-09-21 15:29:00       1066.0
2023-09-25 09:15:00 2023-09-22 15:29:00       3946.0
2023-09-26 09:15:00 2023-09-25 15:29:00       1066.0
2023-09-27 09:15:00 2023-09-26 15:29:00       1066.0
2023-09-28 09:15:00 2023-09-27 15:29:00       1066.0
2023-09-29 09:15:00 2023-09-28 15:29:00       1066.0
2023-10-03 09:15:00 2023-09-29 15:29:00       5386.0
2023-10-04 09:15:00 2023-10-03 15:29:00       1066.0
2023-10-05 09:15:00 2023-10-04 15:29:00       1066.0
2023-10-06 09:15:00 2023-10-05 15:29:00       1066.0
2023-10-09 09:15:00 2023-10-06 15:29:00       3946.0
2023-10-10 09:15:00 2023-10-09 15:29:00       1066.0
2023-10-11 09:15:00 2023-10-10 15:29:00       1066.0
2023-10-12 09:15:00 2023-10-11 15:29:00       1066.0
2023-10-13 09:15:00 2023-10-12 15:29:00       1066.0
2023-10-16 09:15:00 2023-10-13 15:29:00       3946.0
2023-10-17 09:15:00 2023-10-16 15:29:00       1066.0
2023-10-18 09:15:00 2023-10-17 15:29:00       1066.0
2023-10-19 09:15:00 2023-10-18 15:29:00       1066.0
2023-10-20 09:15:00 2023-10-19 15:29:00       1066.0
2023-10-23 09:15:00 2023-10-20 15:29:00       3946.0
2023-10-25 09:15:00 2023-10-23 15:29:00       2506.0
2023-10-26 09:15:00 2023-10-25 15:29:00       1066.0
2023-10-27 09:15:00 2023-10-26 15:29:00       1066.0
2023-10-30 09:15:00 2023-10-27 15:29:00       3946.0
2023-10-31 09:15:00 2023-10-30 15:29:00       1066.0
2023-11-01 09:15:00 2023-10-31 15:29:00       1066.0
2023-11-02 09:15:00 2023-11-01 15:29:00       1066.0
2023-11-03 09:15:00 2023-11-02 15:29:00       1066.0
2023-11-06 09:15:00 2023-11-03 15:29:00       3946.0
2023-11-07 09:15:00 2023-11-06 15:29:00       1066.0
2023-11-08 09:15:00 2023-11-07 15:29:00       1066.0
2023-11-09 09:15:00 2023-11-08 15:29:00       1066.0
2023-11-10 09:15:00 2023-11-09 15:29:00       1066.0
2023-11-12 18:15:00 2023-11-10 15:29:00       3046.0
2023-11-13 09:15:00 2023-11-12 19:14:00        841.0
2023-11-15 09:15:00 2023-11-13 15:29:00       2506.0
2023-11-16 09:15:00 2023-11-15 15:29:00       1066.0
2023-11-17 09:15:00 2023-11-16 15:29:00       1066.0
2023-11-20 09:15:00 2023-11-17 15:29:00       3946.0
2023-11-21 09:15:00 2023-11-20 15:29:00       1066.0
2023-11-22 09:15:00 2023-11-21 15:29:00       1066.0
2023-11-23 09:15:00 2023-11-22 15:29:00       1066.0
2023-11-24 09:15:00 2023-11-23 15:29:00       1066.0
2023-11-28 09:15:00 2023-11-24 15:29:00       5386.0
2023-11-29 09:15:00 2023-11-28 15:29:00       1066.0
2023-11-30 09:15:00 2023-11-29 15:29:00       1066.0
2023-12-01 09:15:00 2023-11-30 15:29:00       1066.0
2023-12-04 09:15:00 2023-12-01 15:29:00       3946.0
2023-12-05 09:15:00 2023-12-04 15:29:00       1066.0
2023-12-06 09:15:00 2023-12-05 15:29:00       1066.0
2023-12-07 09:15:00 2023-12-06 15:29:00       1066.0
2023-12-08 09:15:00 2023-12-07 15:29:00       1066.0
2023-12-11 09:15:00 2023-12-08 15:29:00       3946.0
2023-12-12 09:15:00 2023-12-11 15:29:00       1066.0
2023-12-13 09:15:00 2023-12-12 15:29:00       1066.0
2023-12-14 09:15:00 2023-12-13 15:29:00       1066.0
2023-12-15 09:15:00 2023-12-14 15:29:00       1066.0
2023-12-18 09:15:00 2023-12-15 15:29:00       3946.0
2023-12-19 09:15:00 2023-12-18 15:29:00       1066.0
2023-12-20 09:15:00 2023-12-19 15:29:00       1066.0
2023-12-21 09:15:00 2023-12-20 15:29:00       1066.0
2023-12-22 09:15:00 2023-12-21 15:29:00       1066.0
2023-12-26 09:15:00 2023-12-22 15:29:00       5386.0
2023-12-27 09:15:00 2023-12-26 15:29:00       1066.0
2023-12-28 09:15:00 2023-12-27 15:29:00       1066.0
2023-12-29 09:15:00 2023-12-28 15:29:00       1066.0
2024-01-01 09:15:00 2023-12-29 15:29:00       3946.0
2024-01-02 09:15:00 2024-01-01 15:29:00       1066.0
2024-01-03 09:15:00 2024-01-02 15:29:00       1066.0
2024-01-04 09:15:00 2024-01-03 15:29:00       1066.0
2024-01-05 09:15:00 2024-01-04 15:29:00       1066.0
2024-01-08 09:15:00 2024-01-05 15:29:00       3946.0
2024-01-09 09:15:00 2024-01-08 15:29:00       1066.0
2024-01-10 09:15:00 2024-01-09 15:29:00       1066.0
2024-01-11 09:15:00 2024-01-10 15:29:00       1066.0
2024-01-12 09:15:00 2024-01-11 15:29:00       1066.0
2024-01-15 09:15:00 2024-01-12 15:29:00       3946.0
2024-01-16 09:15:00 2024-01-15 15:29:00       1066.0
2024-01-17 09:15:00 2024-01-16 15:29:00       1066.0
2024-01-18 09:15:00 2024-01-17 15:29:00       1066.0
2024-01-19 09:15:00 2024-01-18 15:29:00       1066.0
2024-01-20 09:15:00 2024-01-19 15:29:00       1066.0
2024-01-23 09:15:00 2024-01-20 15:29:00       3946.0
2024-01-24 09:15:00 2024-01-23 15:29:00       1066.0
2024-01-25 09:15:00 2024-01-24 15:29:00       1066.0
2024-01-29 09:15:00 2024-01-25 15:29:00       5386.0
2024-01-30 09:15:00 2024-01-29 15:29:00       1066.0
2024-01-31 09:15:00 2024-01-30 15:29:00       1066.0
2024-02-01 09:15:00 2024-01-31 15:29:00       1066.0
2024-02-02 09:15:00 2024-02-01 15:29:00       1066.0
2024-02-05 09:15:00 2024-02-02 15:29:00       3946.0
2024-02-06 09:15:00 2024-02-05 15:29:00       1066.0
2024-02-07 09:15:00 2024-02-06 15:29:00       1066.0
2024-02-08 09:15:00 2024-02-07 15:29:00       1066.0
2024-02-09 09:15:00 2024-02-08 15:29:00       1066.0
2024-02-12 09:15:00 2024-02-09 15:29:00       3946.0
2024-02-13 09:15:00 2024-02-12 15:29:00       1066.0
2024-02-14 09:15:00 2024-02-13 15:29:00       1066.0
2024-02-15 09:15:00 2024-02-14 15:29:00       1066.0
2024-02-16 09:15:00 2024-02-15 15:29:00       1066.0
2024-02-19 09:15:00 2024-02-16 15:29:00       3946.0
2024-02-20 09:15:00 2024-02-19 15:29:00       1066.0
2024-02-21 09:15:00 2024-02-20 15:29:00       1066.0
2024-02-22 09:15:00 2024-02-21 15:29:00       1066.0
2024-02-23 09:15:00 2024-02-22 15:29:00       1066.0
2024-02-26 09:15:00 2024-02-23 15:29:00       3946.0
2024-02-27 09:15:00 2024-02-26 15:29:00       1066.0
2024-02-28 09:15:00 2024-02-27 15:29:00       1066.0
2024-02-29 09:15:00 2024-02-28 15:29:00       1066.0
2024-03-01 09:15:00 2024-02-29 15:29:00       1066.0
2024-03-02 09:15:00 2024-03-01 15:29:00       1066.0
2024-03-02 11:30:00 2024-03-02 09:59:00         91.0
2024-03-04 09:15:00 2024-03-02 12:29:00       2686.0
2024-03-05 09:15:00 2024-03-04 15:29:00       1066.0
2024-03-06 09:15:00 2024-03-05 15:29:00       1066.0
2024-03-07 09:15:00 2024-03-06 15:29:00       1066.0
2024-03-11 09:15:00 2024-03-07 15:29:00       5386.0
2024-03-12 09:15:00 2024-03-11 15:29:00       1066.0
2024-03-13 09:15:00 2024-03-12 15:29:00       1066.0
2024-03-14 09:15:00 2024-03-13 15:29:00       1066.0
2024-03-15 09:15:00 2024-03-14 15:29:00       1066.0
2024-03-18 09:15:00 2024-03-15 15:29:00       3946.0
2024-03-19 09:15:00 2024-03-18 15:29:00       1066.0
2024-03-20 09:15:00 2024-03-19 15:29:00       1066.0
2024-03-21 09:15:00 2024-03-20 15:29:00       1066.0
2024-03-22 09:15:00 2024-03-21 15:29:00       1066.0
2024-03-26 09:15:00 2024-03-22 15:29:00       5386.0
2024-03-27 09:15:00 2024-03-26 15:29:00       1066.0
2024-03-28 09:15:00 2024-03-27 15:29:00       1066.0
2024-04-01 09:15:00 2024-03-28 15:29:00       5386.0
2024-04-02 09:15:00 2024-04-01 15:29:00       1066.0
2024-04-03 09:15:00 2024-04-02 15:29:00       1066.0
2024-04-04 09:15:00 2024-04-03 15:29:00       1066.0
2024-04-05 09:15:00 2024-04-04 15:29:00       1066.0
2024-04-08 09:15:00 2024-04-05 15:29:00       3946.0
2024-04-09 09:15:00 2024-04-08 15:29:00       1066.0
2024-04-10 09:15:00 2024-04-09 15:29:00       1066.0
2024-04-12 09:15:00 2024-04-10 15:29:00       2506.0
2024-04-15 09:15:00 2024-04-12 15:29:00       3946.0
2024-04-16 09:15:00 2024-04-15 15:29:00       1066.0
2024-04-18 09:15:00 2024-04-16 15:29:00       2506.0
2024-04-19 09:15:00 2024-04-18 15:29:00       1066.0
2024-04-22 09:15:00 2024-04-19 15:29:00       3946.0
2024-04-23 09:15:00 2024-04-22 15:29:00       1066.0
2024-04-23 10:54:00 2024-04-23 10:51:00          3.0
2024-04-23 10:58:00 2024-04-23 10:54:00          4.0
2024-04-24 09:15:00 2024-04-23 15:29:00       1066.0
2024-04-25 09:15:00 2024-04-24 15:29:00       1066.0
2024-04-26 09:15:00 2024-04-25 15:29:00       1066.0
2024-04-29 09:15:00 2024-04-26 15:29:00       3946.0
2024-04-30 09:15:00 2024-04-29 15:29:00       1066.0
2024-05-02 09:15:00 2024-04-30 15:29:00       2506.0
2024-05-03 09:15:00 2024-05-02 15:29:00       1066.0
2024-05-06 09:15:00 2024-05-03 15:29:00       3946.0
2024-05-07 09:15:00 2024-05-06 15:29:00       1066.0
2024-05-08 09:15:00 2024-05-07 15:29:00       1066.0
2024-05-09 09:15:00 2024-05-08 15:29:00       1066.0
2024-05-10 09:15:00 2024-05-09 15:29:00       1066.0
2024-05-13 09:15:00 2024-05-10 15:29:00       3946.0
2024-05-14 09:15:00 2024-05-13 15:29:00       1066.0
2024-05-15 09:15:00 2024-05-14 15:29:00       1066.0
2024-05-16 09:15:00 2024-05-15 15:29:00       1066.0
2024-05-17 09:15:00 2024-05-16 15:29:00       1066.0
2024-05-18 09:15:00 2024-05-17 15:29:00       1066.0
2024-05-18 11:30:00 2024-05-18 09:59:00         91.0
2024-05-21 09:15:00 2024-05-18 12:29:00       4126.0
2024-05-22 09:15:00 2024-05-21 15:29:00       1066.0
2024-05-23 09:15:00 2024-05-22 15:29:00       1066.0
2024-05-24 09:15:00 2024-05-23 15:29:00       1066.0
2024-05-27 09:15:00 2024-05-24 15:29:00       3946.0
2024-05-28 09:15:00 2024-05-27 15:29:00       1066.0
2024-05-29 09:15:00 2024-05-28 15:29:00       1066.0
2024-05-30 09:15:00 2024-05-29 15:29:00       1066.0
2024-05-31 09:15:00 2024-05-30 15:29:00       1066.0
2024-06-03 09:15:00 2024-05-31 15:29:00       3946.0
2024-06-04 09:15:00 2024-06-03 15:29:00       1066.0
2024-06-05 09:15:00 2024-06-04 15:29:00       1066.0
2024-06-06 09:15:00 2024-06-05 15:29:00       1066.0
2024-06-07 09:15:00 2024-06-06 15:29:00       1066.0
2024-06-10 09:15:00 2024-06-07 15:29:00       3946.0
2024-06-11 09:15:00 2024-06-10 15:29:00       1066.0
2024-06-12 09:15:00 2024-06-11 15:29:00       1066.0
2024-06-13 09:15:00 2024-06-12 15:29:00       1066.0
2024-06-14 09:15:00 2024-06-13 15:29:00       1066.0
2024-06-18 09:15:00 2024-06-14 15:29:00       5386.0
2024-06-19 09:15:00 2024-06-18 15:29:00       1066.0
2024-06-20 09:15:00 2024-06-19 15:29:00       1066.0
2024-06-21 09:15:00 2024-06-20 15:29:00       1066.0
2024-06-24 09:15:00 2024-06-21 15:29:00       3946.0
2024-06-25 09:15:00 2024-06-24 15:29:00       1066.0
2024-06-26 09:15:00 2024-06-25 15:29:00       1066.0
2024-06-27 09:15:00 2024-06-26 15:29:00       1066.0
2024-06-28 09:15:00 2024-06-27 15:29:00       1066.0
2024-07-01 09:15:00 2024-06-28 15:29:00       3946.0
2024-07-02 09:15:00 2024-07-01 15:29:00       1066.0
2024-07-03 09:15:00 2024-07-02 15:29:00       1066.0
2024-07-04 09:15:00 2024-07-03 15:29:00       1066.0
2024-07-05 09:15:00 2024-07-04 15:29:00       1066.0
2024-07-08 09:15:00 2024-07-05 15:29:00       3946.0
2024-07-09 09:15:00 2024-07-08 15:29:00       1066.0
2024-07-10 09:15:00 2024-07-09 15:29:00       1066.0
2024-07-11 09:15:00 2024-07-10 15:29:00       1066.0
2024-07-12 09:15:00 2024-07-11 15:29:00       1066.0
2024-07-15 09:15:00 2024-07-12 15:29:00       3946.0
2024-07-16 09:15:00 2024-07-15 15:29:00       1066.0
2024-07-18 09:15:00 2024-07-16 15:29:00       2506.0
2024-07-19 09:15:00 2024-07-18 15:29:00       1066.0
2024-07-22 09:15:00 2024-07-19 15:29:00       3946.0
2024-07-23 09:15:00 2024-07-22 15:29:00       1066.0
2024-07-24 09:15:00 2024-07-23 15:29:00       1066.0
2024-07-25 09:15:00 2024-07-24 15:29:00       1066.0
2024-07-26 09:15:00 2024-07-25 15:29:00       1066.0
2024-07-29 09:15:00 2024-07-26 15:29:00       3946.0
2024-07-30 09:15:00 2024-07-29 15:29:00       1066.0
2024-07-31 09:15:00 2024-07-30 15:29:00       1066.0
2024-08-01 09:15:00 2024-07-31 15:29:00       1066.0
2024-08-02 09:15:00 2024-08-01 15:29:00       1066.0
2024-08-05 09:15:00 2024-08-02 15:29:00       3946.0
2024-08-06 09:15:00 2024-08-05 15:29:00       1066.0
2024-08-07 09:15:00 2024-08-06 15:29:00       1066.0
2024-08-08 09:15:00 2024-08-07 15:29:00       1066.0
2024-08-09 09:15:00 2024-08-08 15:29:00       1066.0
2024-08-12 09:15:00 2024-08-09 15:29:00       3946.0
2024-08-13 09:15:00 2024-08-12 15:29:00       1066.0
2024-08-14 09:15:00 2024-08-13 15:29:00       1066.0
2024-08-16 09:15:00 2024-08-14 15:29:00       2506.0
2024-08-19 09:15:00 2024-08-16 15:29:00       3946.0
2024-08-20 09:15:00 2024-08-19 15:29:00       1066.0
2024-08-21 09:15:00 2024-08-20 15:29:00       1066.0
2024-08-22 09:15:00 2024-08-21 15:29:00       1066.0
2024-08-23 09:15:00 2024-08-22 15:29:00       1066.0
2024-08-26 09:15:00 2024-08-23 15:29:00       3946.0
2024-08-27 09:15:00 2024-08-26 15:29:00       1066.0
2024-08-28 09:15:00 2024-08-27 15:29:00       1066.0
2024-08-29 09:15:00 2024-08-28 15:29:00       1066.0
2024-08-30 09:15:00 2024-08-29 15:29:00       1066.0
2024-09-02 09:15:00 2024-08-30 15:29:00       3946.0
2024-09-03 09:15:00 2024-09-02 15:29:00       1066.0
2024-09-04 09:15:00 2024-09-03 15:29:00       1066.0
2024-09-05 09:15:00 2024-09-04 15:29:00       1066.0
2024-09-06 09:15:00 2024-09-05 15:29:00       1066.0
2024-09-09 09:15:00 2024-09-06 15:29:00       3946.0
2024-09-10 09:15:00 2024-09-09 15:29:00       1066.0
2024-09-11 09:15:00 2024-09-10 15:29:00       1066.0
2024-09-12 09:15:00 2024-09-11 15:29:00       1066.0
2024-09-13 09:15:00 2024-09-12 15:29:00       1066.0
2024-09-16 09:15:00 2024-09-13 15:29:00       3946.0
2024-09-17 09:15:00 2024-09-16 15:29:00       1066.0
2024-09-18 09:15:00 2024-09-17 15:29:00       1066.0
2024-09-19 09:15:00 2024-09-18 15:29:00       1066.0
2024-09-20 09:15:00 2024-09-19 15:29:00       1066.0
2024-09-23 09:15:00 2024-09-20 15:29:00       3946.0
2024-09-24 09:15:00 2024-09-23 15:29:00       1066.0
2024-09-25 09:15:00 2024-09-24 15:29:00       1066.0
2024-09-26 09:15:00 2024-09-25 15:29:00       1066.0
2024-09-27 09:15:00 2024-09-26 15:29:00       1066.0
2024-09-30 09:15:00 2024-09-27 15:29:00       3946.0
2024-10-01 09:15:00 2024-09-30 15:29:00       1066.0
2024-10-03 09:15:00 2024-10-01 15:29:00       2506.0
2024-10-04 09:15:00 2024-10-03 15:29:00       1066.0
2024-10-07 09:15:00 2024-10-04 15:29:00       3946.0
2024-10-08 09:15:00 2024-10-07 15:29:00       1066.0
2024-10-09 09:15:00 2024-10-08 15:29:00       1066.0
2024-10-10 09:15:00 2024-10-09 15:29:00       1066.0
2024-10-11 09:15:00 2024-10-10 15:29:00       1066.0
2024-10-14 09:15:00 2024-10-11 15:29:00       3946.0
2024-10-15 09:15:00 2024-10-14 15:29:00       1066.0
2024-10-16 09:15:00 2024-10-15 15:29:00       1066.0
2024-10-17 09:15:00 2024-10-16 15:29:00       1066.0
2024-10-18 09:15:00 2024-10-17 15:29:00       1066.0
2024-10-21 09:15:00 2024-10-18 15:29:00       3946.0
2024-10-22 09:15:00 2024-10-21 15:29:00       1066.0
2024-10-23 09:15:00 2024-10-22 15:29:00       1066.0
2024-10-24 09:15:00 2024-10-23 15:29:00       1066.0
2024-10-25 09:15:00 2024-10-24 15:29:00       1066.0
2024-10-28 09:15:00 2024-10-25 15:29:00       3946.0
2024-10-29 09:15:00 2024-10-28 15:29:00       1066.0
2024-10-30 09:15:00 2024-10-29 15:29:00       1066.0
2024-10-31 09:15:00 2024-10-30 15:29:00       1066.0
2024-11-01 18:00:00 2024-10-31 15:29:00       1591.0
2024-11-04 09:15:00 2024-11-01 18:59:00       3736.0
2024-11-05 09:15:00 2024-11-04 15:29:00       1066.0
2024-11-06 09:15:00 2024-11-05 15:29:00       1066.0
2024-11-07 09:15:00 2024-11-06 15:29:00       1066.0
2024-11-08 09:15:00 2024-11-07 15:29:00       1066.0
2024-11-11 09:15:00 2024-11-08 15:29:00       3946.0
2024-11-12 09:15:00 2024-11-11 15:29:00       1066.0
2024-11-13 09:15:00 2024-11-12 15:29:00       1066.0
2024-11-14 09:15:00 2024-11-13 15:29:00       1066.0
2024-11-18 09:15:00 2024-11-14 15:29:00       5386.0
2024-11-19 09:15:00 2024-11-18 15:29:00       1066.0
2024-11-21 09:15:00 2024-11-19 15:29:00       2506.0
2024-11-22 09:15:00 2024-11-21 15:29:00       1066.0
2024-11-25 09:15:00 2024-11-22 15:29:00       3946.0
2024-11-26 09:15:00 2024-11-25 15:29:00       1066.0
2024-11-27 09:15:00 2024-11-26 15:29:00       1066.0
2024-11-28 09:15:00 2024-11-27 15:29:00       1066.0
2024-11-29 09:15:00 2024-11-28 15:29:00       1066.0
2024-12-02 09:15:00 2024-11-29 15:29:00       3946.0
2024-12-03 09:15:00 2024-12-02 15:29:00       1066.0
2024-12-04 09:15:00 2024-12-03 15:29:00       1066.0
2024-12-05 09:15:00 2024-12-04 15:29:00       1066.0
2024-12-06 09:15:00 2024-12-05 15:29:00       1066.0
2024-12-09 09:15:00 2024-12-06 15:29:00       3946.0
2024-12-10 09:15:00 2024-12-09 15:29:00       1066.0
2024-12-11 09:15:00 2024-12-10 15:29:00       1066.0
2024-12-12 09:15:00 2024-12-11 15:29:00       1066.0
2024-12-13 09:15:00 2024-12-12 15:29:00       1066.0
2024-12-16 09:15:00 2024-12-13 15:29:00       3946.0
2024-12-17 09:15:00 2024-12-16 15:29:00       1066.0
2024-12-18 09:15:00 2024-12-17 15:29:00       1066.0
2024-12-19 09:15:00 2024-12-18 15:29:00       1066.0
2024-12-20 09:15:00 2024-12-19 15:29:00       1066.0
2024-12-23 09:15:00 2024-12-20 15:29:00       3946.0
2024-12-24 09:15:00 2024-12-23 15:29:00       1066.0
2024-12-26 09:15:00 2024-12-24 15:29:00       2506.0
2024-12-27 09:15:00 2024-12-26 15:29:00       1066.0
2024-12-30 09:15:00 2024-12-27 15:29:00       3946.0
2024-12-31 09:15:00 2024-12-30 15:29:00       1066.0
2025-01-01 09:15:00 2024-12-31 15:29:00       1066.0
2025-01-02 09:15:00 2025-01-01 15:29:00       1066.0
2025-01-03 09:15:00 2025-01-02 15:29:00       1066.0
2025-01-06 09:15:00 2025-01-03 15:29:00       3946.0
2025-01-07 09:15:00 2025-01-06 15:29:00       1066.0
2025-01-08 09:15:00 2025-01-07 15:29:00       1066.0
2025-01-09 09:15:00 2025-01-08 15:29:00       1066.0
2025-01-10 09:15:00 2025-01-09 15:29:00       1066.0
2025-01-13 09:15:00 2025-01-10 15:29:00       3946.0
2025-01-14 09:15:00 2025-01-13 15:29:00       1066.0
2025-01-15 09:15:00 2025-01-14 15:29:00       1066.0
2025-01-16 09:15:00 2025-01-15 15:29:00       1066.0
2025-01-17 09:15:00 2025-01-16 15:29:00       1066.0
2025-01-20 09:15:00 2025-01-17 15:29:00       3946.0
2025-01-21 09:15:00 2025-01-20 15:29:00       1066.0
2025-01-22 09:15:00 2025-01-21 15:29:00       1066.0
2025-01-23 09:15:00 2025-01-22 15:29:00       1066.0
2025-01-24 09:15:00 2025-01-23 15:29:00       1066.0
2025-01-27 09:15:00 2025-01-24 15:29:00       3946.0
2025-01-28 09:15:00 2025-01-27 15:29:00       1066.0
2025-01-29 09:15:00 2025-01-28 15:29:00       1066.0
2025-01-30 09:15:00 2025-01-29 15:29:00       1066.0
2025-01-31 09:15:00 2025-01-30 15:29:00       1066.0
2025-02-01 09:15:00 2025-01-31 15:29:00       1066.0
2025-02-03 09:15:00 2025-02-01 15:29:00       2506.0
2025-02-04 09:15:00 2025-02-03 15:29:00       1066.0
2025-02-05 09:15:00 2025-02-04 15:29:00       1066.0
2025-02-06 09:15:00 2025-02-05 15:29:00       1066.0
2025-02-07 09:15:00 2025-02-06 15:29:00       1066.0
2025-02-10 09:15:00 2025-02-07 15:29:00       3946.0
2025-02-11 09:15:00 2025-02-10 15:29:00       1066.0
2025-02-12 09:15:00 2025-02-11 15:29:00       1066.0
2025-02-13 09:15:00 2025-02-12 15:29:00       1066.0
2025-02-14 09:15:00 2025-02-13 15:29:00       1066.0

In [60]:
for ticker, df in stocks.items():

    df = df.sort_values("date").copy()
    diff = df["date"].diff()

    gaps = df.loc[
        diff > pd.Timedelta(minutes=1),
        ["date"]
    ].copy()

    gaps["previous_bar"] = df["date"].shift(1).loc[gaps.index]

    gaps["gap_minutes"] = (
        gaps["date"] - gaps["previous_bar"]
    ).dt.total_seconds() / 60

    print("\n================", ticker, "================")
    
    if len(gaps) == 0:
        print("No gaps")
    else:
        print(
            gaps[
                ["previous_bar", "date", "gap_minutes"]
            ].to_string(index=False)
        )

================ RELIANCE ================
       previous_bar                date  gap_minutes
2023-08-21 15:29:00 2023-08-22 09:15:00       1066.0
2023-08-22 15:29:00 2023-08-23 09:15:00       1066.0
2023-08-23 15:29:00 2023-08-24 09:15:00       1066.0
2023-08-24 15:29:00 2023-08-25 09:15:00       1066.0
2023-08-25 15:29:00 2023-08-28 09:15:00       3946.0
2023-08-28 15:29:00 2023-08-29 09:15:00       1066.0
2023-08-29 15:29:00 2023-08-30 09:15:00       1066.0
2023-08-30 15:29:00 2023-08-31 09:15:00       1066.0
2023-08-31 15:29:00 2023-09-01 09:15:00       1066.0
2023-09-01 15:29:00 2023-09-04 09:15:00       3946.0
2023-09-04 15:29:00 2023-09-05 09:15:00       1066.0
2023-09-05 15:29:00 2023-09-06 09:15:00       1066.0
2023-09-06 15:29:00 2023-09-07 09:15:00       1066.0
2023-09-07 15:29:00 2023-09-08 09:15:00       1066.0
2023-09-08 15:29:00 2023-09-11 09:15:00       3946.0
2023-09-11 15:29:00 2023-09-12 09:15:00       1066.0
2023-09-12 15:29:00 2023-09-13 09:15:00       1066.0
2023-09-13 15:29:00 2023-09-14 09:15:00       1066.0
2023-09-14 15:29:00 2023-09-15 09:15:00       1066.0
2023-09-15 15:29:00 2023-09-18 09:15:00       3946.0
2023-09-18 15:29:00 2023-09-20 09:15:00       2506.0
2023-09-20 15:29:00 2023-09-21 09:15:00       1066.0
2023-09-21 15:29:00 2023-09-22 09:15:00       1066.0
2023-09-22 15:29:00 2023-09-25 09:15:00       3946.0
2023-09-25 15:29:00 2023-09-26 09:15:00       1066.0
2023-09-26 15:29:00 2023-09-27 09:15:00       1066.0
2023-09-27 15:29:00 2023-09-28 09:15:00       1066.0
2023-09-28 15:29:00 2023-09-29 09:15:00       1066.0
2023-09-29 15:29:00 2023-10-03 09:15:00       5386.0
2023-10-03 15:29:00 2023-10-04 09:15:00       1066.0
2023-10-04 15:29:00 2023-10-05 09:15:00       1066.0
2023-10-05 15:29:00 2023-10-06 09:15:00       1066.0
2023-10-06 15:29:00 2023-10-09 09:15:00       3946.0
2023-10-09 15:29:00 2023-10-10 09:15:00       1066.0
2023-10-10 15:29:00 2023-10-11 09:15:00       1066.0
2023-10-11 15:29:00 2023-10-12 09:15:00       1066.0
2023-10-12 15:29:00 2023-10-13 09:15:00       1066.0
2023-10-13 15:29:00 2023-10-16 09:15:00       3946.0
2023-10-16 15:29:00 2023-10-17 09:15:00       1066.0
2023-10-17 15:29:00 2023-10-18 09:15:00       1066.0
2023-10-18 15:29:00 2023-10-19 09:15:00       1066.0
2023-10-19 15:29:00 2023-10-20 09:15:00       1066.0
2023-10-20 15:29:00 2023-10-23 09:15:00       3946.0
2023-10-23 15:29:00 2023-10-25 09:15:00       2506.0
2023-10-25 15:29:00 2023-10-26 09:15:00       1066.0
2023-10-26 15:29:00 2023-10-27 09:15:00       1066.0
2023-10-27 15:29:00 2023-10-30 09:15:00       3946.0
2023-10-30 15:29:00 2023-10-31 09:15:00       1066.0
2023-10-31 15:29:00 2023-11-01 09:15:00       1066.0
2023-11-01 15:29:00 2023-11-02 09:15:00       1066.0
2023-11-02 15:29:00 2023-11-03 09:15:00       1066.0
2023-11-03 15:29:00 2023-11-06 09:15:00       3946.0
2023-11-06 15:29:00 2023-11-07 09:15:00       1066.0
2023-11-07 15:29:00 2023-11-08 09:15:00       1066.0
2023-11-08 15:29:00 2023-11-09 09:15:00       1066.0
2023-11-09 15:29:00 2023-11-10 09:15:00       1066.0
2023-11-10 15:29:00 2023-11-12 18:15:00       3046.0
2023-11-12 19:14:00 2023-11-13 09:15:00        841.0
2023-11-13 15:29:00 2023-11-15 09:15:00       2506.0
2023-11-15 15:29:00 2023-11-16 09:15:00       1066.0
2023-11-16 15:29:00 2023-11-17 09:15:00       1066.0
2023-11-17 15:29:00 2023-11-20 09:15:00       3946.0
2023-11-20 15:29:00 2023-11-21 09:15:00       1066.0
2023-11-21 15:29:00 2023-11-22 09:15:00       1066.0
2023-11-22 15:29:00 2023-11-23 09:15:00       1066.0
2023-11-23 15:29:00 2023-11-24 09:15:00       1066.0
2023-11-24 15:29:00 2023-11-28 09:15:00       5386.0
2023-11-28 15:29:00 2023-11-29 09:15:00       1066.0
2023-11-29 15:29:00 2023-11-30 09:15:00       1066.0
2023-11-30 15:29:00 2023-12-01 09:15:00       1066.0
2023-12-01 15:29:00 2023-12-04 09:15:00       3946.0
2023-12-04 15:29:00 2023-12-05 09:15:00       1066.0
2023-12-05 15:29:00 2023-12-06 09:15:00       1066.0
2023-12-06 15:29:00 2023-12-07 09:15:00       1066.0
2023-12-07 15:29:00 2023-12-08 09:15:00       1066.0
2023-12-08 15:29:00 2023-12-11 09:15:00       3946.0
2023-12-11 15:29:00 2023-12-12 09:15:00       1066.0
2023-12-12 15:29:00 2023-12-13 09:15:00       1066.0
2023-12-13 15:29:00 2023-12-14 09:15:00       1066.0
2023-12-14 15:29:00 2023-12-15 09:15:00       1066.0
2023-12-15 15:29:00 2023-12-18 09:15:00       3946.0
2023-12-18 15:29:00 2023-12-19 09:15:00       1066.0
2023-12-19 15:29:00 2023-12-20 09:15:00       1066.0
2023-12-20 15:29:00 2023-12-21 09:15:00       1066.0
2023-12-21 15:29:00 2023-12-22 09:15:00       1066.0
2023-12-22 15:29:00 2023-12-26 09:15:00       5386.0
2023-12-26 15:29:00 2023-12-27 09:15:00       1066.0
2023-12-27 15:29:00 2023-12-28 09:15:00       1066.0
2023-12-28 15:29:00 2023-12-29 09:15:00       1066.0
2023-12-29 15:29:00 2024-01-01 09:15:00       3946.0
2024-01-01 15:29:00 2024-01-02 09:15:00       1066.0
2024-01-02 15:29:00 2024-01-03 09:15:00       1066.0
2024-01-03 15:29:00 2024-01-04 09:15:00       1066.0
2024-01-04 15:29:00 2024-01-05 09:15:00       1066.0
2024-01-05 15:29:00 2024-01-08 09:15:00       3946.0
2024-01-08 15:29:00 2024-01-09 09:15:00       1066.0
2024-01-09 15:29:00 2024-01-10 09:15:00       1066.0
2024-01-10 15:29:00 2024-01-11 09:15:00       1066.0
2024-01-11 15:29:00 2024-01-12 09:15:00       1066.0
2024-01-12 15:29:00 2024-01-15 09:15:00       3946.0
2024-01-15 15:29:00 2024-01-16 09:15:00       1066.0
2024-01-16 15:29:00 2024-01-17 09:15:00       1066.0
2024-01-17 15:29:00 2024-01-18 09:15:00       1066.0
2024-01-18 15:29:00 2024-01-19 09:15:00       1066.0
2024-01-19 15:29:00 2024-01-20 09:15:00       1066.0
2024-01-20 15:29:00 2024-01-23 09:15:00       3946.0
2024-01-23 15:29:00 2024-01-24 09:15:00       1066.0
2024-01-24 15:29:00 2024-01-25 09:15:00       1066.0
2024-01-25 15:29:00 2024-01-29 09:15:00       5386.0
2024-01-29 15:29:00 2024-01-30 09:15:00       1066.0
2024-01-30 15:29:00 2024-01-31 09:15:00       1066.0
2024-01-31 15:29:00 2024-02-01 09:15:00       1066.0
2024-02-01 15:29:00 2024-02-02 09:15:00       1066.0
2024-02-02 15:29:00 2024-02-05 09:15:00       3946.0
2024-02-05 15:29:00 2024-02-06 09:15:00       1066.0
2024-02-06 15:29:00 2024-02-07 09:15:00       1066.0
2024-02-07 15:29:00 2024-02-08 09:15:00       1066.0
2024-02-08 15:29:00 2024-02-09 09:15:00       1066.0
2024-02-09 15:29:00 2024-02-12 09:15:00       3946.0
2024-02-12 15:29:00 2024-02-13 09:15:00       1066.0
2024-02-13 15:29:00 2024-02-14 09:15:00       1066.0
2024-02-14 15:29:00 2024-02-15 09:15:00       1066.0
2024-02-15 15:29:00 2024-02-16 09:15:00       1066.0
2024-02-16 15:29:00 2024-02-19 09:15:00       3946.0
2024-02-19 15:29:00 2024-02-20 09:15:00       1066.0
2024-02-20 15:29:00 2024-02-21 09:15:00       1066.0
2024-02-21 15:29:00 2024-02-22 09:15:00       1066.0
2024-02-22 15:29:00 2024-02-23 09:15:00       1066.0
2024-02-23 15:29:00 2024-02-26 09:15:00       3946.0
2024-02-26 15:29:00 2024-02-27 09:15:00       1066.0
2024-02-27 15:29:00 2024-02-28 09:15:00       1066.0
2024-02-28 15:29:00 2024-02-29 09:15:00       1066.0
2024-02-29 15:29:00 2024-03-01 09:15:00       1066.0
2024-03-01 15:29:00 2024-03-02 09:15:00       1066.0
2024-03-02 09:59:00 2024-03-02 11:30:00         91.0
2024-03-02 12:29:00 2024-03-04 09:15:00       2686.0
2024-03-04 15:29:00 2024-03-05 09:15:00       1066.0
2024-03-05 15:29:00 2024-03-06 09:15:00       1066.0
2024-03-06 15:29:00 2024-03-07 09:15:00       1066.0
2024-03-07 15:29:00 2024-03-11 09:15:00       5386.0
2024-03-11 15:29:00 2024-03-12 09:15:00       1066.0
2024-03-12 15:29:00 2024-03-13 09:15:00       1066.0
2024-03-13 15:29:00 2024-03-14 09:15:00       1066.0
2024-03-14 15:29:00 2024-03-15 09:15:00       1066.0
2024-03-15 15:29:00 2024-03-18 09:15:00       3946.0
2024-03-18 15:29:00 2024-03-19 09:15:00       1066.0
2024-03-19 15:29:00 2024-03-20 09:15:00       1066.0
2024-03-20 15:29:00 2024-03-21 09:15:00       1066.0
2024-03-21 15:29:00 2024-03-22 09:15:00       1066.0
2024-03-22 15:29:00 2024-03-26 09:15:00       5386.0
2024-03-26 15:29:00 2024-03-27 09:15:00       1066.0
2024-03-27 15:29:00 2024-03-28 09:15:00       1066.0
2024-03-28 15:29:00 2024-04-01 09:15:00       5386.0
2024-04-01 15:29:00 2024-04-02 09:15:00       1066.0
2024-04-02 15:29:00 2024-04-03 09:15:00       1066.0
2024-04-03 15:29:00 2024-04-04 09:15:00       1066.0
2024-04-04 15:29:00 2024-04-05 09:15:00       1066.0
2024-04-05 15:29:00 2024-04-08 09:15:00       3946.0
2024-04-08 15:29:00 2024-04-09 09:15:00       1066.0
2024-04-09 15:29:00 2024-04-10 09:15:00       1066.0
2024-04-10 15:29:00 2024-04-12 09:15:00       2506.0
2024-04-12 15:29:00 2024-04-15 09:15:00       3946.0
2024-04-15 15:29:00 2024-04-16 09:15:00       1066.0
2024-04-16 15:29:00 2024-04-18 09:15:00       2506.0
2024-04-18 15:29:00 2024-04-19 09:15:00       1066.0
2024-04-19 15:29:00 2024-04-22 09:15:00       3946.0
2024-04-22 15:29:00 2024-04-23 09:15:00       1066.0
2024-04-23 10:51:00 2024-04-23 10:54:00          3.0
2024-04-23 10:54:00 2024-04-23 10:58:00          4.0
2024-04-23 15:29:00 2024-04-24 09:15:00       1066.0
2024-04-24 15:29:00 2024-04-25 09:15:00       1066.0
2024-04-25 15:29:00 2024-04-26 09:15:00       1066.0
2024-04-26 15:29:00 2024-04-29 09:15:00       3946.0
2024-04-29 15:29:00 2024-04-30 09:15:00       1066.0
2024-04-30 15:29:00 2024-05-02 09:15:00       2506.0
2024-05-02 15:29:00 2024-05-03 09:15:00       1066.0
2024-05-03 15:29:00 2024-05-06 09:15:00       3946.0
2024-05-06 15:29:00 2024-05-07 09:15:00       1066.0
2024-05-07 15:29:00 2024-05-08 09:15:00       1066.0
2024-05-08 15:29:00 2024-05-09 09:15:00       1066.0
2024-05-09 15:29:00 2024-05-10 09:15:00       1066.0
2024-05-10 15:29:00 2024-05-13 09:15:00       3946.0
2024-05-13 15:29:00 2024-05-14 09:15:00       1066.0
2024-05-14 15:29:00 2024-05-15 09:15:00       1066.0
2024-05-15 15:29:00 2024-05-16 09:15:00       1066.0
2024-05-16 15:29:00 2024-05-17 09:15:00       1066.0
2024-05-17 15:29:00 2024-05-18 09:15:00       1066.0
2024-05-18 09:59:00 2024-05-18 11:30:00         91.0
2024-05-18 12:29:00 2024-05-21 09:15:00       4126.0
2024-05-21 15:29:00 2024-05-22 09:15:00       1066.0
2024-05-22 15:29:00 2024-05-23 09:15:00       1066.0
2024-05-23 15:29:00 2024-05-24 09:15:00       1066.0
2024-05-24 15:29:00 2024-05-27 09:15:00       3946.0
2024-05-27 15:29:00 2024-05-28 09:15:00       1066.0
2024-05-28 15:29:00 2024-05-29 09:15:00       1066.0
2024-05-29 15:29:00 2024-05-30 09:15:00       1066.0
2024-05-30 15:29:00 2024-05-31 09:15:00       1066.0
2024-05-31 15:29:00 2024-06-03 09:15:00       3946.0
2024-06-03 15:29:00 2024-06-04 09:15:00       1066.0
2024-06-04 15:29:00 2024-06-05 09:15:00       1066.0
2024-06-05 15:29:00 2024-06-06 09:15:00       1066.0
2024-06-06 15:29:00 2024-06-07 09:15:00       1066.0
2024-06-07 15:29:00 2024-06-10 09:15:00       3946.0
2024-06-10 15:29:00 2024-06-11 09:15:00       1066.0
2024-06-11 15:29:00 2024-06-12 09:15:00       1066.0
2024-06-12 15:29:00 2024-06-13 09:15:00       1066.0
2024-06-13 15:29:00 2024-06-14 09:15:00       1066.0
2024-06-14 15:29:00 2024-06-18 09:15:00       5386.0
2024-06-18 15:29:00 2024-06-19 09:15:00       1066.0
2024-06-19 15:29:00 2024-06-20 09:15:00       1066.0
2024-06-20 15:29:00 2024-06-21 09:15:00       1066.0
2024-06-21 15:29:00 2024-06-24 09:15:00       3946.0
2024-06-24 15:29:00 2024-06-25 09:15:00       1066.0
2024-06-25 15:29:00 2024-06-26 09:15:00       1066.0
2024-06-26 15:29:00 2024-06-27 09:15:00       1066.0
2024-06-27 15:29:00 2024-06-28 09:15:00       1066.0
2024-06-28 15:29:00 2024-07-01 09:15:00       3946.0
2024-07-01 15:29:00 2024-07-02 09:15:00       1066.0
2024-07-02 15:29:00 2024-07-03 09:15:00       1066.0
2024-07-03 15:29:00 2024-07-04 09:15:00       1066.0
2024-07-04 15:29:00 2024-07-05 09:15:00       1066.0
2024-07-05 15:29:00 2024-07-08 09:15:00       3946.0
2024-07-08 15:29:00 2024-07-09 09:15:00       1066.0
2024-07-09 15:29:00 2024-07-10 09:15:00       1066.0
2024-07-10 15:29:00 2024-07-11 09:15:00       1066.0
2024-07-11 15:29:00 2024-07-12 09:15:00       1066.0
2024-07-12 15:29:00 2024-07-15 09:15:00       3946.0
2024-07-15 15:29:00 2024-07-16 09:15:00       1066.0
2024-07-16 15:29:00 2024-07-18 09:15:00       2506.0
2024-07-18 15:29:00 2024-07-19 09:15:00       1066.0
2024-07-19 15:29:00 2024-07-22 09:15:00       3946.0
2024-07-22 15:29:00 2024-07-23 09:15:00       1066.0
2024-07-23 15:29:00 2024-07-24 09:15:00       1066.0
2024-07-24 15:29:00 2024-07-25 09:15:00       1066.0
2024-07-25 15:29:00 2024-07-26 09:15:00       1066.0
2024-07-26 15:29:00 2024-07-29 09:15:00       3946.0
2024-07-29 15:29:00 2024-07-30 09:15:00       1066.0
2024-07-30 15:29:00 2024-07-31 09:15:00       1066.0
2024-07-31 15:29:00 2024-08-01 09:15:00       1066.0
2024-08-01 15:29:00 2024-08-02 09:15:00       1066.0
2024-08-02 15:29:00 2024-08-05 09:15:00       3946.0
2024-08-05 15:29:00 2024-08-06 09:15:00       1066.0
2024-08-06 15:29:00 2024-08-07 09:15:00       1066.0
2024-08-07 15:29:00 2024-08-08 09:15:00       1066.0
2024-08-08 15:29:00 2024-08-09 09:15:00       1066.0
2024-08-09 15:29:00 2024-08-12 09:15:00       3946.0
2024-08-12 15:29:00 2024-08-13 09:15:00       1066.0
2024-08-13 15:29:00 2024-08-14 09:15:00       1066.0
2024-08-14 15:29:00 2024-08-16 09:15:00       2506.0
2024-08-16 15:29:00 2024-08-19 09:15:00       3946.0
2024-08-19 15:29:00 2024-08-20 09:15:00       1066.0
2024-08-20 15:29:00 2024-08-21 09:15:00       1066.0
2024-08-21 15:29:00 2024-08-22 09:15:00       1066.0
2024-08-22 15:29:00 2024-08-23 09:15:00       1066.0
2024-08-23 15:29:00 2024-08-26 09:15:00       3946.0
2024-08-26 15:29:00 2024-08-27 09:15:00       1066.0
2024-08-27 15:29:00 2024-08-28 09:15:00       1066.0
2024-08-28 15:29:00 2024-08-29 09:15:00       1066.0
2024-08-29 15:29:00 2024-08-30 09:15:00       1066.0
2024-08-30 15:29:00 2024-09-02 09:15:00       3946.0
2024-09-02 15:29:00 2024-09-03 09:15:00       1066.0
2024-09-03 15:29:00 2024-09-04 09:15:00       1066.0
2024-09-04 15:29:00 2024-09-05 09:15:00       1066.0
2024-09-05 15:29:00 2024-09-06 09:15:00       1066.0
2024-09-06 15:29:00 2024-09-09 09:15:00       3946.0
2024-09-09 15:29:00 2024-09-10 09:15:00       1066.0
2024-09-10 15:29:00 2024-09-11 09:15:00       1066.0
2024-09-11 15:29:00 2024-09-12 09:15:00       1066.0
2024-09-12 15:29:00 2024-09-13 09:15:00       1066.0
2024-09-13 15:29:00 2024-09-16 09:15:00       3946.0
2024-09-16 15:29:00 2024-09-17 09:15:00       1066.0
2024-09-17 15:29:00 2024-09-18 09:15:00       1066.0
2024-09-18 15:29:00 2024-09-19 09:15:00       1066.0
2024-09-19 15:29:00 2024-09-20 09:15:00       1066.0
2024-09-20 15:29:00 2024-09-23 09:15:00       3946.0
2024-09-23 15:29:00 2024-09-24 09:15:00       1066.0
2024-09-24 15:29:00 2024-09-25 09:15:00       1066.0
2024-09-25 15:29:00 2024-09-26 09:15:00       1066.0
2024-09-26 15:29:00 2024-09-27 09:15:00       1066.0
2024-09-27 15:29:00 2024-09-30 09:15:00       3946.0
2024-09-30 15:29:00 2024-10-01 09:15:00       1066.0
2024-10-01 15:29:00 2024-10-03 09:15:00       2506.0
2024-10-03 15:29:00 2024-10-04 09:15:00       1066.0
2024-10-04 15:29:00 2024-10-07 09:15:00       3946.0
2024-10-07 15:29:00 2024-10-08 09:15:00       1066.0
2024-10-08 15:29:00 2024-10-09 09:15:00       1066.0
2024-10-09 15:29:00 2024-10-10 09:15:00       1066.0
2024-10-10 15:29:00 2024-10-11 09:15:00       1066.0
2024-10-11 15:29:00 2024-10-14 09:15:00       3946.0
2024-10-14 15:29:00 2024-10-15 09:15:00       1066.0
2024-10-15 15:29:00 2024-10-16 09:15:00       1066.0
2024-10-16 15:29:00 2024-10-17 09:15:00       1066.0
2024-10-17 15:29:00 2024-10-18 09:15:00       1066.0
2024-10-18 15:29:00 2024-10-21 09:15:00       3946.0
2024-10-21 15:29:00 2024-10-22 09:15:00       1066.0
2024-10-22 15:29:00 2024-10-23 09:15:00       1066.0
2024-10-23 15:29:00 2024-10-24 09:15:00       1066.0
2024-10-24 15:29:00 2024-10-25 09:15:00       1066.0
2024-10-25 15:29:00 2024-10-28 09:15:00       3946.0
2024-10-28 15:29:00 2024-10-29 09:15:00       1066.0
2024-10-29 15:29:00 2024-10-30 09:15:00       1066.0
2024-10-30 15:29:00 2024-10-31 09:15:00       1066.0
2024-10-31 15:29:00 2024-11-01 18:00:00       1591.0
2024-11-01 18:59:00 2024-11-04 09:15:00       3736.0
2024-11-04 15:29:00 2024-11-05 09:15:00       1066.0
2024-11-05 15:29:00 2024-11-06 09:15:00       1066.0
2024-11-06 15:29:00 2024-11-07 09:15:00       1066.0
2024-11-07 15:29:00 2024-11-08 09:15:00       1066.0
2024-11-08 15:29:00 2024-11-11 09:15:00       3946.0
2024-11-11 15:29:00 2024-11-12 09:15:00       1066.0
2024-11-12 15:29:00 2024-11-13 09:15:00       1066.0
2024-11-13 15:29:00 2024-11-14 09:15:00       1066.0
2024-11-14 15:29:00 2024-11-18 09:15:00       5386.0
2024-11-18 15:29:00 2024-11-19 09:15:00       1066.0
2024-11-19 15:29:00 2024-11-21 09:15:00       2506.0
2024-11-21 15:29:00 2024-11-22 09:15:00       1066.0
2024-11-22 15:29:00 2024-11-25 09:15:00       3946.0
2024-11-25 15:29:00 2024-11-26 09:15:00       1066.0
2024-11-26 15:29:00 2024-11-27 09:15:00       1066.0
2024-11-27 15:29:00 2024-11-28 09:15:00       1066.0
2024-11-28 15:29:00 2024-11-29 09:15:00       1066.0
2024-11-29 15:29:00 2024-12-02 09:15:00       3946.0
2024-12-02 15:29:00 2024-12-03 09:15:00       1066.0
2024-12-03 15:29:00 2024-12-04 09:15:00       1066.0
2024-12-04 15:29:00 2024-12-05 09:15:00       1066.0
2024-12-05 15:29:00 2024-12-06 09:15:00       1066.0
2024-12-06 15:29:00 2024-12-09 09:15:00       3946.0
2024-12-09 15:29:00 2024-12-10 09:15:00       1066.0
2024-12-10 15:29:00 2024-12-11 09:15:00       1066.0
2024-12-11 15:29:00 2024-12-12 09:15:00       1066.0
2024-12-12 15:29:00 2024-12-13 09:15:00       1066.0
2024-12-13 15:29:00 2024-12-16 09:15:00       3946.0
2024-12-16 15:29:00 2024-12-17 09:15:00       1066.0
2024-12-17 15:29:00 2024-12-18 09:15:00       1066.0
2024-12-18 15:29:00 2024-12-19 09:15:00       1066.0
2024-12-19 15:29:00 2024-12-20 09:15:00       1066.0
2024-12-20 15:29:00 2024-12-23 09:15:00       3946.0
2024-12-23 15:29:00 2024-12-24 09:15:00       1066.0
2024-12-24 15:29:00 2024-12-26 09:15:00       2506.0
2024-12-26 15:29:00 2024-12-27 09:15:00       1066.0
2024-12-27 15:29:00 2024-12-30 09:15:00       3946.0
2024-12-30 15:29:00 2024-12-31 09:15:00       1066.0
2024-12-31 15:29:00 2025-01-01 09:15:00       1066.0
2025-01-01 15:29:00 2025-01-02 09:15:00       1066.0
2025-01-02 15:29:00 2025-01-03 09:15:00       1066.0
2025-01-03 15:29:00 2025-01-06 09:15:00       3946.0
2025-01-06 15:29:00 2025-01-07 09:15:00       1066.0
2025-01-07 15:29:00 2025-01-08 09:15:00       1066.0
2025-01-08 15:29:00 2025-01-09 09:15:00       1066.0
2025-01-09 15:29:00 2025-01-10 09:15:00       1066.0
2025-01-10 15:29:00 2025-01-13 09:15:00       3946.0
2025-01-13 15:29:00 2025-01-14 09:15:00       1066.0
2025-01-14 15:29:00 2025-01-15 09:15:00       1066.0
2025-01-15 15:29:00 2025-01-16 09:15:00       1066.0
2025-01-16 15:29:00 2025-01-17 09:15:00       1066.0
2025-01-17 15:29:00 2025-01-20 09:15:00       3946.0
2025-01-20 15:29:00 2025-01-21 09:15:00       1066.0
2025-01-21 15:29:00 2025-01-22 09:15:00       1066.0
2025-01-22 15:29:00 2025-01-23 09:15:00       1066.0
2025-01-23 15:29:00 2025-01-24 09:15:00       1066.0
2025-01-24 15:29:00 2025-01-27 09:15:00       3946.0
2025-01-27 15:29:00 2025-01-28 09:15:00       1066.0
2025-01-28 15:29:00 2025-01-29 09:15:00       1066.0
2025-01-29 15:29:00 2025-01-30 09:15:00       1066.0
2025-01-30 15:29:00 2025-01-31 09:15:00       1066.0
2025-01-31 15:29:00 2025-02-01 09:15:00       1066.0
2025-02-01 15:29:00 2025-02-03 09:15:00       2506.0
2025-02-03 15:29:00 2025-02-04 09:15:00       1066.0
2025-02-04 15:29:00 2025-02-05 09:15:00       1066.0
2025-02-05 15:29:00 2025-02-06 09:15:00       1066.0
2025-02-06 15:29:00 2025-02-07 09:15:00       1066.0
2025-02-07 15:29:00 2025-02-10 09:15:00       3946.0
2025-02-10 15:29:00 2025-02-11 09:15:00       1066.0
2025-02-11 15:29:00 2025-02-12 09:15:00       1066.0
2025-02-12 15:29:00 2025-02-13 09:15:00       1066.0

In [61]:
for ticker, df in stocks.items():

    df = df.sort_values("date").copy()
    diff = df["date"].diff()

    gaps = df.loc[
        diff > pd.Timedelta(minutes=1),
        ["date"]
    ].copy()

    gaps["previous_bar"] = df["date"].shift(1).loc[gaps.index]

    gaps["gap_minutes"] = (
        gaps["date"] - gaps["previous_bar"]
    ).dt.total_seconds() / 60

    print("\n", ticker)
    print("Number of gaps:", len(gaps))
    print("Gap sizes:", gaps["gap_minutes"].tolist())

 RELIANCE
Number of gaps: 747
Gap sizes: [1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3046.0, 841.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 91.0, 2686.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 3.0, 4.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 91.0, 4126.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1591.0, 3736.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 2506.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 5386.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1336.0, 2551.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 2506.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 2506.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0]

 HDFCBANK
Number of gaps: 747
Gap sizes: [1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3046.0, 841.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 91.0, 2686.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 3.0, 4.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 91.0, 4126.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1591.0, 3736.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 2506.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 5386.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1336.0, 2551.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 2506.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 2506.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0]

 NYKAA
Number of gaps: 747
Gap sizes: [1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3046.0, 841.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 91.0, 2686.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 7.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 91.0, 4126.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 2.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1591.0, 3736.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 2506.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 5386.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1336.0, 2551.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 2506.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 2506.0, 1066.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 2506.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 2506.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 2506.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 5386.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0, 1066.0, 1066.0, 3946.0, 1066.0, 1066.0]

 RVNL
Number of gaps: 746

In [62]:
for ticker, df in stocks.items():

    df = df.sort_values("date").copy()
    diff = df["date"].diff()

    gaps = df.loc[
        diff > pd.Timedelta(minutes=1),
        ["date"]
    ].copy()

    gaps["previous_bar"] = df["date"].shift(1).loc[gaps.index]

    gaps["gap_minutes"] = (
        gaps["date"] - gaps["previous_bar"]
    ).dt.total_seconds() / 60

    print(f"\n{ticker}")
    
    for _, row in gaps.iterrows():
        print(
            row["previous_bar"],
            "→",
            row["date"],
            "|",
            row["gap_minutes"],
            "minutes"
        )

RELIANCE
2023-08-21 15:29:00 → 2023-08-22 09:15:00 | 1066.0 minutes
2023-08-22 15:29:00 → 2023-08-23 09:15:00 | 1066.0 minutes
2023-08-23 15:29:00 → 2023-08-24 09:15:00 | 1066.0 minutes
2023-08-24 15:29:00 → 2023-08-25 09:15:00 | 1066.0 minutes
2023-08-25 15:29:00 → 2023-08-28 09:15:00 | 3946.0 minutes
2023-08-28 15:29:00 → 2023-08-29 09:15:00 | 1066.0 minutes
2023-08-29 15:29:00 → 2023-08-30 09:15:00 | 1066.0 minutes
2023-08-30 15:29:00 → 2023-08-31 09:15:00 | 1066.0 minutes
2023-08-31 15:29:00 → 2023-09-01 09:15:00 | 1066.0 minutes
2023-09-01 15:29:00 → 2023-09-04 09:15:00 | 3946.0 minutes
2023-09-04 15:29:00 → 2023-09-05 09:15:00 | 1066.0 minutes
2023-09-05 15:29:00 → 2023-09-06 09:15:00 | 1066.0 minutes
2023-09-06 15:29:00 → 2023-09-07 09:15:00 | 1066.0 minutes
2023-09-07 15:29:00 → 2023-09-08 09:15:00 | 1066.0 minutes
2023-09-08 15:29:00 → 2023-09-11 09:15:00 | 3946.0 minutes
2023-09-11 15:29:00 → 2023-09-12 09:15:00 | 1066.0 minutes
2023-09-12 15:29:00 → 2023-09-13 09:15:00 | 1066.0 minutes
2023-09-13 15:29:00 → 2023-09-14 09:15:00 | 1066.0 minutes
2023-09-14 15:29:00 → 2023-09-15 09:15:00 | 1066.0 minutes
2023-09-15 15:29:00 → 2023-09-18 09:15:00 | 3946.0 minutes
2023-09-18 15:29:00 → 2023-09-20 09:15:00 | 2506.0 minutes
2023-09-20 15:29:00 → 2023-09-21 09:15:00 | 1066.0 minutes
2023-09-21 15:29:00 → 2023-09-22 09:15:00 | 1066.0 minutes
2023-09-22 15:29:00 → 2023-09-25 09:15:00 | 3946.0 minutes
2023-09-25 15:29:00 → 2023-09-26 09:15:00 | 1066.0 minutes
2023-09-26 15:29:00 → 2023-09-27 09:15:00 | 1066.0 minutes
2023-09-27 15:29:00 → 2023-09-28 09:15:00 | 1066.0 minutes
2023-09-28 15:29:00 → 2023-09-29 09:15:00 | 1066.0 minutes
2023-09-29 15:29:00 → 2023-10-03 09:15:00 | 5386.0 minutes
2023-10-03 15:29:00 → 2023-10-04 09:15:00 | 1066.0 minutes
2023-10-04 15:29:00 → 2023-10-05 09:15:00 | 1066.0 minutes
2023-10-05 15:29:00 → 2023-10-06 09:15:00 | 1066.0 minutes
2023-10-06 15:29:00 → 2023-10-09 09:15:00 | 3946.0 minutes
2023-10-09 15:29:00 → 2023-10-10 09:15:00 | 1066.0 minutes
2023-10-10 15:29:00 → 2023-10-11 09:15:00 | 1066.0 minutes
2023-10-11 15:29:00 → 2023-10-12 09:15:00 | 1066.0 minutes
2023-10-12 15:29:00 → 2023-10-13 09:15:00 | 1066.0 minutes
2023-10-13 15:29:00 → 2023-10-16 09:15:00 | 3946.0 minutes
2023-10-16 15:29:00 → 2023-10-17 09:15:00 | 1066.0 minutes
2023-10-17 15:29:00 → 2023-10-18 09:15:00 | 1066.0 minutes
2023-10-18 15:29:00 → 2023-10-19 09:15:00 | 1066.0 minutes
2023-10-19 15:29:00 → 2023-10-20 09:15:00 | 1066.0 minutes
2023-10-20 15:29:00 → 2023-10-23 09:15:00 | 3946.0 minutes
2023-10-23 15:29:00 → 2023-10-25 09:15:00 | 2506.0 minutes
2023-10-25 15:29:00 → 2023-10-26 09:15:00 | 1066.0 minutes
2023-10-26 15:29:00 → 2023-10-27 09:15:00 | 1066.0 minutes
2023-10-27 15:29:00 → 2023-10-30 09:15:00 | 3946.0 minutes
2023-10-30 15:29:00 → 2023-10-31 09:15:00 | 1066.0 minutes
2023-10-31 15:29:00 → 2023-11-01 09:15:00 | 1066.0 minutes
2023-11-01 15:29:00 → 2023-11-02 09:15:00 | 1066.0 minutes
2023-11-02 15:29:00 → 2023-11-03 09:15:00 | 1066.0 minutes
2023-11-03 15:29:00 → 2023-11-06 09:15:00 | 3946.0 minutes
2023-11-06 15:29:00 → 2023-11-07 09:15:00 | 1066.0 minutes
2023-11-07 15:29:00 → 2023-11-08 09:15:00 | 1066.0 minutes
2023-11-08 15:29:00 → 2023-11-09 09:15:00 | 1066.0 minutes
2023-11-09 15:29:00 → 2023-11-10 09:15:00 | 1066.0 minutes
2023-11-10 15:29:00 → 2023-11-12 18:15:00 | 3046.0 minutes
2023-11-12 19:14:00 → 2023-11-13 09:15:00 | 841.0 minutes
2023-11-13 15:29:00 → 2023-11-15 09:15:00 | 2506.0 minutes
2023-11-15 15:29:00 → 2023-11-16 09:15:00 | 1066.0 minutes
2023-11-16 15:29:00 → 2023-11-17 09:15:00 | 1066.0 minutes
2023-11-17 15:29:00 → 2023-11-20 09:15:00 | 3946.0 minutes
2023-11-20 15:29:00 → 2023-11-21 09:15:00 | 1066.0 minutes
2023-11-21 15:29:00 → 2023-11-22 09:15:00 | 1066.0 minutes
2023-11-22 15:29:00 → 2023-11-23 09:15:00 | 1066.0 minutes
2023-11-23 15:29:00 → 2023-11-24 09:15:00 | 1066.0 minutes
2023-11-24 15:29:00 → 2023-11-28 09:15:00 | 5386.0 minutes
2023-11-28 15:29:00 → 2023-11-29 09:15:00 | 1066.0 minutes
2023-11-29 15:29:00 → 2023-11-30 09:15:00 | 1066.0 minutes
2023-11-30 15:29:00 → 2023-12-01 09:15:00 | 1066.0 minutes
2023-12-01 15:29:00 → 2023-12-04 09:15:00 | 3946.0 minutes
2023-12-04 15:29:00 → 2023-12-05 09:15:00 | 1066.0 minutes
2023-12-05 15:29:00 → 2023-12-06 09:15:00 | 1066.0 minutes
2023-12-06 15:29:00 → 2023-12-07 09:15:00 | 1066.0 minutes
2023-12-07 15:29:00 → 2023-12-08 09:15:00 | 1066.0 minutes
2023-12-08 15:29:00 → 2023-12-11 09:15:00 | 3946.0 minutes
2023-12-11 15:29:00 → 2023-12-12 09:15:00 | 1066.0 minutes
2023-12-12 15:29:00 → 2023-12-13 09:15:00 | 1066.0 minutes
2023-12-13 15:29:00 → 2023-12-14 09:15:00 | 1066.0 minutes
2023-12-14 15:29:00 → 2023-12-15 09:15:00 | 1066.0 minutes
2023-12-15 15:29:00 → 2023-12-18 09:15:00 | 3946.0 minutes
2023-12-18 15:29:00 → 2023-12-19 09:15:00 | 1066.0 minutes
2023-12-19 15:29:00 → 2023-12-20 09:15:00 | 1066.0 minutes
2023-12-20 15:29:00 → 2023-12-21 09:15:00 | 1066.0 minutes
2023-12-21 15:29:00 → 2023-12-22 09:15:00 | 1066.0 minutes
2023-12-22 15:29:00 → 2023-12-26 09:15:00 | 5386.0 minutes
2023-12-26 15:29:00 → 2023-12-27 09:15:00 | 1066.0 minutes
2023-12-27 15:29:00 → 2023-12-28 09:15:00 | 1066.0 minutes
2023-12-28 15:29:00 → 2023-12-29 09:15:00 | 1066.0 minutes
2023-12-29 15:29:00 → 2024-01-01 09:15:00 | 3946.0 minutes
2024-01-01 15:29:00 → 2024-01-02 09:15:00 | 1066.0 minutes
2024-01-02 15:29:00 → 2024-01-03 09:15:00 | 1066.0 minutes
2024-01-03 15:29:00 → 2024-01-04 09:15:00 | 1066.0 minutes
2024-01-04 15:29:00 → 2024-01-05 09:15:00 | 1066.0 minutes
2024-01-05 15:29:00 → 2024-01-08 09:15:00 | 3946.0 minutes
2024-01-08 15:29:00 → 2024-01-09 09:15:00 | 1066.0 minutes
2024-01-09 15:29:00 → 2024-01-10 09:15:00 | 1066.0 minutes
2024-01-10 15:29:00 → 2024-01-11 09:15:00 | 1066.0 minutes
2024-01-11 15:29:00 → 2024-01-12 09:15:00 | 1066.0 minutes
2024-01-12 15:29:00 → 2024-01-15 09:15:00 | 3946.0 minutes
2024-01-15 15:29:00 → 2024-01-16 09:15:00 | 1066.0 minutes
2024-01-16 15:29:00 → 2024-01-17 09:15:00 | 1066.0 minutes
2024-01-17 15:29:00 → 2024-01-18 09:15:00 | 1066.0 minutes
2024-01-18 15:29:00 → 2024-01-19 09:15:00 | 1066.0 minutes
2024-01-19 15:29:00 → 2024-01-20 09:15:00 | 1066.0 minutes
2024-01-20 15:29:00 → 2024-01-23 09:15:00 | 3946.0 minutes
2024-01-23 15:29:00 → 2024-01-24 09:15:00 | 1066.0 minutes
2024-01-24 15:29:00 → 2024-01-25 09:15:00 | 1066.0 minutes
2024-01-25 15:29:00 → 2024-01-29 09:15:00 | 5386.0 minutes
2024-01-29 15:29:00 → 2024-01-30 09:15:00 | 1066.0 minutes
2024-01-30 15:29:00 → 2024-01-31 09:15:00 | 1066.0 minutes
2024-01-31 15:29:00 → 2024-02-01 09:15:00 | 1066.0 minutes
2024-02-01 15:29:00 → 2024-02-02 09:15:00 | 1066.0 minutes
2024-02-02 15:29:00 → 2024-02-05 09:15:00 | 3946.0 minutes
2024-02-05 15:29:00 → 2024-02-06 09:15:00 | 1066.0 minutes
2024-02-06 15:29:00 → 2024-02-07 09:15:00 | 1066.0 minutes
2024-02-07 15:29:00 → 2024-02-08 09:15:00 | 1066.0 minutes
2024-02-08 15:29:00 → 2024-02-09 09:15:00 | 1066.0 minutes
2024-02-09 15:29:00 → 2024-02-12 09:15:00 | 3946.0 minutes
2024-02-12 15:29:00 → 2024-02-13 09:15:00 | 1066.0 minutes
2024-02-13 15:29:00 → 2024-02-14 09:15:00 | 1066.0 minutes
2024-02-14 15:29:00 → 2024-02-15 09:15:00 | 1066.0 minutes
2024-02-15 15:29:00 → 2024-02-16 09:15:00 | 1066.0 minutes
2024-02-16 15:29:00 → 2024-02-19 09:15:00 | 3946.0 minutes
2024-02-19 15:29:00 → 2024-02-20 09:15:00 | 1066.0 minutes
2024-02-20 15:29:00 → 2024-02-21 09:15:00 | 1066.0 minutes
2024-02-21 15:29:00 → 2024-02-22 09:15:00 | 1066.0 minutes
2024-02-22 15:29:00 → 2024-02-23 09:15:00 | 1066.0 minutes
2024-02-23 15:29:00 → 2024-02-26 09:15:00 | 3946.0 minutes
2024-02-26 15:29:00 → 2024-02-27 09:15:00 | 1066.0 minutes
2024-02-27 15:29:00 → 2024-02-28 09:15:00 | 1066.0 minutes
2024-02-28 15:29:00 → 2024-02-29 09:15:00 | 1066.0 minutes
2024-02-29 15:29:00 → 2024-03-01 09:15:00 | 1066.0 minutes
2024-03-01 15:29:00 → 2024-03-02 09:15:00 | 1066.0 minutes
2024-03-02 09:59:00 → 2024-03-02 11:30:00 | 91.0 minutes
2024-03-02 12:29:00 → 2024-03-04 09:15:00 | 2686.0 minutes
2024-03-04 15:29:00 → 2024-03-05 09:15:00 | 1066.0 minutes
2024-03-05 15:29:00 → 2024-03-06 09:15:00 | 1066.0 minutes
2024-03-06 15:29:00 → 2024-03-07 09:15:00 | 1066.0 minutes
2024-03-07 15:29:00 → 2024-03-11 09:15:00 | 5386.0 minutes
2024-03-11 15:29:00 → 2024-03-12 09:15:00 | 1066.0 minutes
2024-03-12 15:29:00 → 2024-03-13 09:15:00 | 1066.0 minutes
2024-03-13 15:29:00 → 2024-03-14 09:15:00 | 1066.0 minutes
2024-03-14 15:29:00 → 2024-03-15 09:15:00 | 1066.0 minutes
2024-03-15 15:29:00 → 2024-03-18 09:15:00 | 3946.0 minutes
2024-03-18 15:29:00 → 2024-03-19 09:15:00 | 1066.0 minutes
2024-03-19 15:29:00 → 2024-03-20 09:15:00 | 1066.0 minutes
2024-03-20 15:29:00 → 2024-03-21 09:15:00 | 1066.0 minutes
2024-03-21 15:29:00 → 2024-03-22 09:15:00 | 1066.0 minutes
2024-03-22 15:29:00 → 2024-03-26 09:15:00 | 5386.0 minutes
2024-03-26 15:29:00 → 2024-03-27 09:15:00 | 1066.0 minutes
2024-03-27 15:29:00 → 2024-03-28 09:15:00 | 1066.0 minutes
2024-03-28 15:29:00 → 2024-04-01 09:15:00 | 5386.0 minutes
2024-04-01 15:29:00 → 2024-04-02 09:15:00 | 1066.0 minutes
2024-04-02 15:29:00 → 2024-04-03 09:15:00 | 1066.0 minutes
2024-04-03 15:29:00 → 2024-04-04 09:15:00 | 1066.0 minutes
2024-04-04 15:29:00 → 2024-04-05 09:15:00 | 1066.0 minutes
2024-04-05 15:29:00 → 2024-04-08 09:15:00 | 3946.0 minutes
2024-04-08 15:29:00 → 2024-04-09 09:15:00 | 1066.0 minutes
2024-04-09 15:29:00 → 2024-04-10 09:15:00 | 1066.0 minutes
2024-04-10 15:29:00 → 2024-04-12 09:15:00 | 2506.0 minutes
2024-04-12 15:29:00 → 2024-04-15 09:15:00 | 3946.0 minutes
2024-04-15 15:29:00 → 2024-04-16 09:15:00 | 1066.0 minutes
2024-04-16 15:29:00 → 2024-04-18 09:15:00 | 2506.0 minutes
2024-04-18 15:29:00 → 2024-04-19 09:15:00 | 1066.0 minutes
2024-04-19 15:29:00 → 2024-04-22 09:15:00 | 3946.0 minutes
2024-04-22 15:29:00 → 2024-04-23 09:15:00 | 1066.0 minutes
2024-04-23 10:51:00 → 2024-04-23 10:54:00 | 3.0 minutes
2024-04-23 10:54:00 → 2024-04-23 10:58:00 | 4.0 minutes
2024-04-23 15:29:00 → 2024-04-24 09:15:00 | 1066.0 minutes
2024-04-24 15:29:00 → 2024-04-25 09:15:00 | 1066.0 minutes
2024-04-25 15:29:00 → 2024-04-26 09:15:00 | 1066.0 minutes
2024-04-26 15:29:00 → 2024-04-29 09:15:00 | 3946.0 minutes
2024-04-29 15:29:00 → 2024-04-30 09:15:00 | 1066.0 minutes
2024-04-30 15:29:00 → 2024-05-02 09:15:00 | 2506.0 minutes
2024-05-02 15:29:00 → 2024-05-03 09:15:00 | 1066.0 minutes
2024-05-03 15:29:00 → 2024-05-06 09:15:00 | 3946.0 minutes
2024-05-06 15:29:00 → 2024-05-07 09:15:00 | 1066.0 minutes
2024-05-07 15:29:00 → 2024-05-08 09:15:00 | 1066.0 minutes
2024-05-08 15:29:00 → 2024-05-09 09:15:00 | 1066.0 minutes
2024-05-09 15:29:00 → 2024-05-10 09:15:00 | 1066.0 minutes
2024-05-10 15:29:00 → 2024-05-13 09:15:00 | 3946.0 minutes
2024-05-13 15:29:00 → 2024-05-14 09:15:00 | 1066.0 minutes
2024-05-14 15:29:00 → 2024-05-15 09:15:00 | 1066.0 minutes
2024-05-15 15:29:00 → 2024-05-16 09:15:00 | 1066.0 minutes
2024-05-16 15:29:00 → 2024-05-17 09:15:00 | 1066.0 minutes
2024-05-17 15:29:00 → 2024-05-18 09:15:00 | 1066.0 minutes
2024-05-18 09:59:00 → 2024-05-18 11:30:00 | 91.0 minutes
2024-05-18 12:29:00 → 2024-05-21 09:15:00 | 4126.0 minutes
2024-05-21 15:29:00 → 2024-05-22 09:15:00 | 1066.0 minutes
2024-05-22 15:29:00 → 2024-05-23 09:15:00 | 1066.0 minutes
2024-05-23 15:29:00 → 2024-05-24 09:15:00 | 1066.0 minutes
2024-05-24 15:29:00 → 2024-05-27 09:15:00 | 3946.0 minutes
2024-05-27 15:29:00 → 2024-05-28 09:15:00 | 1066.0 minutes
2024-05-28 15:29:00 → 2024-05-29 09:15:00 | 1066.0 minutes
2024-05-29 15:29:00 → 2024-05-30 09:15:00 | 1066.0 minutes
2024-05-30 15:29:00 → 2024-05-31 09:15:00 | 1066.0 minutes
2024-05-31 15:29:00 → 2024-06-03 09:15:00 | 3946.0 minutes
2024-06-03 15:29:00 → 2024-06-04 09:15:00 | 1066.0 minutes
2024-06-04 15:29:00 → 2024-06-05 09:15:00 | 1066.0 minutes
2024-06-05 15:29:00 → 2024-06-06 09:15:00 | 1066.0 minutes
2024-06-06 15:29:00 → 2024-06-07 09:15:00 | 1066.0 minutes
2024-06-07 15:29:00 → 2024-06-10 09:15:00 | 3946.0 minutes
2024-06-10 15:29:00 → 2024-06-11 09:15:00 | 1066.0 minutes
2024-06-11 15:29:00 → 2024-06-12 09:15:00 | 1066.0 minutes
2024-06-12 15:29:00 → 2024-06-13 09:15:00 | 1066.0 minutes
2024-06-13 15:29:00 → 2024-06-14 09:15:00 | 1066.0 minutes
2024-06-14 15:29:00 → 2024-06-18 09:15:00 | 5386.0 minutes
2024-06-18 15:29:00 → 2024-06-19 09:15:00 | 1066.0 minutes
2024-06-19 15:29:00 → 2024-06-20 09:15:00 | 1066.0 minutes
2024-06-20 15:29:00 → 2024-06-21 09:15:00 | 1066.0 minutes
2024-06-21 15:29:00 → 2024-06-24 09:15:00 | 3946.0 minutes
2024-06-24 15:29:00 → 2024-06-25 09:15:00 | 1066.0 minutes
2024-06-25 15:29:00 → 2024-06-26 09:15:00 | 1066.0 minutes
2024-06-26 15:29:00 → 2024-06-27 09:15:00 | 1066.0 minutes
2024-06-27 15:29:00 → 2024-06-28 09:15:00 | 1066.0 minutes
2024-06-28 15:29:00 → 2024-07-01 09:15:00 | 3946.0 minutes
2024-07-01 15:29:00 → 2024-07-02 09:15:00 | 1066.0 minutes
2024-07-02 15:29:00 → 2024-07-03 09:15:00 | 1066.0 minutes
2024-07-03 15:29:00 → 2024-07-04 09:15:00 | 1066.0 minutes
2024-07-04 15:29:00 → 2024-07-05 09:15:00 | 1066.0 minutes
2024-07-05 15:29:00 → 2024-07-08 09:15:00 | 3946.0 minutes
2024-07-08 15:29:00 → 2024-07-09 09:15:00 | 1066.0 minutes
2024-07-09 15:29:00 → 2024-07-10 09:15:00 | 1066.0 minutes
2024-07-10 15:29:00 → 2024-07-11 09:15:00 | 1066.0 minutes
2024-07-11 15:29:00 → 2024-07-12 09:15:00 | 1066.0 minutes
2024-07-12 15:29:00 → 2024-07-15 09:15:00 | 3946.0 minutes
2024-07-15 15:29:00 → 2024-07-16 09:15:00 | 1066.0 minutes
2024-07-16 15:29:00 → 2024-07-18 09:15:00 | 2506.0 minutes
2024-07-18 15:29:00 → 2024-07-19 09:15:00 | 1066.0 minutes
2024-07-19 15:29:00 → 2024-07-22 09:15:00 | 3946.0 minutes
2024-07-22 15:29:00 → 2024-07-23 09:15:00 | 1066.0 minutes
2024-07-23 15:29:00 → 2024-07-24 09:15:00 | 1066.0 minutes
2024-07-24 15:29:00 → 2024-07-25 09:15:00 | 1066.0 minutes
2024-07-25 15:29:00 → 2024-07-26 09:15:00 | 1066.0 minutes
2024-07-26 15:29:00 → 2024-07-29 09:15:00 | 3946.0 minutes
2024-07-29 15:29:00 → 2024-07-30 09:15:00 | 1066.0 minutes
2024-07-30 15:29:00 → 2024-07-31 09:15:00 | 1066.0 minutes
2024-07-31 15:29:00 → 2024-08-01 09:15:00 | 1066.0 minutes
2024-08-01 15:29:00 → 2024-08-02 09:15:00 | 1066.0 minutes
2024-08-02 15:29:00 → 2024-08-05 09:15:00 | 3946.0 minutes
2024-08-05 15:29:00 → 2024-08-06 09:15:00 | 1066.0 minutes
2024-08-06 15:29:00 → 2024-08-07 09:15:00 | 1066.0 minutes
2024-08-07 15:29:00 → 2024-08-08 09:15:00 | 1066.0 minutes
2024-08-08 15:29:00 → 2024-08-09 09:15:00 | 1066.0 minutes
2024-08-09 15:29:00 → 2024-08-12 09:15:00 | 3946.0 minutes
2024-08-12 15:29:00 → 2024-08-13 09:15:00 | 1066.0 minutes
2024-08-13 15:29:00 → 2024-08-14 09:15:00 | 1066.0 minutes
2024-08-14 15:29:00 → 2024-08-16 09:15:00 | 2506.0 minutes
2024-08-16 15:29:00 → 2024-08-19 09:15:00 | 3946.0 minutes
2024-08-19 15:29:00 → 2024-08-20 09:15:00 | 1066.0 minutes
2024-08-20 15:29:00 → 2024-08-21 09:15:00 | 1066.0 minutes
2024-08-21 15:29:00 → 2024-08-22 09:15:00 | 1066.0 minutes
2024-08-22 15:29:00 → 2024-08-23 09:15:00 | 1066.0 minutes
2024-08-23 15:29:00 → 2024-08-26 09:15:00 | 3946.0 minutes
2024-08-26 15:29:00 → 2024-08-27 09:15:00 | 1066.0 minutes
2024-08-27 15:29:00 → 2024-08-28 09:15:00 | 1066.0 minutes
2024-08-28 15:29:00 → 2024-08-29 09:15:00 | 1066.0 minutes
2024-08-29 15:29:00 → 2024-08-30 09:15:00 | 1066.0 minutes
2024-08-30 15:29:00 → 2024-09-02 09:15:00 | 3946.0 minutes
2024-09-02 15:29:00 → 2024-09-03 09:15:00 | 1066.0 minutes
2024-09-03 15:29:00 → 2024-09-04 09:15:00 | 1066.0 minutes
2024-09-04 15:29:00 → 2024-09-05 09:15:00 | 1066.0 minutes
2024-09-05 15:29:00 → 2024-09-06 09:15:00 | 1066.0 minutes
2024-09-06 15:29:00 → 2024-09-09 09:15:00 | 3946.0 minutes
2024-09-09 15:29:00 → 2024-09-10 09:15:00 | 1066.0 minutes
2024-09-10 15:29:00 → 2024-09-11 09:15:00 | 1066.0 minutes
2024-09-11 15:29:00 → 2024-09-12 09:15:00 | 1066.0 minutes
2024-09-12 15:29:00 → 2024-09-13 09:15:00 | 1066.0 minutes
2024-09-13 15:29:00 → 2024-09-16 09:15:00 | 3946.0 minutes
2024-09-16 15:29:00 → 2024-09-17 09:15:00 | 1066.0 minutes
2024-09-17 15:29:00 → 2024-09-18 09:15:00 | 1066.0 minutes
2024-09-18 15:29:00 → 2024-09-19 09:15:00 | 1066.0 minutes
2024-09-19 15:29:00 → 2024-09-20 09:15:00 | 1066.0 minutes
2024-09-20 15:29:00 → 2024-09-23 09:15:00 | 3946.0 minutes
2024-09-23 15:29:00 → 2024-09-24 09:15:00 | 1066.0 minutes
2024-09-24 15:29:00 → 2024-09-25 09:15:00 | 1066.0 minutes
2024-09-25 15:29:00 → 2024-09-26 09:15:00 | 1066.0 minutes
2024-09-26 15:29:00 → 2024-09-27 09:15:00 | 1066.0 minutes
2024-09-27 15:29:00 → 2024-09-30 09:15:00 | 3946.0 minutes
2024-09-30 15:29:00 → 2024-10-01 09:15:00 | 1066.0 minutes
2024-10-01 15:29:00 → 2024-10-03 09:15:00 | 2506.0 minutes
2024-10-03 15:29:00 → 2024-10-04 09:15:00 | 1066.0 minutes
2024-10-04 15:29:00 → 2024-10-07 09:15:00 | 3946.0 minutes
2024-10-07 15:29:00 → 2024-10-08 09:15:00 | 1066.0 minutes
2024-10-08 15:29:00 → 2024-10-09 09:15:00 | 1066.0 minutes
2024-10-09 15:29:00 → 2024-10-10 09:15:00 | 1066.0 minutes
2024-10-10 15:29:00 → 2024-10-11 09:15:00 | 1066.0 minutes
2024-10-11 15:29:00 → 2024-10-14 09:15:00 | 3946.0 minutes
2024-10-14 15:29:00 → 2024-10-15 09:15:00 | 1066.0 minutes
2024-10-15 15:29:00 → 2024-10-16 09:15:00 | 1066.0 minutes
2024-10-16 15:29:00 → 2024-10-17 09:15:00 | 1066.0 minutes
2024-10-17 15:29:00 → 2024-10-18 09:15:00 | 1066.0 minutes
2024-10-18 15:29:00 → 2024-10-21 09:15:00 | 3946.0 minutes
2024-10-21 15:29:00 → 2024-10-22 09:15:00 | 1066.0 minutes
2024-10-22 15:29:00 → 2024-10-23 09:15:00 | 1066.0 minutes
2024-10-23 15:29:00 → 2024-10-24 09:15:00 | 1066.0 minutes
2024-10-24 15:29:00 → 2024-10-25 09:15:00 | 1066.0 minutes
2024-10-25 15:29:00 → 2024-10-28 09:15:00 | 3946.0 minutes
2024-10-28 15:29:00 → 2024-10-29 09:15:00 | 1066.0 minutes
2024-10-29 15:29:00 → 2024-10-30 09:15:00 | 1066.0 minutes
2024-10-30 15:29:00 → 2024-10-31 09:15:00 | 1066.0 minutes
2024-10-31 15:29:00 → 2024-11-01 18:00:00 | 1591.0 minutes
2024-11-01 18:59:00 → 2024-11-04 09:15:00 | 3736.0 minutes
2024-11-04 15:29:00 → 2024-11-05 09:15:00 | 1066.0 minutes
2024-11-05 15:29:00 → 2024-11-06 09:15:00 | 1066.0 minutes
2024-11-06 15:29:00 → 2024-11-07 09:15:00 | 1066.0 minutes
2024-11-07 15:29:00 → 2024-11-08 09:15:00 | 1066.0 minutes
2024-11-08 15:29:00 → 2024-11-11 09:15:00 | 3946.0 minutes
2024-11-11 15:29:00 → 2024-11-12 09:15:00 | 1066.0 minutes
2024-11-12 15:29:00 → 2024-11-13 09:15:00 | 1066.0 minutes
2024-11-13 15:29:00 → 2024-11-14 09:15:00 | 1066.0 minutes
2024-11-14 15:29:00 → 2024-11-18 09:15:00 | 5386.0 minutes
2024-11-18 15:29:00 → 2024-11-19 09:15:00 | 1066.0 minutes
2024-11-19 15:29:00 → 2024-11-21 09:15:00 | 2506.0 minutes
2024-11-21 15:29:00 → 2024-11-22 09:15:00 | 1066.0 minutes
2024-11-22 15:29:00 → 2024-11-25 09:15:00 | 3946.0 minutes
2024-11-25 15:29:00 → 2024-11-26 09:15:00 | 1066.0 minutes
2024-11-26 15:29:00 → 2024-11-27 09:15:00 | 1066.0 minutes
2024-11-27 15:29:00 → 2024-11-28 09:15:00 | 1066.0 minutes
2024-11-28 15:29:00 → 2024-11-29 09:15:00 | 1066.0 minutes
2024-11-29 15:29:00 → 2024-12-02 09:15:00 | 3946.0 minutes
2024-12-02 15:29:00 → 2024-12-03 09:15:00 | 1066.0 minutes
2024-12-03 15:29:00 → 2024-12-04 09:15:00 | 1066.0 minutes
2024-12-04 15:29:00 → 2024-12-05 09:15:00 | 1066.0 minutes
2024-12-05 15:29:00 → 2024-12-06 09:15:00 | 1066.0 minutes
2024-12-06 15:29:00 → 2024-12-09 09:15:00 | 3946.0 minutes
2024-12-09 15:29:00 → 2024-12-10 09:15:00 | 1066.0 minutes
2024-12-10 15:29:00 → 2024-12-11 09:15:00 | 1066.0 minutes
2024-12-11 15:29:00 → 2024-12-12 09:15:00 | 1066.0 minutes
2024-12-12 15:29:00 → 2024-12-13 09:15:00 | 1066.0 minutes
2024-12-13 15:29:00 → 2024-12-16 09:15:00 | 3946.0 minutes
2024-12-16 15:29:00 → 2024-12-17 09:15:00 | 1066.0 minutes
2024-12-17 15:29:00 → 2024-12-18 09:15:00 | 1066.0 minutes
2024-12-18 15:29:00 → 2024-12-19 09:15:00 | 1066.0 minutes
2024-12-19 15:29:00 → 2024-12-20 09:15:00 | 1066.0 minutes
2024-12-20 15:29:00 → 2024-12-23 09:15:00 | 3946.0 minutes
2024-12-23 15:29:00 → 2024-12-24 09:15:00 | 1066.0 minutes
2024-12-24 15:29:00 → 2024-12-26 09:15:00 | 2506.0 minutes

In [63]:
stock_map = {
    500325: "RELIANCE",
    500180: "HDFCBANK",
    543384: "NYKAA",
    542649: "RVNL",
    532343: "HAL"
}

In [64]:
announcements["ticker"] = announcements["SCRIP_CD"].map(stock_map)

print(
    announcements[
        ["SCRIP_CD", "ticker"]
    ].drop_duplicates().sort_values("SCRIP_CD").to_string(index=False)
)

 SCRIP_CD   ticker
   500180 HDFCBANK
   500325 RELIANCE
   541154      NaN
   542649     RVNL
   543384    NYKAA

In [65]:
print(announcements["SCRIP_CD"].unique())

[500180 500325 542649 543384 541154]

In [66]:
stock_map = {
    500325: "RELIANCE",
    500180: "HDFCBANK",
    543384: "NYKAA",
    541154: "HAL",
    542649: "RVNL"
}

announcements["ticker"] = announcements["SCRIP_CD"].map(stock_map)

print(
    announcements[
        ["SCRIP_CD", "ticker"]
    ].drop_duplicates()
    .sort_values("SCRIP_CD")
    .to_string(index=False)
)

print("\nUnmapped announcements:", announcements["ticker"].isna().sum())

 SCRIP_CD   ticker
   500180 HDFCBANK
   500325 RELIANCE
   541154      HAL
   542649     RVNL
   543384    NYKAA

Unmapped announcements: 0

In [67]:
events = announcements[
    [
        "NEWSID",
        "SCRIP_CD",
        "ticker",
        "DissemDT",
        "HEADLINE",
        "CATEGORYNAME",
        "SUBCATNAME"
    ]
].copy()

print("Total events:", len(events))
print(events.head().to_string(index=False))

Total events: 2530
                              NEWSID  SCRIP_CD   ticker                DissemDT                                                                                                                                                                                            HEADLINE   CATEGORYNAME               SUBCATNAME
d4395f8a-6089-4a17-8dec-385a6acb2b67    500180 HDFCBANK 2026-08-19 23:19:39.420                                      Intimation of Credit Rating pursuant to Regulation 30 of SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015 ("SEBI Listing Regulations") Company Update            Credit Rating
391541fa-8d4b-41b6-9304-1e15bed1d5d8    500180 HDFCBANK 2026-08-19 22:52:54.670                                            Intimation under Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 ("SEBI Listing Regulations") Company Update                  General
989d8d2f-2b08-4a1c-8d43-f55bae61c178    500325 RELIANCE 2026-08-18 20:06:38.747 This is further to the disclosure dated August 13, 2026 made by the Company. We wish to inform you that the Company executives participated in the Institutional Investors'' Meeting - Motilal .... Company Update                  General
b0bc3391-c0aa-44d6-be8d-a10b20b10247    500325 RELIANCE 2026-08-18 17:44:19.310                                                                                                                                    Please refer our letter dated August 18, 2026 attached herewith. Company Update                  General
32de7735-b8e6-4653-b377-0c5762be73af    542649     RVNL 2026-08-18 14:24:13.290                                                                                                                                                        Transcript of Conference Call with Investors Company Update Earnings Call Transcript

In [68]:
events = events.sort_values(
    ["ticker", "DissemDT"]
).reset_index(drop=True)

print(events[[
    "ticker",
    "DissemDT",
    "HEADLINE"
]].head(10).to_string(index=False))

ticker                DissemDT                                                                                              HEADLINE
   HAL 2023-08-23 17:38:08.580                                                                              Announcement as attached
   HAL 2023-08-28 17:56:31.123                                                                              Announcement as attached
   HAL 2023-08-31 17:56:43.077                               Proceedings / Outcome of the 60th Annual General Meeting of the Company
   HAL 2023-09-01 16:15:05.740                                               Details of Voting Results and Report of the Scrutinizer
   HAL 2023-09-01 17:01:27.883                                                                                 Announcement attached
   HAL 2023-09-01 17:02:53.890                                                                                 Announcement attached
   HAL 2023-09-01 17:06:56.487 Shareholders has approved sub-division of Equity Shares of the Company in 60th AGM held on 31.08.2023
   HAL 2023-09-01 17:09:24.247                                                                                 Announcement attached
   HAL 2023-09-12 14:31:50.297                                                                                announcement attached.
   HAL 2023-09-15 17:22:38.493                                                                                 Announcement attached

In [69]:
event = events.iloc[0]

print(event.to_string())

NEWSID          d9de7773-d48b-4140-904a-6f736773dc4c
SCRIP_CD                                      541154
ticker                                           HAL
DissemDT                  2023-08-23 17:38:08.580000
HEADLINE                    Announcement as attached
CATEGORYNAME                             Corp Action
SUBCATNAME                          Dividend Updates

In [70]:
ticker = event["ticker"]
event_time = event["DissemDT"]

stock_data = stocks[ticker]

future_bars = stock_data[
    stock_data["date"] >= event_time
].sort_values("date")

print(
    future_bars[
        ["date", "open", "high", "low", "close", "volume"]
    ].head(5).to_string(index=False)
)

               date    open    high     low   close   volume
2023-08-24 09:15:00 2067.50 2067.50 2037.50 2040.60 281870.0
2023-08-24 09:16:00 2041.90 2050.85 2037.85 2050.75 151148.0
2023-08-24 09:17:00 2050.90 2062.40 2050.90 2058.90 159206.0
2023-08-24 09:18:00 2057.95 2059.10 2046.00 2047.70  87888.0
2023-08-24 09:19:00 2048.30 2048.45 2042.10 2046.40  75370.0

In [71]:
clean_stocks = {}

for ticker, df in stocks.items():
    df = df.sort_values("date").copy()

    # Identify invalid OHLC bars
    invalid_ohlc = (
        (df["high"] < df["open"]) |
        (df["high"] < df["close"]) |
        (df["low"] > df["open"]) |
        (df["low"] > df["close"]) |
        (df["high"] < df["low"])
    )

    # Exclude only the invalid OHLC bars
    df = df.loc[~invalid_ohlc].copy()

    clean_stocks[ticker] = df.reset_index(drop=True)

    print(
        ticker,
        "| Removed invalid OHLC bars:",
        invalid_ohlc.sum(),
        "| Remaining:",
        len(df)
    )

RELIANCE | Removed invalid OHLC bars: 0 | Remaining: 277510
HDFCBANK | Removed invalid OHLC bars: 1 | Remaining: 277509
NYKAA | Removed invalid OHLC bars: 0 | Remaining: 277508
RVNL | Removed invalid OHLC bars: 0 | Remaining: 277509
HAL | Removed invalid OHLC bars: 1 | Remaining: 277509

In [72]:
def find_event_bar(event_time, stock_df):
    """
    Find the first valid one-minute bar beginning
    at or after the announcement dissemination time.
    """

    future = stock_df[
        stock_df["date"] >= event_time
    ]

    if future.empty:
        return None

    return future.iloc[0]

In [73]:
event = events.iloc[0]

bar = find_event_bar(
    event["DissemDT"],
    clean_stocks[event["ticker"]]
)

print("Announcement:")
print(event["DissemDT"])

print("\nEvent bar:")
print(bar[[
    "date",
    "open",
    "high",
    "low",
    "close",
    "volume"
]].to_string())

Announcement:
2023-08-23 17:38:08.580000

Event bar:
date      2023-08-24 09:15:00
open                   2067.5
high                   2067.5
low                    2037.5
close                  2040.6
volume               281870.0

In [74]:
aligned_events = []

for _, event in events.iterrows():

    ticker = event["ticker"]
    stock_df = clean_stocks[ticker]

    bar = find_event_bar(
        event["DissemDT"],
        stock_df
    )

    if bar is None:
        event_bar_time = pd.NaT
        event_close = pd.NA
    else:
        event_bar_time = bar["date"]
        event_close = bar["close"]

    aligned_events.append({
        "NEWSID": event["NEWSID"],
        "SCRIP_CD": event["SCRIP_CD"],
        "ticker": ticker,
        "DissemDT": event["DissemDT"],
        "event_time": event_bar_time,
        "event_close": event_close,
        "HEADLINE": event["HEADLINE"],
        "CATEGORYNAME": event["CATEGORYNAME"],
        "SUBCATNAME": event["SUBCATNAME"]
    })

aligned_events = pd.DataFrame(aligned_events)

print("Total announcements:", len(aligned_events))
print(
    "Events without matching bar:",
    aligned_events["event_time"].isna().sum()
)

Total announcements: 2530
Events without matching bar: 2

In [75]:
aligned_events["alignment_delay_seconds"] = (
    aligned_events["event_time"] -
    aligned_events["DissemDT"]
).dt.total_seconds()

print(
    aligned_events["alignment_delay_seconds"]
    .describe()
)

count      2528.000000
mean      80098.114716
std       79251.400506
min           0.253000
25%       40953.195000
50%       54681.381500
75%       82283.554000
max      321305.960000
Name: alignment_delay_seconds, dtype: float64

In [76]:
print(
    aligned_events[
        [
            "ticker",
            "DissemDT",
            "event_time",
            "alignment_delay_seconds",
            "HEADLINE"
        ]
    ]
    .sort_values(
        "alignment_delay_seconds",
        ascending=False
    )
    .head(10)
    .to_string(index=False)
)

  ticker                DissemDT          event_time  alignment_delay_seconds                                                                                                                                                                                        HEADLINE
RELIANCE 2024-11-14 15:59:54.040 2024-11-18 09:15:00               321305.960                                    We enclose the details of ''Letter(s) of Confirmation'' issued by the Company to its shareholders, in lieu of share certificate(s) reported as lost by them.
HDFCBANK 2026-01-23 16:00:12.523 2026-01-27 09:15:00               321287.477                                  Transcript of Earnings Call in relation to the unaudited standalone and consolidated financial results for the quarter and nine-months ended December 31, 2025
RELIANCE 2026-04-30 16:03:05.177 2026-05-04 09:15:00               321114.823 Please find attached a media release by Reliance Retail Limited, a subsidiary of the Company, titled "Reliance Retail Acquires Priyanka Chopra Jonas''s Anomaly, Accelerating Expansion of ....
     HAL 2025-04-11 16:07:14.450 2025-04-15 09:15:00               320865.550                                                                                                                                                                        announcement as attached
    RVNL 2026-06-25 16:12:34.593 2026-06-29 09:15:00               320545.407                                                                                        Intimation of Trading Window Closure pursuant to SEBI (Prohibition of Insider Trading) Regulations, 2015
    RVNL 2024-03-28 16:22:35.890 2024-04-01 09:15:00               319944.110                                                                                        Rail Vikas Nigam Limited emerges as the Lowest Bidder (L1) from SER HQ-ELECTRICAL/SOUTH EASTERN RAILWAY.
HDFCBANK 2023-09-29 16:31:40.523 2023-10-03 09:15:00               319399.477                                                                                                      Appointment of Chief Compliance Officer (Senior Management Personnel) of HDFC Bank Limited
   NYKAA 2025-08-14 16:42:36.520 2025-08-18 09:15:00               318743.480                                                                                                                  Please find attached transcript of the Conference call for analyst / investor.
RELIANCE 2023-11-24 17:05:58.357 2023-11-28 09:15:00               317341.643       We enclose the information regarding loss of share certificate(s) received from the shareholder(s) of the Company on November 23, 2023 and November 24, 2023 aggregating to 5,864 shares.
    RVNL 2024-03-07 17:11:54.473 2024-03-11 09:15:00               316985.527                                                                                                                 Letter of Award (LoA) received from M. P. Poorv Kshetra Vidyut Vitaran Co. Ltd.

# 5. Event Identification and Alignment

In [77]:
duplicate_events = aligned_events[
    aligned_events.duplicated(
        subset=["ticker", "event_time"],
        keep=False
    )
].sort_values(["ticker", "event_time"])

print("Announcements involved in duplicate event minutes:",
      len(duplicate_events))

print(
    duplicate_events[
        ["ticker", "DissemDT", "event_time", "HEADLINE"]
    ].head(30).to_string(index=False)
)

Announcements involved in duplicate event minutes: 1227
ticker                DissemDT          event_time                                                                                                                                                                                        HEADLINE
   HAL 2023-09-01 16:15:05.740 2023-09-04 09:15:00                                                                                                                                         Details of Voting Results and Report of the Scrutinizer
   HAL 2023-09-01 17:01:27.883 2023-09-04 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2023-09-01 17:02:53.890 2023-09-04 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2023-09-01 17:06:56.487 2023-09-04 09:15:00                                                                                           Shareholders has approved sub-division of Equity Shares of the Company in 60th AGM held on 31.08.2023
   HAL 2023-09-01 17:09:24.247 2023-09-04 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2024-02-01 09:02:32.033 2024-02-01 09:15:00                                                                                                                                                                           announcement attached
   HAL 2024-02-01 09:14:21.697 2024-02-01 09:15:00       Hindustan Aeronautics Ltdhas informed BSE that the meeting of the Board of Directors of the Company is scheduled on 12/02/2024 ,inter alia, to consider and approve Announcement attached
   HAL 2024-03-22 17:40:26.457 2024-03-26 09:15:00                                                                                                                                                                        Announcement as attached
   HAL 2024-03-25 14:37:58.517 2024-03-26 09:15:00                                                                                                                                                                        announcement is attached
   HAL 2024-06-05 16:07:06.327 2024-06-06 09:15:00                                                                                                                                                                           announcement attached
   HAL 2024-06-05 16:10:43.087 2024-06-06 09:15:00                                                                                                                                                                        announcement is attached
   HAL 2024-06-17 15:06:56.513 2024-06-18 09:15:00                                                                                                                                                                           announcement attached
   HAL 2024-06-17 15:09:57.483 2024-06-18 09:15:00                                                                                                                                                                        announcement is attached
   HAL 2024-08-31 12:59:16.427 2024-09-02 09:15:00                                                                                                                                                                        Announcement is attached
   HAL 2024-08-31 16:27:45.800 2024-09-02 09:15:00                                                                                                                                                                        announcement is attached
   HAL 2024-09-09 16:33:12.170 2024-09-10 09:15:00                                                                                                                                                                        announcement is attached
   HAL 2024-09-09 17:16:13.580 2024-09-10 09:15:00                                                                                                                                                                        Announcement is attached
   HAL 2024-10-22 16:51:44.140 2024-10-23 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2024-10-22 17:13:28.450 2024-10-23 09:15:00                                                                                                                                                                        announcement is attached
   HAL 2024-12-27 16:39:07.627 2024-12-30 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2024-12-27 17:16:45.283 2024-12-30 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2024-12-27 17:32:44.840 2024-12-30 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2025-02-04 17:01:24.397 2025-02-05 09:15:00 Hindustan Aeronautics Ltdhas informed BSE that the meeting of the Board of Directors of the Company is scheduled on 12/02/2025 ,inter alia, to consider and approve In continuation to our ....
   HAL 2025-02-04 17:06:52.050 2025-02-05 09:15:00                                                                                                                                                                           Announcement attached
   HAL 2025-03-28 20:12:00.080 2025-04-01 09:15:00                                                                                                                                                                        Announcement as attached
   HAL 2025-03-31 18:36:30.993 2025-04-01 09:15:00                                                                                                                                                                        Announcement as attached
   HAL 2025-05-01 16:59:59.223 2025-05-02 09:15:00                                                                                                                                                                        Announcement as attached
   HAL 2025-05-01 17:18:07.760 2025-05-02 09:15:00                                                                                                                                                                        Announcement as attached
   HAL 2025-05-06 16:43:20.703 2025-05-07 09:15:00  Hindustan Aeronautics Ltdhas informed BSE that the meeting of the Board of Directors of the Company is scheduled on 14/05/2025 ,inter alia, to consider and approve the audited financial ....
   HAL 2025-05-06 20:21:41.830 2025-05-07 09:15:00                                                                                                                                                                        Announcement as attached

In [78]:
duplicate_counts = (
    aligned_events
    .groupby(["ticker", "event_time"])
    .size()
    .reset_index(name="announcement_count")
)

print(
    duplicate_counts[
        duplicate_counts["announcement_count"] > 1
    ]
    .sort_values("announcement_count", ascending=False)
    .to_string(index=False)
)

  ticker          event_time  announcement_count
HDFCBANK 2025-04-21 09:15:00                   9
HDFCBANK 2024-04-22 09:15:00                   9
RELIANCE 2025-01-17 09:15:00                   8
   NYKAA 2025-06-02 09:15:00                   8
RELIANCE 2025-04-28 09:15:00                   8
HDFCBANK 2024-07-22 09:15:00                   8
   NYKAA 2025-08-13 09:15:00                   8
RELIANCE 2024-01-20 09:15:00                   8
    RVNL 2023-09-04 09:15:00                   7
RELIANCE 2025-10-20 09:15:00                   7
RELIANCE 2025-07-21 09:15:00                   7
RELIANCE 2023-10-30 09:15:00                   7
   NYKAA 2025-11-10 09:15:00                   7
   NYKAA 2023-11-07 09:15:00                   7
RELIANCE 2026-01-19 09:15:00                   7
RELIANCE 2024-11-18 09:15:00                   7
HDFCBANK 2024-10-21 09:15:00                   7
   NYKAA 2024-08-14 09:15:00                   7
   NYKAA 2024-05-23 09:15:00                   7
RELIANCE 2026-05-29 09:15:00                   7
HDFCBANK 2026-04-20 09:15:00                   6
   NYKAA 2026-08-05 09:15:00                   6
   NYKAA 2024-11-13 09:15:00                   6
RELIANCE 2024-09-02 09:15:00                   6
RELIANCE 2024-04-23 09:15:00                   6
RELIANCE 2024-10-15 09:15:00                   6
RELIANCE 2026-04-27 09:15:00                   6
RELIANCE 2024-07-22 09:15:00                   6
RELIANCE 2026-07-20 09:15:00                   6
    RVNL 2026-08-03 09:15:00                   5
     HAL 2023-09-04 09:15:00                   5
HDFCBANK 2023-09-22 09:15:00                   5
    RVNL 2025-09-01 09:15:00                   5
   NYKAA 2024-02-07 09:15:00                   5
HDFCBANK 2026-01-19 09:15:00                   5
HDFCBANK 2025-07-21 09:15:00                   5
   NYKAA 2026-08-03 09:15:00                   5
   NYKAA 2026-02-06 09:15:00                   5
   NYKAA 2026-05-22 09:15:00                   5
RELIANCE 2026-06-22 09:15:00                   5
    RVNL 2025-02-17 09:15:00                   5
HDFCBANK 2023-10-17 09:15:00                   5
    RVNL 2024-05-18 09:15:00                   5
RELIANCE 2024-02-09 09:15:00                   5
RELIANCE 2024-09-11 09:15:00                   5
RELIANCE 2023-11-17 09:15:00                   5
RELIANCE 2024-04-18 09:15:00                   5
RELIANCE 2024-10-17 09:15:00                   5
   NYKAA 2025-02-11 09:15:00                   5
RELIANCE 2023-08-29 09:15:00                   5
    RVNL 2024-09-02 09:15:00                   4
    RVNL 2024-09-09 09:15:00                   4
    RVNL 2025-03-03 09:15:00                   4
    RVNL 2025-05-22 09:15:00                   4
HDFCBANK 2023-09-20 09:15:00                   4
    RVNL 2024-03-11 09:15:00                   4
    RVNL 2023-11-10 09:15:00                   4
RELIANCE 2025-09-01 09:15:00                   4
RELIANCE 2024-10-21 09:15:00                   4
RELIANCE 2024-11-21 09:15:00                   4
HDFCBANK 2024-03-20 09:15:00                   4
RELIANCE 2024-08-30 09:15:00                   4
HDFCBANK 2024-05-02 09:15:00                   4
HDFCBANK 2024-04-18 09:15:00                   4
RELIANCE 2023-11-22 09:15:00                   4
RELIANCE 2024-01-01 09:15:00                   4
RELIANCE 2024-01-15 09:15:00                   4
RELIANCE 2024-03-13 09:15:00                   4
RELIANCE 2024-05-30 09:15:00                   4
   NYKAA 2026-05-14 09:15:00                   4
RELIANCE 2023-08-30 09:15:00                   4
RELIANCE 2023-09-27 09:15:00                   4
   NYKAA 2025-08-04 09:15:00                   4
   NYKAA 2024-07-15 09:15:00                   4
HDFCBANK 2025-07-14 09:15:00                   4
   NYKAA 2023-09-20 09:15:00                   4
HDFCBANK 2026-07-13 09:15:00                   4
HDFCBANK 2026-07-20 09:15:00                   4
HDFCBANK 2026-04-06 09:15:00                   4
    RVNL 2025-11-12 09:15:00                   4
     HAL 2026-05-04 09:15:00                   3
HDFCBANK 2023-09-05 09:15:00                   3
     HAL 2026-01-29 09:15:00                   3
    RVNL 2025-08-07 09:15:00                   3
    RVNL 2024-05-21 09:15:00                   3
HDFCBANK 2025-10-20 09:15:00                   3
HDFCBANK 2025-12-01 09:15:00                   3
    RVNL 2025-05-16 09:15:00                   3
    RVNL 2024-07-10 09:15:00                   3
    RVNL 2024-07-30 09:15:00                   3
    RVNL 2024-10-01 09:15:00                   3
    RVNL 2024-11-07 09:15:00                   3
    RVNL 2023-08-30 09:15:00                   3
    RVNL 2023-09-28 09:15:00                   3
    RVNL 2024-04-01 09:15:00                   3
RELIANCE 2026-02-09 09:15:00                   3
RELIANCE 2026-02-11 09:15:00                   3
RELIANCE 2026-06-01 09:15:00                   3
RELIANCE 2026-06-03 09:15:00                   3
HDFCBANK 2024-01-17 09:15:00                   3
HDFCBANK 2024-02-13 09:15:00                   3
   NYKAA 2023-11-09 09:15:00                   3
    RVNL 2026-02-06 09:15:00                   3
HDFCBANK 2024-02-29 09:15:00                   3
HDFCBANK 2024-04-02 09:15:00                   3
RELIANCE 2025-10-31 09:15:00                   3
RELIANCE 2024-11-14 09:15:00                   3
RELIANCE 2024-11-29 09:15:00                   3
RELIANCE 2025-02-11 09:15:00                   3
RELIANCE 2024-09-20 09:15:00                   3
RELIANCE 2024-09-25 09:15:00                   3
RELIANCE 2024-09-30 09:15:00                   3
RELIANCE 2024-11-11 09:15:00                   3
RELIANCE 2024-08-07 09:15:00                   3
RELIANCE 2024-08-16 09:15:00                   3
   NYKAA 2024-08-27 09:15:00                   3
   NYKAA 2024-09-19 09:15:00                   3
HDFCBANK 2026-03-19 09:15:00                   3
HDFCBANK 2026-03-24 09:15:00                   3
RELIANCE 2024-08-29 09:15:00                   3
RELIANCE 2024-09-09 09:15:00                   3
RELIANCE 2024-09-12 09:15:00                   3
RELIANCE 2024-09-16 09:15:00                   3
RELIANCE 2024-06-12 09:15:00                   3
RELIANCE 2024-06-14 09:15:00                   3
RELIANCE 2024-06-24 09:15:00                   3
RELIANCE 2024-06-27 09:15:00                   3
RELIANCE 2024-07-10 09:15:00                   3
HDFCBANK 2024-04-29 09:15:00                   3
HDFCBANK 2024-07-19 09:15:00                   3
RELIANCE 2024-06-06 09:15:00                   3
RELIANCE 2024-04-01 09:15:00                   3
RELIANCE 2023-08-23 09:15:00                   3
HDFCBANK 2024-09-02 09:15:00                   3
RELIANCE 2024-04-25 09:15:00                   3
RELIANCE 2024-05-02 09:15:00                   3
RELIANCE 2024-05-22 09:15:00                   3
RELIANCE 2024-02-15 09:15:00                   3
RELIANCE 2024-02-29 09:15:00                   3
RELIANCE 2024-03-07 09:15:00                   3
RELIANCE 2023-11-06 09:15:00                   3
RELIANCE 2023-11-10 09:15:00                   3
RELIANCE 2023-11-23 09:15:00                   3
RELIANCE 2023-09-15 09:15:00                   3
RELIANCE 2023-09-20 09:15:00                   3
RELIANCE 2023-10-23 09:15:00                   3
HDFCBANK 2024-10-30 09:15:00                   3
HDFCBANK 2024-12-11 09:15:00                   3
RELIANCE 2023-09-04 09:15:00                   3
HDFCBANK 2023-09-14 09:15:00                   3
HDFCBANK 2023-10-26 09:15:00                   3
     HAL 2025-06-30 09:15:00                   3
     HAL 2025-09-01 09:15:00                   3
    RVNL 2026-05-26 09:15:00                   3
    RVNL 2026-07-29 09:15:00                   3
     HAL 2024-12-30 09:15:00                   3
     HAL 2024-06-18 09:15:00                   2
     HAL 2024-10-23 09:15:00                   2
     HAL 2025-02-05 09:15:00                   2
     HAL 2026-02-05 09:15:00                   2
    RVNL 2026-01-16 09:15:00                   2
    RVNL 2025-03-12 09:15:00                   2
     HAL 2024-06-06 09:15:00                   2
    RVNL 2026-07-30 09:15:00                   2
    RVNL 2026-07-27 09:15:00                   2
    RVNL 2026-05-29 09:15:00                   2
    RVNL 2025-08-01 09:15:00                   2
    RVNL 2025-07-03 09:15:00                   2
    RVNL 2024-06-10 09:15:00                   2
    RVNL 2024-06-11 09:15:00                   2
    RVNL 2024-06-27 09:15:00                   2
HDFCBANK 2025-07-28 09:15:00                   2
HDFCBANK 2025-08-11 09:15:00                   2
HDFCBANK 2025-10-01 09:15:00                   2
HDFCBANK 2025-10-29 09:15:00                   2
HDFCBANK 2025-12-10 09:15:00                   2
HDFCBANK 2025-12-19 09:15:00                   2
HDFCBANK 2026-02-04 09:15:00                   2
HDFCBANK 2026-02-12 09:15:00                   2
     HAL 2025-04-01 09:15:00                   2
    RVNL 2025-03-25 09:15:00                   2
    RVNL 2025-05-07 09:15:00                   2
    RVNL 2025-05-14 09:15:00                   2
    RVNL 2025-05-30 09:15:00                   2
HDFCBANK 2024-09-03 09:15:00                   2
HDFCBANK 2024-09-12 09:15:00                   2
HDFCBANK 2024-10-03 09:15:00                   2
HDFCBANK 2024-11-07 09:15:00                   2
HDFCBANK 2024-11-13 09:15:00                   2
HDFCBANK 2024-11-26 09:15:00                   2
HDFCBANK 2024-11-27 09:15:00                   2
HDFCBANK 2024-11-29 09:15:00                   2
HDFCBANK 2024-12-17 09:15:00                   2
HDFCBANK 2024-12-18 09:15:00                   2
RELIANCE 2023-08-24 09:15:00                   2
RELIANCE 2023-08-25 09:15:00                   2
RELIANCE 2023-09-01 09:15:00                   2
   NYKAA 2025-04-07 09:15:00                   2
   NYKAA 2025-04-11 09:15:00                   2
   NYKAA 2025-05-20 09:15:00                   2
RELIANCE 2023-12-18 09:15:00                   2
RELIANCE 2024-01-03 09:15:00                   2
RELIANCE 2024-01-10 09:15:00                   2
RELIANCE 2023-09-06 09:15:00                   2
RELIANCE 2023-09-07 09:15:00                   2
RELIANCE 2023-09-11 09:15:00                   2
RELIANCE 2023-09-12 09:15:00                   2
RELIANCE 2023-09-13 09:15:00                   2
RELIANCE 2023-09-22 09:15:00                   2
RELIANCE 2023-09-25 09:15:00                   2
RELIANCE 2023-10-03 09:15:00                   2
RELIANCE 2023-10-09 09:15:00                   2
RELIANCE 2023-10-10 09:15:00                   2
RELIANCE 2023-10-16 09:15:00                   2
RELIANCE 2023-10-18 09:15:00                   2
RELIANCE 2023-11-01 09:15:00                   2
RELIANCE 2024-02-22 09:15:00                   2
RELIANCE 2024-02-26 09:15:00                   2
RELIANCE 2024-03-01 09:15:00                   2
RELIANCE 2024-03-14 09:15:00                   2
RELIANCE 2024-03-20 09:15:00                   2
RELIANCE 2024-03-26 09:15:00                   2
RELIANCE 2023-11-02 09:15:00                   2
RELIANCE 2023-11-03 09:15:00                   2
RELIANCE 2023-11-08 09:15:00                   2
RELIANCE 2023-11-15 09:15:00                   2
RELIANCE 2023-11-20 09:15:00                   2
RELIANCE 2023-12-01 09:15:00                   2
RELIANCE 2023-12-04 09:15:00                   2
RELIANCE 2023-12-08 09:15:00                   2
RELIANCE 2023-12-13 09:15:00                   2
RELIANCE 2023-12-14 09:15:00                   2
HDFCBANK 2025-05-29 09:15:00                   2
HDFCBANK 2025-06-09 09:15:00                   2
RELIANCE 2024-04-26 09:15:00                   2
RELIANCE 2024-05-08 09:15:00                   2
RELIANCE 2024-05-09 09:15:00                   2
RELIANCE 2024-05-16 09:15:00                   2
RELIANCE 2024-05-23 09:15:00                   2
RELIANCE 2024-05-27 09:15:00                   2
HDFCBANK 2024-04-09 09:15:00                   2
RELIANCE 2024-01-17 09:15:00                   2
RELIANCE 2024-01-25 09:15:00                   2
RELIANCE 2024-01-31 09:15:00                   2
RELIANCE 2024-02-05 09:15:00                   2
RELIANCE 2024-02-07 09:15:00                   2
RELIANCE 2024-02-14 09:15:00                   2
RELIANCE 2024-02-21 09:15:00                   2
RELIANCE 2024-04-05 09:15:00                   2
RELIANCE 2024-04-10 09:15:00                   2
RELIANCE 2024-04-12 09:15:00                   2
RELIANCE 2024-04-16 09:15:00                   2
   NYKAA 2026-02-10 09:15:00                   2
   NYKAA 2026-04-07 09:15:00                   2
   NYKAA 2026-05-11 09:15:00                   2
   NYKAA 2026-07-24 09:15:00                   2
   NYKAA 2026-07-28 09:15:00                   2
   NYKAA 2026-08-10 09:15:00                   2
HDFCBANK 2024-07-31 09:15:00                   2
HDFCBANK 2024-08-12 09:15:00                   2
HDFCBANK 2025-01-30 09:15:00                   2
HDFCBANK 2025-03-03 09:15:00                   2
HDFCBANK 2025-03-27 09:15:00                   2
HDFCBANK 2025-05-16 09:15:00                   2
RELIANCE 2024-07-31 09:15:00                   2
RELIANCE 2024-08-06 09:15:00                   2
HDFCBANK 2024-04-12 09:15:00                   2
HDFCBANK 2024-04-23 09:15:00                   2
HDFCBANK 2024-05-06 09:15:00                   2
HDFCBANK 2024-05-07 09:15:00                   2
HDFCBANK 2024-05-18 09:15:00                   2
HDFCBANK 2024-05-31 09:15:00                   2
HDFCBANK 2024-06-11 09:15:00                   2
HDFCBANK 2024-06-21 09:15:00                   2
HDFCBANK 2024-07-24 09:15:00                   2
RELIANCE 2024-05-29 09:15:00                   2
RELIANCE 2024-06-04 09:15:00                   2
RELIANCE 2024-06-05 09:15:00                   2
RELIANCE 2024-06-11 09:15:00                   2
RELIANCE 2024-03-28 09:15:00                   2
HDFCBANK 2026-05-27 09:15:00                   2
RELIANCE 2024-08-26 09:15:00                   2
RELIANCE 2024-09-04 09:15:00                   2
RELIANCE 2024-09-05 09:15:00                   2
RELIANCE 2024-09-06 09:15:00                   2
RELIANCE 2024-09-13 09:15:00                   2
RELIANCE 2024-09-18 09:15:00                   2
RELIANCE 2024-06-26 09:15:00                   2
RELIANCE 2024-06-28 09:15:00                   2
RELIANCE 2024-07-01 09:15:00                   2
RELIANCE 2024-07-03 09:15:00                   2
RELIANCE 2024-07-08 09:15:00                   2
RELIANCE 2024-07-12 09:15:00                   2
RELIANCE 2024-07-15 09:15:00                   2
RELIANCE 2024-07-18 09:15:00                   2
RELIANCE 2024-07-24 09:15:00                   2
RELIANCE 2024-11-01 18:00:00                   2
RELIANCE 2024-08-08 09:15:00                   2
RELIANCE 2024-08-09 09:15:00                   2
RELIANCE 2024-08-14 09:15:00                   2
RELIANCE 2024-08-21 09:15:00                   2
HDFCBANK 2025-06-12 09:15:00                   2
HDFCBANK 2025-06-20 09:15:00                   2
HDFCBANK 2025-07-16 09:15:00                   2
HDFCBANK 2025-07-22 09:15:00                   2
HDFCBANK 2025-07-24 09:15:00                   2
   NYKAA 2024-05-13 09:15:00                   2
   NYKAA 2024-05-15 09:15:00                   2
   NYKAA 2024-10-08 09:15:00                   2
HDFCBANK 2026-03-20 09:15:00                   2
HDFCBANK 2026-04-15 09:15:00                   2
HDFCBANK 2026-04-17 09:15:00                   2
RELIANCE 2024-12-23 09:15:00                   2
RELIANCE 2024-12-30 09:15:00                   2
RELIANCE 2025-01-01 09:15:00                   2
RELIANCE 2025-01-10 09:15:00                   2
RELIANCE 2025-02-13 09:15:00                   2
RELIANCE 2024-09-19 09:15:00                   2
RELIANCE 2024-09-23 09:15:00                   2
RELIANCE 2024-10-03 09:15:00                   2
RELIANCE 2024-10-08 09:15:00                   2
RELIANCE 2024-10-09 09:15:00                   2
RELIANCE 2024-10-10 09:15:00                   2
RELIANCE 2024-10-18 09:15:00                   2
RELIANCE 2024-10-23 09:15:00                   2
RELIANCE 2024-10-25 09:15:00                   2
RELIANCE 2024-10-30 09:15:00                   2
RELIANCE 2024-10-31 09:15:00                   2
RELIANCE 2025-07-01 09:15:00                   2
RELIANCE 2025-07-14 09:15:00                   2
RELIANCE 2025-07-31 09:15:00                   2
RELIANCE 2025-08-01 09:15:00                   2
RELIANCE 2025-08-19 09:15:00                   2
HDFCBANK 2023-12-12 09:15:00                   2
HDFCBANK 2023-12-27 09:15:00                   2
HDFCBANK 2024-01-01 09:15:00                   2
RELIANCE 2024-11-13 09:15:00                   2
RELIANCE 2024-11-19 09:15:00                   2
RELIANCE 2024-11-22 09:15:00                   2
RELIANCE 2024-12-04 09:15:00                   2
RELIANCE 2024-12-06 09:15:00                   2
RELIANCE 2024-12-11 09:15:00                   2
RELIANCE 2024-12-13 09:15:00                   2
RELIANCE 2024-12-16 09:15:00                   2
    RVNL 2026-03-04 09:15:00                   2
HDFCBANK 2024-03-07 09:15:00                   2
HDFCBANK 2024-03-19 09:15:00                   2
HDFCBANK 2024-03-21 09:15:00                   2
HDFCBANK 2024-04-01 09:15:00                   2
RELIANCE 2025-09-19 09:15:00                   2
RELIANCE 2025-10-10 09:15:00                   2
RELIANCE 2025-10-27 09:15:00                   2
RELIANCE 2025-02-17 09:15:00                   2
RELIANCE 2025-04-01 09:15:00                   2
RELIANCE 2025-04-21 09:15:00                   2
RELIANCE 2025-05-05 09:15:00                   2
RELIANCE 2025-05-29 09:15:00                   2
RELIANCE 2025-06-02 09:15:00                   2
RELIANCE 2025-06-11 09:15:00                   2
RELIANCE 2025-06-13 09:15:00                   2
HDFCBANK 2024-02-06 09:15:00                   2
HDFCBANK 2024-02-14 09:15:00                   2
HDFCBANK 2024-02-26 09:15:00                   2
HDFCBANK 2026-05-29 09:15:00                   2
HDFCBANK 2026-06-29 09:15:00                   2
HDFCBANK 2026-06-30 09:15:00                   2
HDFCBANK 2026-07-27 09:15:00                   2
HDFCBANK 2026-08-06 09:15:00                   2
   NYKAA 2023-10-06 09:15:00                   2
   NYKAA 2023-12-04 09:15:00                   2
HDFCBANK 2025-01-06 09:15:00                   2
HDFCBANK 2025-01-23 09:15:00                   2
    RVNL 2026-01-23 09:15:00                   2
    RVNL 2026-01-28 09:15:00                   2
    RVNL 2026-01-29 09:15:00                   2
    RVNL 2026-02-26 09:15:00                   2
    RVNL 2024-02-09 09:15:00                   2
    RVNL 2024-02-12 09:15:00                   2
    RVNL 2024-03-12 09:15:00                   2
RELIANCE 2025-11-13 09:15:00                   2
RELIANCE 2025-12-02 09:15:00                   2
RELIANCE 2025-12-04 09:15:00                   2
RELIANCE 2025-12-05 09:15:00                   2
RELIANCE 2026-01-09 09:15:00                   2
RELIANCE 2026-01-30 09:15:00                   2
RELIANCE 2026-03-11 09:15:00                   2
RELIANCE 2026-04-01 09:15:00                   2
RELIANCE 2026-04-20 09:15:00                   2
RELIANCE 2026-05-21 09:15:00                   2
RELIANCE 2026-06-10 09:15:00                   2
RELIANCE 2026-07-13 09:15:00                   2
HDFCBANK 2024-01-20 09:15:00                   2
    RVNL 2024-10-03 09:15:00                   2
    RVNL 2024-10-31 09:15:00                   2
    RVNL 2024-11-06 09:15:00                   2
    RVNL 2024-11-08 09:15:00                   2
    RVNL 2024-11-11 09:15:00                   2
    RVNL 2024-11-25 09:15:00                   2
RELIANCE 2026-08-10 09:15:00                   2
RELIANCE 2026-08-19 09:15:00                   2
    RVNL 2023-10-03 09:15:00                   2
    RVNL 2023-10-09 09:15:00                   2
    RVNL 2023-10-20 09:15:00                   2
    RVNL 2023-11-12 18:15:00                   2
    RVNL 2023-11-15 09:15:00                   2
    RVNL 2024-01-03 09:15:00                   2
    RVNL 2024-01-15 09:15:00                   2

In [79]:
print("Total announcement-event rows:", len(duplicate_counts))
print(
    "Maximum announcements on one trading session:",
    duplicate_counts["announcement_count"].max()
)

Total announcement-event rows: 1743
Maximum announcements on one trading session: 9

In [80]:
print("Total announcement-event rows:", len(duplicate_counts))
print(
    "Maximum announcements on one trading session:",
    duplicate_counts["announcement_count"].max()
)

Total announcement-event rows: 1743
Maximum announcements on one trading session: 9

In [81]:
# Find DataFrames that contain the announcement_count column

for name, obj in list(globals().items()):
    if hasattr(obj, "columns"):
        if "announcement_count" in obj.columns:
            print("Found:", name)

Found: duplicate_counts

In [82]:
# Safely find the DataFrame containing announcement_count

for name in list(globals().keys()):
    obj = globals()[name]
    if hasattr(obj, "columns") and "announcement_count" in obj.columns:
        print("Found:", name)

Found: duplicate_counts

In [83]:
# Count announcements by ticker and trading session

daily_counts = (
    aligned_events
    .assign(trading_date=aligned_events["event_time"].dt.date)
    .groupby(["ticker", "trading_date"])
    .size()
    .reset_index(name="announcement_count")
)

print("daily_counts created:", daily_counts.shape)

daily_counts created: (1515, 3)

In [84]:
df = daily_counts

print("Total announcement-event rows:", len(df))

print(
    "Maximum announcements on one trading session:",
    df["announcement_count"].max()
)

print("\nTop 10 busiest announcement sessions:")
print(
    df.sort_values("announcement_count", ascending=False)
      .head(10)
      .to_string(index=False)
)

print("\nAnnouncement counts by ticker:")
print(
    df.groupby("ticker")["announcement_count"]
      .agg(
          trading_sessions="count",
          total_announcements="sum",
          max_announcements="max"
    )
)

Total announcement-event rows: 1515
Maximum announcements on one trading session: 9

Top 10 busiest announcement sessions:
  ticker trading_date  announcement_count
HDFCBANK   2024-07-22                   9
HDFCBANK   2025-04-21                   9
HDFCBANK   2024-04-22                   9
   NYKAA   2025-06-02                   8
   NYKAA   2024-08-14                   8
RELIANCE   2024-01-20                   8
RELIANCE   2025-04-28                   8
   NYKAA   2025-08-13                   8
   NYKAA   2025-11-10                   8
RELIANCE   2025-01-17                   8

Announcement counts by ticker:
          trading_sessions  total_announcements  max_announcements
ticker
HAL                    189                  276                  5
HDFCBANK               364                  605                  9
NYKAA                  202                  339                  8
RELIANCE               458                  844                  8
RVNL                   302                  464                  7

In [85]:
# Safely identify the DataFrame containing announcement_count

found = []

for name in list(globals().keys()):
    try:
        obj = globals()[name]
        if hasattr(obj, "columns") and "announcement_count" in obj.columns:
            found.append(name)
    except:
        pass

print("DataFrames found:", found)

DataFrames found: ['df', 'duplicate_counts', 'daily_counts']

In [86]:
df = duplicate_counts.copy()

print("Total announcement-event rows:", len(df))

print(
    "Maximum announcements on one trading session:",
    df["announcement_count"].max()
)

print("\nTop 10 busiest announcement sessions:")
print(
    df.sort_values("announcement_count", ascending=False)
      .head(10)
      .to_string(index=False)
)

print("\nAnnouncement counts by ticker:")
print(
    df.groupby("ticker")["announcement_count"]
      .agg(
          trading_sessions="count",
          total_announcements="sum",
          max_announcements="max"
    )
)

Total announcement-event rows: 1743
Maximum announcements on one trading session: 9

Top 10 busiest announcement sessions:
  ticker          event_time  announcement_count
HDFCBANK 2025-04-21 09:15:00                   9
HDFCBANK 2024-04-22 09:15:00                   9
RELIANCE 2024-01-20 09:15:00                   8
   NYKAA 2025-06-02 09:15:00                   8
RELIANCE 2025-04-28 09:15:00                   8
RELIANCE 2025-01-17 09:15:00                   8
HDFCBANK 2024-07-22 09:15:00                   8
   NYKAA 2025-08-13 09:15:00                   8
RELIANCE 2026-01-19 09:15:00                   7
RELIANCE 2025-10-20 09:15:00                   7

Announcement counts by ticker:
          trading_sessions  total_announcements  max_announcements
ticker
HAL                    247                  276                  5
HDFCBANK               429                  605                  9
NYKAA                  236                  339                  8
RELIANCE               485                  844                  8
RVNL                   346                  464                  7

In [87]:
# Classify announcements by when they were released

ann = announcements.copy()

ann["DissemDT"] = pd.to_datetime(ann["DissemDT"])

ann["announcement_hour"] = ann["DissemDT"].dt.hour
ann["announcement_minute"] = ann["DissemDT"].dt.minute
ann["announcement_time"] = ann["DissemDT"].dt.time

def classify_timing(t):
    if t < pd.Timestamp("09:15").time():
        return "Pre-market"
    elif t <= pd.Timestamp("15:30").time():
        return "During-market"
    else:
        return "After-market"

ann["market_timing"] = ann["announcement_time"].apply(classify_timing)

print("\nAnnouncement timing:")
print(
    ann["market_timing"]
    .value_counts()
)

print("\nAnnouncement timing by ticker:")
print(
    pd.crosstab(
        ann["ticker"],
        ann["market_timing"]
    )
)

Announcement timing:
market_timing
After-market     1876
During-market     594
Pre-market         60
Name: count, dtype: int64

Announcement timing by ticker:
market_timing  After-market  During-market  Pre-market
ticker
HAL                     121            147           8
HDFCBANK                419            165          23
NYKAA                   235            100           4
RELIANCE                751             71          22
RVNL                    350            111           3

In [88]:
# Trading data dictionary

stock_data = {
    "RELIANCE": stocks["RELIANCE"],
    "HDFCBANK": stocks["HDFCBANK"],
    "NYKAA": stocks["NYKAA"],
    "RVNL": stocks["RVNL"],
    "HAL": stocks["HAL"]
}

print("Trading data loaded for:")
for ticker, df in stock_data.items():
    print(f"{ticker}: {len(df):,} rows")

Trading data loaded for:
RELIANCE: 277,510 rows
HDFCBANK: 277,510 rows
NYKAA: 277,508 rows
RVNL: 277,509 rows
HAL: 277,510 rows

In [89]:
for name in list(globals().keys()):
    try:
        obj = globals()[name]

        if hasattr(obj, "columns"):
            cols = set(obj.columns)

            required = {"date", "open", "high", "low", "close", "volume"}

            if required.issubset(cols):
                print(name, "->", obj.shape)
    except:
        pass

reliance -> (277510, 7)
df -> (277510, 7)
zero_volume -> (187, 7)
future_bars -> (276385, 7)
stock_df -> (277509, 7)

In [90]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path(r"C:\IndoThai_Quant_Assessment\data")

stock_files = {
    "RELIANCE": "RELIANCE.csv",
    "HDFCBANK": "HDFCBANK.csv",
    "NYKAA": "NYKAA.csv",
    "RVNL": "RVNL.csv",
    "HAL": "HAL.csv"
}

stocks = {}

for ticker, filename in stock_files.items():
    path = DATA_DIR / filename

    df_stock = pd.read_csv(path)
    df_stock["date"] = pd.to_datetime(df_stock["date"])
    df_stock = df_stock.sort_values("date").reset_index(drop=True)

    stocks[ticker] = df_stock

    print(
        f"{ticker}: {len(df_stock):,} rows | "
        f"{df_stock['date'].min()} → {df_stock['date'].max()}"
    )

RELIANCE: 277,510 rows | 2023-08-21 09:15:00 → 2026-08-19 15:29:00
HDFCBANK: 277,510 rows | 2023-08-21 09:15:00 → 2026-08-19 15:29:00
NYKAA: 277,508 rows | 2023-08-21 09:15:00 → 2026-08-19 15:29:00
RVNL: 277,509 rows | 2023-08-21 09:15:00 → 2026-08-19 15:29:00
HAL: 277,510 rows | 2023-08-21 09:15:00 → 2026-08-19 15:29:00

In [91]:
def classify_timing(t):
    t = t.time()

    if t < pd.Timestamp("09:15").time():
        return "Pre-market"
    elif t <= pd.Timestamp("15:30").time():
        return "During-market"
    else:
        return "After-market"

ann["market_timing"] = ann["DissemDT"].apply(classify_timing)

print(ann["market_timing"].value_counts())

market_timing
After-market     1876
During-market     594
Pre-market         60
Name: count, dtype: int64

In [92]:
ann = announcements.copy()
ann["DissemDT"] = pd.to_datetime(ann["DissemDT"])

# Classify announcement timing
def classify_timing(t):
    t = t.time()

    if t < pd.Timestamp("09:15").time():
        return "Pre-market"
    elif t <= pd.Timestamp("15:30").time():
        return "During-market"
    else:
        return "After-market"

ann["market_timing"] = ann["DissemDT"].apply(classify_timing)

# Find the first trading bar at or after announcement time
def find_event_bar(row):
    ticker = row["ticker"]
    announcement_time = row["DissemDT"]

    prices = stocks[ticker]
    candidates = prices[prices["date"] >= announcement_time]

    if candidates.empty:
        return pd.NaT

    return candidates.iloc[0]["date"]

ann["event_time_correct"] = ann.apply(find_event_bar, axis=1)

print("Total announcements:", len(ann))
print("Successfully aligned:", ann["event_time_correct"].notna().sum())
print("Unaligned:", ann["event_time_correct"].isna().sum())

print("\nTiming alignment:")
print(
    ann[
        ["ticker", "DissemDT", "market_timing", "event_time_correct"]
    ].head(15).to_string(index=False)
)

Total announcements: 2530
Successfully aligned: 2528
Unaligned: 2

Timing alignment:
  ticker                DissemDT market_timing  event_time_correct
HDFCBANK 2026-08-19 23:19:39.420  After-market                 NaT
HDFCBANK 2026-08-19 22:52:54.670  After-market                 NaT
RELIANCE 2026-08-18 20:06:38.747  After-market 2026-08-19 09:15:00
RELIANCE 2026-08-18 17:44:19.310  After-market 2026-08-19 09:15:00
    RVNL 2026-08-18 14:24:13.290 During-market 2026-08-18 14:25:00
RELIANCE 2026-08-17 17:18:06.063  After-market 2026-08-18 09:15:00
HDFCBANK 2026-08-16 19:43:27.497  After-market 2026-08-17 09:15:00
    RVNL 2026-08-14 18:22:56.080  After-market 2026-08-17 09:15:00
RELIANCE 2026-08-14 17:45:54.693  After-market 2026-08-17 09:15:00
HDFCBANK 2026-08-14 14:10:20.837 During-market 2026-08-14 14:11:00
RELIANCE 2026-08-13 19:40:26.910  After-market 2026-08-14 09:15:00
    RVNL 2026-08-13 18:10:55.750  After-market 2026-08-14 09:15:00
HDFCBANK 2026-08-13 16:21:49.777  After-market 2026-08-14 09:15:00
RELIANCE 2026-08-12 19:47:33.767  After-market 2026-08-13 09:15:00
   NYKAA 2026-08-12 19:45:26.120  After-market 2026-08-13 09:15:00

In [93]:
print(
    ann[ann["event_time_correct"].isna()][
        ["ticker", "DissemDT", "HEADLINE"]
    ].to_string(index=False)
)

  ticker                DissemDT                                                                                                                                                       HEADLINE
HDFCBANK 2026-08-19 23:19:39.420 Intimation of Credit Rating pursuant to Regulation 30 of SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015 ("SEBI Listing Regulations")
HDFCBANK 2026-08-19 22:52:54.670       Intimation under Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 ("SEBI Listing Regulations")

In [94]:
def classify_timing(t):
    t = t.time()

    if t < pd.Timestamp("09:15").time():
        return "Pre-market"
    elif t <= pd.Timestamp("15:30").time():
        return "During-market"
    else:
        return "After-market"

ann["market_timing"] = ann["DissemDT"].apply(classify_timing)

print(
    ann["market_timing"].value_counts()
)

market_timing
After-market     1876
During-market     594
Pre-market         60
Name: count, dtype: int64

In [95]:
# Create final event dataset using successfully aligned announcements

events = ann[ann["event_time_correct"].notna()].copy()

print("Final aligned announcements:", len(events))
print("Excluded announcements:", ann["event_time_correct"].isna().sum())

print("\nEvent timing:")
print(
    events["market_timing"].value_counts()
)

print("\nEvents by ticker:")
print(
    events["ticker"].value_counts()
)

Final aligned announcements: 2528
Excluded announcements: 2

Event timing:
market_timing
After-market     1874
During-market     594
Pre-market         60
Name: count, dtype: int64

Events by ticker:
ticker
RELIANCE    844
HDFCBANK    605
RVNL        464
NYKAA       339
HAL         276
Name: count, dtype: int64

In [96]:
print(
    events[
        [
            "ticker",
            "DissemDT",
            "market_timing",
            "event_time_correct",
            "HEADLINE"
        ]
    ].head(10).to_string(index=False)
)

  ticker                DissemDT market_timing  event_time_correct                                                                                                                                                                                                                                                                                                                                                            HEADLINE
RELIANCE 2026-08-18 20:06:38.747  After-market 2026-08-19 09:15:00                                                                                                                                                                 This is further to the disclosure dated August 13, 2026 made by the Company. We wish to inform you that the Company executives participated in the Institutional Investors'' Meeting - Motilal ....
RELIANCE 2026-08-18 17:44:19.310  After-market 2026-08-19 09:15:00                                                                                                                                                                                                                                                                                                    Please refer our letter dated August 18, 2026 attached herewith.
    RVNL 2026-08-18 14:24:13.290 During-market 2026-08-18 14:25:00                                                                                                                                                                                                                                                                                                                        Transcript of Conference Call with Investors
RELIANCE 2026-08-17 17:18:06.063  After-market 2026-08-18 09:15:00 The Exchange has sought clarification from Reliance Industries Ltd with reference to the media report appearing on https://economictimes.indiatimes.com dated August 14, 2026,(Link: https://economictimes.indiatimes.com/industry/energy/oil-gas/sc-slaps-rs-10-lakh-fine-on-reliance-industries-for-delaying-ntpc-gas-supply-suit/articleshow/133249366.cms) ....
HDFCBANK 2026-08-16 19:43:27.497  After-market 2026-08-17 09:15:00                                                                                                                                                                                             Intimation of Schedule of Analyst / Institutional Investor Meetings under Regulation 30 of the SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015
    RVNL 2026-08-14 18:22:56.080  After-market 2026-08-17 09:15:00                                                                                                                                                                                                                                   Appointment of Shri Rakesh Bhalla (DIN: 07020164) as Non-Official (Independent) Director on the Board of Rail Vikas Nigam Limited
RELIANCE 2026-08-14 17:45:54.693  After-market 2026-08-17 09:15:00                                                                                                                                                                    Please find attached a media release by the Company, titled "Reliance Industries and Rolls-Royce announce strategic intent to partner and develop India''s indigenous combat engine for the ....
HDFCBANK 2026-08-14 14:10:20.837 During-market 2026-08-14 14:11:00                                                                                                                                                                                                                                                                                                 Allotment of 1729212 equity shares pursuant to exercise of ESOP/RSU
RELIANCE 2026-08-13 19:40:26.910  After-market 2026-08-14 09:15:00                                                                                                                                                                      Please note that the Company executives will be participating in the Institutional Investors'' Meeting - Motilal Oswal''s 22nd Annual Global Investor Conference, scheduled to be held on ....
    RVNL 2026-08-13 18:10:55.750  After-market 2026-08-14 09:15:00                                                                                                                                                                Dear Sir/Madam, \r\n????? ?????/??????,\r\n\r\nThis is further to our letter dated 06.08.2026 regarding intimation of the Schedule of Conference Call with Investor/Analyst/Institutions. It is ....

In [97]:
# Calculate 1-minute simple returns for each stock

for ticker, df_stock in stocks.items():
    df_stock = df_stock.sort_values("date").copy()

    df_stock["return"] = (
        df_stock["close"] / df_stock["close"].shift(1)
    ) - 1

    stocks[ticker] = df_stock

    print(
        f"{ticker}: "
        f"rows={len(df_stock):,}, "
        f"returns={df_stock['return'].notna().sum():,}, "
        f"missing_returns={df_stock['return'].isna().sum()}"
    )

RELIANCE: rows=277,510, returns=277,509, missing_returns=1
HDFCBANK: rows=277,510, returns=277,509, missing_returns=1
NYKAA: rows=277,508, returns=277,507, missing_returns=1
RVNL: rows=277,509, returns=277,508, missing_returns=1
HAL: rows=277,510, returns=277,509, missing_returns=1

In [98]:
def get_event_price(row):
    ticker = row["ticker"]
    event_time = row["event_time_correct"]

    prices = stocks[ticker]

    match = prices.loc[prices["date"] == event_time, "close"]

    if len(match) == 0:
        return pd.NA

    return match.iloc[0]


events["event_close"] = events.apply(get_event_price, axis=1)

print("Events with event price:", events["event_close"].notna().sum())
print("Events without event price:", events["event_close"].isna().sum())

print(
    events[
        ["ticker", "DissemDT", "event_time_correct", "event_close"]
    ].head(10).to_string(index=False)
)

Events with event price: 2528
Events without event price: 0
  ticker                DissemDT  event_time_correct  event_close
RELIANCE 2026-08-18 20:06:38.747 2026-08-19 09:15:00      1318.20
RELIANCE 2026-08-18 17:44:19.310 2026-08-19 09:15:00      1318.20
    RVNL 2026-08-18 14:24:13.290 2026-08-18 14:25:00       225.70
RELIANCE 2026-08-17 17:18:06.063 2026-08-18 09:15:00      1311.60
HDFCBANK 2026-08-16 19:43:27.497 2026-08-17 09:15:00       726.45
    RVNL 2026-08-14 18:22:56.080 2026-08-17 09:15:00       226.55
RELIANCE 2026-08-14 17:45:54.693 2026-08-17 09:15:00      1308.50
HDFCBANK 2026-08-14 14:10:20.837 2026-08-14 14:11:00       727.85
RELIANCE 2026-08-13 19:40:26.910 2026-08-14 09:15:00      1310.50
    RVNL 2026-08-13 18:10:55.750 2026-08-14 09:15:00       228.69

In [99]:
# Create trading-minute positions for each stock

for ticker, df_stock in stocks.items():
    df_stock = df_stock.sort_values("date").reset_index(drop=True).copy()
    df_stock["bar_index"] = range(len(df_stock))
    stocks[ticker] = df_stock

print("Trading-minute indices created.")

Trading-minute indices created.

In [100]:
# Find the bar index corresponding to each event

def get_event_index(row):
    ticker = row["ticker"]
    event_time = row["event_time_correct"]

    prices = stocks[ticker]

    match = prices.index[
        prices["date"] == event_time
    ]

    if len(match) == 0:
        return pd.NA

    return match[0]


events["event_index"] = events.apply(get_event_index, axis=1)

print(
    "Events with valid event index:",
    events["event_index"].notna().sum()
)

print(
    "Events without event index:",
    events["event_index"].isna().sum()
)

Events with valid event index: 2528
Events without event index: 0

In [101]:
event_windows = []

for _, event in events.iterrows():

    ticker = event["ticker"]
    event_idx = int(event["event_index"])

    prices = stocks[ticker]

    start_idx = event_idx - 30
    end_idx = event_idx + 30

    # Skip events where the complete window isn't available
    if start_idx < 0 or end_idx >= len(prices):
        continue

    window = prices.iloc[start_idx:end_idx + 1].copy()

    window["ticker"] = ticker
    window["event_id"] = event.name
    window["event_time"] = event["event_time_correct"]

    # Relative trading-minute position
    window["event_minute"] = (
        window.index - event_idx
    )

    event_windows.append(window)

event_windows = pd.concat(
    event_windows,
    ignore_index=True
)

print("Event-window rows:", len(event_windows))
print("Unique events:", event_windows["event_id"].nunique())

print("\nEvent-minute range:")
print(
    event_windows["event_minute"].min(),
    "to",
    event_windows["event_minute"].max()
)

Event-window rows: 154208
Unique events: 2528

Event-minute range:
-30 to 30

In [102]:
print("Events:", len(events))

print("\nEvents with missing event_time_correct:")
print(events["event_time_correct"].isna().sum())

print("\nEvents with missing event_index:")
print(events["event_index"].isna().sum())

Events: 2528

Events with missing event_time_correct:
0

Events with missing event_index:
0

In [103]:
for name in list(globals().keys()):
    try:
        obj = globals()[name]

        if hasattr(obj, "columns"):
            cols = set(obj.columns)

            required = {"date", "open", "high", "low", "close", "volume"}

            if required.issubset(cols):
                print(name, "->", obj.shape)
    except:
        pass

reliance -> (277510, 7)
df -> (277510, 7)
zero_volume -> (187, 7)
future_bars -> (276385, 7)
stock_df -> (277509, 7)
df_stock -> (277510, 9)
event_windows -> (154208, 13)
prices -> (277509, 9)
window -> (61, 13)

In [104]:
import os

for root, dirs, files in os.walk(".", topdown=True):
    for file in files:
        if "nifty" in file.lower():
            print(os.path.join(root, file))

In [105]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        print(os.path.join(root, file))

.\01_data_validation.ipynb
.\Corporate_Announcement_Event_Study_FINAL.ipynb
.\.ipynb_checkpoints\01_data_validation-checkpoint.ipynb
.\.ipynb_checkpoints\Corporate_Announcement_Event_Study_FINAL-checkpoint.ipynb
.\data\corporate_announcements.csv
.\data\corporate_announcements.jsonl
.\data\HAL.csv
.\data\HDFCBANK.csv
.\data\metadata.json
.\data\NYKAA.csv
.\data\RELIANCE.csv
.\data\RVNL.csv
.\data\.ipynb_checkpoints\corporate_announcements-checkpoint.csv

In [106]:
import os

files_found = []

for root, dirs, files in os.walk("."):
    for file in files:
        if file.lower().endswith((".csv", ".xlsx", ".xls", ".parquet", ".zip")):
            files_found.append(os.path.join(root, file))

print("\n".join(files_found))

.\data\corporate_announcements.csv
.\data\HAL.csv
.\data\HDFCBANK.csv
.\data\NYKAA.csv
.\data\RELIANCE.csv
.\data\RVNL.csv
.\data\.ipynb_checkpoints\corporate_announcements-checkpoint.csv

In [107]:
print(reliance.head())
print("\nColumns:")
print(reliance.columns.tolist())

print("\nDate range:")
print(reliance["date"].min())
print(reliance["date"].max())

                 date    open    high     low   close    volume  oi
0 2023-08-21 09:15:00  1270.0  1274.5  1267.5  1271.5  298148.0   0
1 2023-08-21 09:16:00  1271.4  1271.5  1268.2  1270.0   91462.0   0
2 2023-08-21 09:17:00  1270.1  1274.5  1269.7  1274.0   87564.0   0
3 2023-08-21 09:18:00  1274.0  1277.7  1274.0  1277.0  125296.0   0
4 2023-08-21 09:19:00  1277.0  1277.3  1274.0  1274.5   53530.0   0

Columns:
['date', 'open', 'high', 'low', 'close', 'volume', 'oi']

Date range:
2023-08-21 09:15:00
2026-08-19 15:29:00

In [108]:
print("Checking current notebook state...")

print("announcements:", len(announcements) if "announcements" in globals() else "MISSING")
print("aligned_events:", len(aligned_events) if "aligned_events" in globals() else "MISSING")
print("daily_counts:", len(daily_counts) if "daily_counts" in globals() else "MISSING")
print("stocks:", list(stocks.keys()) if "stocks" in globals() else "MISSING")
print("events:", len(events) if "events" in globals() else "MISSING")
print("event_windows:", len(event_windows) if "event_windows" in globals() else "MISSING")

Checking current notebook state...
announcements: 2530
aligned_events: 2530
daily_counts: 1515
stocks: ['RELIANCE', 'HDFCBANK', 'NYKAA', 'RVNL', 'HAL']
events: 2528
event_windows: 154208

In [109]:
print(ann.shape)
print(ann.columns.tolist())

(2530, 31)
['NEWSID', 'SCRIP_CD', 'XML_NAME', 'NEWSSUB', 'DT_TM', 'NEWS_DT', 'CRITICALNEWS', 'ANNOUNCEMENT_TYPE', 'QUARTER_ID', 'FILESTATUS', 'ATTACHMENTNAME', 'MORE', 'HEADLINE', 'CATEGORYNAME', 'OLD', 'RN', 'PDFFLAG', 'NSURL', 'SLONGNAME', 'AGENDA_ID', 'News_submission_dt', 'DissemDT', 'TimeDiff', 'Fld_Attachsize', 'SUBCATNAME', 'BSENewsid', 'Investor_Presentation', 'AUDIO_VIDEO_FILE', 'ticker', 'market_timing', 'event_time_correct']

In [110]:
# Keep only successfully aligned announcements
events = ann[ann["event_time_correct"].notna()].copy()

print("Total events:", len(events))
print("Unaligned/excluded:", ann["event_time_correct"].isna().sum())

Total events: 2528
Unaligned/excluded: 2

In [111]:
def get_event_index(row):
    ticker = row["ticker"]
    event_time = row["event_time_correct"]

    prices = stocks[ticker]

    matches = prices.index[prices["date"] == event_time]

    if len(matches) == 0:
        return pd.NA

    return matches[0]

events["event_index"] = events.apply(get_event_index, axis=1)

print("Events:", len(events))
print("Valid event indexes:", events["event_index"].notna().sum())

Events: 2528
Valid event indexes: 2528

In [112]:
event_windows = []

for _, event in events.iterrows():

    ticker = event["ticker"]
    event_idx = int(event["event_index"])

    prices = stocks[ticker]

    start_idx = event_idx - 30
    end_idx = event_idx + 30

    if start_idx < 0 or end_idx >= len(prices):
        continue

    window = prices.iloc[start_idx:end_idx + 1].copy()

    window["ticker"] = ticker
    window["event_id"] = event.name
    window["event_time"] = event["event_time_correct"]

    window["event_minute"] = (
        window.index - event_idx
    )

    event_windows.append(window)

event_windows = pd.concat(
    event_windows,
    ignore_index=True
)

print("Event-window rows:", len(event_windows))
print("Unique events:", event_windows["event_id"].nunique())

print("\nEvent-minute range:")
print(
    event_windows["event_minute"].min(),
    "to",
    event_windows["event_minute"].max()
)

Event-window rows: 154208
Unique events: 2528

Event-minute range:
-30 to 30

In [113]:
print("event_windows exists:", "event_windows" in globals())

if "event_windows" in globals():
    print("Rows:", len(event_windows))
    print("Columns:", event_windows.columns.tolist())

event_windows exists: True
Rows: 154208
Columns: ['date', 'open', 'high', 'low', 'close', 'volume', 'oi', 'return', 'bar_index', 'ticker', 'event_id', 'event_time', 'event_minute']

In [114]:
print("event_windows exists:", "event_windows" in globals())

event_windows exists: True

In [115]:
print("Kernel is working")

Kernel is working

In [116]:
print("event_windows exists:", "event_windows" in globals())

if "event_windows" in globals():
    print("Rows:", len(event_windows))
    print("Unique events:", event_windows["event_id"].nunique())

event_windows exists: True
Rows: 154208
Unique events: 2528

In [117]:
print("events:", len(events))
print("stocks:", list(stocks.keys()))

events: 2528
stocks: ['RELIANCE', 'HDFCBANK', 'NYKAA', 'RVNL', 'HAL']

In [118]:
event_windows_list = []

for ticker, group in events.groupby("ticker"):
    prices = stocks[ticker]

    for event_id, event in group.iterrows():
        event_idx = int(event["event_index"])

        start_idx = event_idx - 30
        end_idx = event_idx + 30

        if start_idx < 0 or end_idx >= len(prices):
            continue

        window = prices.iloc[start_idx:end_idx + 1].copy()

        window["ticker"] = ticker
        window["event_id"] = event_id
        window["event_time"] = event["event_time_correct"]
        window["event_minute"] = range(-30, 31)

        event_windows_list.append(window)

event_windows = pd.concat(
    event_windows_list,
    ignore_index=True
)

print("Event-window rows:", len(event_windows))
print("Unique events:", event_windows["event_id"].nunique())

print("\nEvent-minute range:")
print(
    event_windows["event_minute"].min(),
    "to",
    event_windows["event_minute"].max()
)

Event-window rows: 154208
Unique events: 2528

Event-minute range:
-30 to 30

In [119]:
print("=== FINAL NOTEBOOK STATE ===")

for name in [
    "event_windows",
    "stock_data",
    "daily_counts",
    "duplicate_counts",
    "events",
    "ann"
]:
    if name in globals():
        obj = globals()[name]
        print(f"{name}: {type(obj).__name__}", end="")
        if hasattr(obj, "shape"):
            print(f" | shape={obj.shape}")
        else:
            print()
    else:
        print(f"{name}: MISSING")

=== FINAL NOTEBOOK STATE ===
event_windows: DataFrame | shape=(154208, 13)
stock_data: dict
daily_counts: DataFrame | shape=(1515, 3)
duplicate_counts: DataFrame | shape=(1743, 3)
events: DataFrame | shape=(2528, 32)
ann: DataFrame | shape=(2530, 31)

In [120]:
# Show DataFrames currently available in memory
print("DataFrames currently available:\n")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"{name:30} {obj.shape}")

DataFrames currently available:

announcements                  (2530, 29)
_11                            (5, 28)
duplicate_ids                  (0, 28)
_16                            (0, 5)
invalid_timestamps             (11, 28)
raw_announcements              (2530, 28)
invalid                        (11, 30)
different                      (24, 28)
reliance                       (277510, 7)
df                             (277510, 7)
gaps                           (747, 3)
zero_volume                    (187, 7)
events                         (2528, 32)
future_bars                    (276385, 7)
aligned_events                 (2530, 10)
stock_df                       (277509, 7)
duplicate_events               (1227, 10)
duplicate_counts               (1743, 3)
obj                            (2530, 31)
daily_counts                   (1515, 3)
ann                            (2530, 31)
df_stock                       (277510, 9)
event_windows                  (154208, 13)
prices                         (277509, 9)
window                         (61, 13)
group                          (464, 32)

In [121]:
print("event_windows columns:")
print(event_windows.columns.tolist())

print("\nSample:")
display(event_windows.head())

print("\nEvents columns:")
print(events.columns.tolist())

event_windows columns:
['date', 'open', 'high', 'low', 'close', 'volume', 'oi', 'return', 'bar_index', 'ticker', 'event_id', 'event_time', 'event_minute']

Sample:

,date,open,high,low,close,volume,oi,return,bar_index,ticker,event_id,event_time,event_minute
0,2026-08-12 13:38:00,4888.0,4889.0,4888.0,4888.0,1875.0,0,-0.000020,275523,HAL,15,2026-08-12 14:08:00,-30
1,2026-08-12 13:39:00,4889.0,4890.0,4889.0,4889.1,849.0,0,0.000225,275524,HAL,15,2026-08-12 14:08:00,-29
2,2026-08-12 13:40:00,4889.2,4890.0,4889.0,4889.0,669.0,0,-0.000020,275525,HAL,15,2026-08-12 14:08:00,-28
3,2026-08-12 13:41:00,4889.0,4889.0,4882.2,4882.2,7121.0,0,-0.001391,275526,HAL,15,2026-08-12 14:08:00,-27
4,2026-08-12 13:42:00,4883.8,4884.0,4882.2,4882.2,172.0,0,0.000000,275527,HAL,15,2026-08-12 14:08:00,-26

Events columns:
['NEWSID', 'SCRIP_CD', 'XML_NAME', 'NEWSSUB', 'DT_TM', 'NEWS_DT', 'CRITICALNEWS', 'ANNOUNCEMENT_TYPE', 'QUARTER_ID', 'FILESTATUS', 'ATTACHMENTNAME', 'MORE', 'HEADLINE', 'CATEGORYNAME', 'OLD', 'RN', 'PDFFLAG', 'NSURL', 'SLONGNAME', 'AGENDA_ID', 'News_submission_dt', 'DissemDT', 'TimeDiff', 'Fld_Attachsize', 'SUBCATNAME', 'BSENewsid', 'Investor_Presentation', 'AUDIO_VIDEO_FILE', 'ticker', 'market_timing', 'event_time_correct', 'event_index']

In [122]:
# Calculate cumulative return from the event minute onward
event_returns = (
    event_windows
    .sort_values(["event_id", "event_minute"])
    .groupby("event_id")
    .apply(
        lambda x: pd.Series({
            "ticker": x["ticker"].iloc[0],
            "event_time": x["event_time"].iloc[0],

            # Return over first 5 minutes: 0 -> +5
            "return_5m": (
                (x.loc[x["event_minute"].between(0, 5), "return"] + 1).prod() - 1
            ),

            # Return over first 30 minutes: 0 -> +30
            "return_30m": (
                (x.loc[x["event_minute"].between(0, 30), "return"] + 1).prod() - 1
            ),

            # Return over available 60-minute window
            "return_60m": (
                (x.loc[x["event_minute"].between(0, 60), "return"] + 1).prod() - 1
            ),
        })
    )
    .reset_index()
)

print("Event return table:", event_returns.shape)
display(event_returns.head())

Event return table: (2528, 6)

   event_id    ticker          event_time  return_5m  return_30m  return_60m
0         2  RELIANCE 2026-08-19 09:15:00  -0.003555   -0.004236   -0.004236
1         3  RELIANCE 2026-08-19 09:15:00  -0.003555   -0.004236   -0.004236
2         4      RVNL 2026-08-18 14:25:00   0.000355    0.001197    0.001197
3         5  RELIANCE 2026-08-18 09:15:00  -0.001748    0.005775    0.005775
4         6  HDFCBANK 2026-08-17 09:15:00  -0.002201   -0.000963   -0.000963

In [123]:
event_windows_list = []

for ticker, group in events.groupby("ticker"):
    prices = stocks[ticker]

    for event_id, event in group.iterrows():

        event_idx = int(event["event_index"])

        # -30 to +60 minutes
        start_idx = event_idx - 30
        end_idx = event_idx + 60

        if start_idx < 0 or end_idx >= len(prices):
            continue

        window = prices.iloc[start_idx:end_idx + 1].copy()

        window["ticker"] = ticker
        window["event_id"] = event_id
        window["event_time"] = event["event_time_correct"]

        # Relative minute
        window["event_minute"] = range(-30, 61)

        event_windows_list.append(window)

event_windows = pd.concat(
    event_windows_list,
    ignore_index=True
)

print("Event-window rows:", len(event_windows))
print("Unique events:", event_windows["event_id"].nunique())

print("\nEvent-minute range:")
print(
    event_windows["event_minute"].min(),
    "to",
    event_windows["event_minute"].max()
)

Event-window rows: 230048
Unique events: 2528

Event-minute range:
-30 to 60

In [124]:
print(
    event_windows
    .groupby("event_id")["event_minute"]
    .agg(["min", "max", "count"])
    .describe()
)

          min     max   count
count  2528.0  2528.0  2528.0
mean    -30.0    60.0    91.0
std       0.0     0.0     0.0
min     -30.0    60.0    91.0
25%     -30.0    60.0    91.0
50%     -30.0    60.0    91.0
75%     -30.0    60.0    91.0
max     -30.0    60.0    91.0

In [125]:
event_returns = (
    event_windows
    .sort_values(["event_id", "event_minute"])
    .groupby("event_id")
    .apply(
        lambda x: pd.Series({
            "ticker": x["ticker"].iloc[0],
            "event_time": x["event_time"].iloc[0],

            "return_5m": (
                (1 + x.loc[
                    x["event_minute"].between(0, 5),
                    "return"
                ]).prod() - 1
            ),

            "return_30m": (
                (1 + x.loc[
                    x["event_minute"].between(0, 30),
                    "return"
                ]).prod() - 1
            ),

            "return_60m": (
                (1 + x.loc[
                    x["event_minute"].between(0, 60),
                    "return"
                ]).prod() - 1
            )
        })
    )
    .reset_index()
)

print("Event return table:", event_returns.shape)

display(event_returns.head())

Event return table: (2528, 6)

   event_id    ticker          event_time  return_5m  return_30m  return_60m
0         2  RELIANCE 2026-08-19 09:15:00  -0.003555   -0.004236   -0.006808
1         3  RELIANCE 2026-08-19 09:15:00  -0.003555   -0.004236   -0.006808
2         4      RVNL 2026-08-18 14:25:00   0.000355    0.001197   -0.000665
3         5  RELIANCE 2026-08-18 09:15:00  -0.001748    0.005775    0.005091
4         6  HDFCBANK 2026-08-17 09:15:00  -0.002201   -0.000963   -0.001307

In [126]:
print("Unique announcement subjects:", events["NEWSSUB"].nunique())

display(
    events["NEWSSUB"]
    .value_counts()
    .head(30)
)

Unique announcement subjects: 760

NEWSSUB
Compliances-Reg. 39 (3) - Details of Loss of Certificate / Duplicate Certificate                                                                    410
Announcement under Regulation 30 (LODR)-Analyst / Investor Meet - Intimation                                                                        193
Announcement under Regulation 30 (LODR)-Allotment of ESOP / ESPS                                                                                    102
Announcement under Regulation 30 (LODR)-Award_of_Order_Receipt_of_Order                                                                              75
Announcement under Regulation 30 (LODR)-Change in Management                                                                                         72
Announcement under Regulation 30 (LODR)-Newspaper Publication                                                                                        67
Announcement under Regulation 30 (LODR)-Press Release / Media Release                                                                                65
Announcement under Regulation 30 (LODR)-Analyst / Investor Meet - Outcome                                                                            62
Announcement under Regulation 30 (LODR)-Change in Directorate                                                                                        55
Closure of Trading Window                                                                                                                            47
Compliances-Certificate under Reg. 74 (5) of SEBI (DP) Regulations, 2018                                                                             41
Announcement under Regulation 30 (LODR)-Earnings Call Transcript                                                                                     40
Announcement under Regulation 30 (LODR)-Acquisition                                                                                                  37
Announcement under Regulation 30 (LODR)-Investor Presentation                                                                                        36
Disclosure Under Regulation 30 Of The Securities And Exchange Board Of India (Listing Obligations And Disclosure Requirements) Regulations, 2015     33
Announcement under Regulation 30 (LODR)-Credit Rating                                                                                                32
Update On Institutional Investors' Meeting                                                                                                           31
Intimation Under Regulation 30 Of The SEBI (Listing Obligations And Disclosure Requirements) Regulations, 2015                                       24
Reg. 34 (1) Annual Report.                                                                                                                           20
Business Responsibility and Sustainability Reporting (BRSR)                                                                                          19
Shareholder Meeting / Postal Ballot-Notice of Postal Ballot                                                                                          18
Intimation Under Regulation 30 Of SEBI (Listing Obligations And Disclosure Requirements) Regulations, 2015                                           18
Shareholder Meeting / Postal Ballot-Outcome of AGM                                                                                                   17
Update On Institutional Investors'' Meeting                                                                                                          17
General Updates                                                                                                                                      15
Shareholder Meeting / Postal Ballot-Outcome of Postal_Ballot                                                                                         14
Shareholder Meeting / Postal Ballot-Scrutinizer''s Report                                                                                            13
Compliances-Reg.24(A)-Annual Secretarial Compliance                                                                                                  13
Announcement under Regulation 30 (LODR)-Updates on Acquisition                                                                                       13
Announcement under Regulation 30 (LODR)-Allotment                                                                                                    13
Name: count, dtype: int64

In [127]:
display(
    events[
        ["NEWSSUB", "CATEGORYNAME", "SUBCATNAME", "HEADLINE"]
    ].head(20)
)

,NEWSSUB,CATEGORYNAME,SUBCATNAME,HEADLINE
2,Update On Institutional Investors'' Meeting - ...,Company Update,General,This is further to the disclosure dated August...
3,"News Clarification - ""SC Slaps Rs 10 Lakh Fine...",Company Update,General,"Please refer our letter dated August 18, 2026 ..."
4,Announcement under Regulation 30 (LODR)-Earnin...,Company Update,Earnings Call Transcript,Transcript of Conference Call with Investors
5,Clarification sought from Reliance Industries Ltd,Company Update,Clarification,The Exchange has sought clarification from Rel...
6,Announcement under Regulation 30 (LODR)-Analys...,Company Update,Analyst / Investor Meet,Intimation of Schedule of Analyst / Institutio...
7,Announcement under Regulation 30 (LODR)-Change...,Company Update,Change in Directorate,Appointment of Shri Rakesh Bhalla (DIN: 070201...
8,Media Release - 'Reliance Industries And Rolls...,Company Update,General,Please find attached a media release by the Co...
9,Announcement under Regulation 30 (LODR)-Allotm...,Company Update,Allotment of ESOP / ESPS,Allotment of 1729212 equity shares pursuant to...
10,Announcement under Regulation 30 (LODR)-Analys...,Company Update,Analyst / Investor Meet,Please note that the Company executives will b...
11,Announcement under Regulation 30 (LODR)-Analys...,Company Update,Analyst / Investor Meet,"Dear Sir/Madam, \r\n????? ?????/??????,\r\n\r\..."
12,Announcement under Regulation 30 (LODR)-Analys...,Company Update,Analyst / Investor Meet,Intimation of Schedule of Analyst / Institutio...
13,Update On Institutional Investors'' Meeting - ...,Company Update,General,This is further to the Disclosure dated August...
14,"Redemption Of Unlisted, Unsecured, Unrated, Re...",Company Update,General,"Redemption of Unlisted, Unsecured, Unrated, Re..."
15,Financial Result For The Quarter Ended 30.06.2026,Result,Financial Results,Announcement as attached
16,Unaudited Financial Results (Standalone & Cons...,Result,Financial Results,Unaudited Financial Results (Standalone & Cons...
17,Board Meeting Outcome for Unaudited Financial ...,Board Meeting,Outcome of Board Meeting,Unaudited Financial Results (Standalone and Co...
18,Announcement under Regulation 30 (LODR)-Allotm...,Company Update,Allotment of ESOP / ESPS,"Allotment of 2,26,200 Equity shares pursuant t..."
19,Announcement under Regulation 30 (LODR)-Earnin...,Company Update,Earnings Call Transcript,Please find enclosed herewith the Transcript o...
20,Newspaper Clippings - Special Window For Trans...,Company Update,General,The newspaper clippings of the advertisement o...
21,Announcement under Regulation 30 (LODR)-Analys...,Company Update,Analyst / Investor Meet,Please note that the Company executives will b...

In [128]:
# Create a practical announcement subject taxonomy

def classify_subject(row):
    text = " ".join([
        str(row.get("NEWSSUB", "")),
        str(row.get("SUBCATNAME", "")),
        str(row.get("HEADLINE", "")),
        str(row.get("CATEGORYNAME", ""))
    ]).lower()

    # 1. Financial Results
    if any(keyword in text for keyword in [
        "financial result",
        "financial results",
        "quarter ended",
        "unaudited financial",
        "audited financial",
        "earnings"
    ]):
        return "Financial Results"

    # 2. Analyst / Investor Communication
    elif any(keyword in text for keyword in [
        "analyst / investor meet",
        "analyst meet",
        "investor meet",
        "institutional investors",
        "earnings call",
        "conference call",
        "investor presentation"
    ]):
        return "Analyst / Investor Communication"

    # 3. Corporate Governance / Management
    elif any(keyword in text for keyword in [
        "change in directorate",
        "appointment",
        "resignation",
        "retirement",
        "board meeting",
        "board of directors",
        "key managerial",
        "management"
    ]):
        return "Corporate Governance / Management"

    # 4. Capital Actions
    elif any(keyword in text for keyword in [
        "allotment",
        "esop",
        "esps",
        "buyback",
        "redemption",
        "bonus",
        "dividend",
        "rights issue",
        "preferential issue",
        "fund raising",
        "equity shares"
    ]):
        return "Capital Actions"

    # 5. Regulatory / Legal / Clarification
    elif any(keyword in text for keyword in [
        "clarification",
        "clarification sought",
        "regulation",
        "legal",
        "court",
        "fine",
        "order",
        "sebi",
        "exchange"
    ]):
        return "Regulatory / Legal / Clarification"

    # 6. Business / Strategic / Media
    elif any(keyword in text for keyword in [
        "media release",
        "acquisition",
        "merger",
        "agreement",
        "partnership",
        "contract",
        "order received",
        "business update",
        "project",
        "expansion"
    ]):
        return "Business / Strategic / Media"

    # 7. Everything else
    else:
        return "Other Corporate Updates"


events["subject_group"] = events.apply(classify_subject, axis=1)

print("Subject groups:")
print(
    events["subject_group"]
    .value_counts()
)

print("\nNumber of subject groups:",
      events["subject_group"].nunique())

Subject groups:
subject_group
Other Corporate Updates               850
Regulatory / Legal / Clarification    556
Financial Results                     352
Analyst / Investor Communication      298
Corporate Governance / Management     235
Capital Actions                       187
Business / Strategic / Media           50
Name: count, dtype: int64

Number of subject groups: 7

In [129]:
subject_counts = (
    events
    .groupby("subject_group")
    .agg(
        announcements=("NEWSID", "count"),
        stocks=("ticker", "nunique")
    )
    .sort_values("announcements", ascending=False)
)

subject_counts["statistical_status"] = subject_counts["announcements"].apply(
    lambda x: "Conclusive candidate" if x >= 10 else "Descriptive only"
)

display(subject_counts)

,announcements,stocks,statistical_status
subject_group,,,
Other Corporate Updates,850,5,Conclusive candidate
Regulatory / Legal / Clarification,556,5,Conclusive candidate
Financial Results,352,5,Conclusive candidate
Analyst / Investor Communication,298,5,Conclusive candidate
Corporate Governance / Management,235,5,Conclusive candidate
Capital Actions,187,5,Conclusive candidate
Business / Strategic / Media,50,4,Conclusive candidate

In [132]:
print("duplicate_events shape:", duplicate_events.shape)

print("\nColumns available:")
print(duplicate_events.columns.tolist())

display(
    duplicate_events[
        [
            "ticker",
            "DissemDT",
            "event_time",
            "NEWSID",
            "HEADLINE"
        ]
    ].head(20)
)

duplicate_events shape: (1227, 10)

Columns available:
['NEWSID', 'SCRIP_CD', 'ticker', 'DissemDT', 'event_time', 'event_close', 'HEADLINE', 'CATEGORYNAME', 'SUBCATNAME', 'alignment_delay_seconds']

,ticker,DissemDT,event_time,NEWSID,HEADLINE
3,HAL,2023-09-01 16:15:05.740,2023-09-04 09:15:00,31cec2fa-69f9-4098-961d-c9845b8917bd,Details of Voting Results and Report of the Sc...
4,HAL,2023-09-01 17:01:27.883,2023-09-04 09:15:00,1dc927a7-73bf-490f-be65-3a36e7119b6a,Announcement attached
5,HAL,2023-09-01 17:02:53.890,2023-09-04 09:15:00,6e4f0ba2-3234-4376-99c8-779b8c494450,Announcement attached
6,HAL,2023-09-01 17:06:56.487,2023-09-04 09:15:00,e71b6c61-387e-45fd-a140-64bfee494ec3,Shareholders has approved sub-division of Equi...
7,HAL,2023-09-01 17:09:24.247,2023-09-04 09:15:00,02f95dcd-6657-49c6-9f86-a69bdf9ca5e6,Announcement attached
31,HAL,2024-02-01 09:02:32.033,2024-02-01 09:15:00,2ea42db2-fd30-42f5-bf0b-f2b587403ea2,announcement attached
32,HAL,2024-02-01 09:14:21.697,2024-02-01 09:15:00,d2a78992-0c11-4136-91f7-99884bbc5490,Hindustan Aeronautics Ltdhas informed BSE that...
47,HAL,2024-03-22 17:40:26.457,2024-03-26 09:15:00,98f25a40-7052-42b4-9102-72041a6119c7,Announcement as attached
48,HAL,2024-03-25 14:37:58.517,2024-03-26 09:15:00,66cbfc62-f50d-4dec-aeed-5fe3e28af179,announcement is attached
69,HAL,2024-06-05 16:07:06.327,2024-06-06 09:15:00,f1a373f3-4f31-442d-996e-1fb762b078cd,announcement attached
70,HAL,2024-06-05 16:10:43.087,2024-06-06 09:15:00,6f6d858f-e968-452b-ab2c-83a28d49bfbe,announcement is attached
72,HAL,2024-06-17 15:06:56.513,2024-06-18 09:15:00,5c866858-6cff-47bb-9488-3cfc41c7a2c3,announcement attached
73,HAL,2024-06-17 15:09:57.483,2024-06-18 09:15:00,50c6e991-da79-4baf-b931-d73b6fdec67b,announcement is attached
102,HAL,2024-08-31 12:59:16.427,2024-09-02 09:15:00,fb4e7ae7-260d-4d8d-9c00-438443bf36a0,Announcement is attached
103,HAL,2024-08-31 16:27:45.800,2024-09-02 09:15:00,c13c78f6-d451-4374-8956-f30002964691,announcement is attached
107,HAL,2024-09-09 16:33:12.170,2024-09-10 09:15:00,10f66c8a-b804-4cae-965d-81f612feb7d2,announcement is attached
108,HAL,2024-09-09 17:16:13.580,2024-09-10 09:15:00,4a708f9e-b4d7-4794-8e39-ca296c2ce682,Announcement is attached
117,HAL,2024-10-22 16:51:44.140,2024-10-23 09:15:00,84e10be5-0789-4193-a141-c421e93246d8,Announcement attached
118,HAL,2024-10-22 17:13:28.450,2024-10-23 09:15:00,4f8997ad-32bf-4742-b068-1109d7bdd93b,announcement is attached
132,HAL,2024-12-27 16:39:07.627,2024-12-30 09:15:00,1cd6d935-0459-4ea6-9804-4eadd4b4a196,Announcement attached

In [133]:
print(duplicate_events.columns.tolist())

['NEWSID', 'SCRIP_CD', 'ticker', 'DissemDT', 'event_time', 'event_close', 'HEADLINE', 'CATEGORYNAME', 'SUBCATNAME', 'alignment_delay_seconds']

In [134]:
display(duplicate_events.head(10))

,NEWSID,SCRIP_CD,ticker,DissemDT,event_time,event_close,HEADLINE,CATEGORYNAME,SUBCATNAME,alignment_delay_seconds
3,31cec2fa-69f9-4098-961d-c9845b8917bd,541154,HAL,2023-09-01 16:15:05.740,2023-09-04 09:15:00,1982.1,Details of Voting Results and Report of the Sc...,AGM/EGM,AGM,233994.260
4,1dc927a7-73bf-490f-be65-3a36e7119b6a,541154,HAL,2023-09-01 17:01:27.883,2023-09-04 09:15:00,1982.1,Announcement attached,Company Update,General,231212.117
5,6e4f0ba2-3234-4376-99c8-779b8c494450,541154,HAL,2023-09-01 17:02:53.890,2023-09-04 09:15:00,1982.1,Announcement attached,Company Update,Amendments to Memorandum & Articles of Associa...,231126.110
6,e71b6c61-387e-45fd-a140-64bfee494ec3,541154,HAL,2023-09-01 17:06:56.487,2023-09-04 09:15:00,1982.1,Shareholders has approved sub-division of Equi...,Corp. Action,Sub-division / Stock Split,230883.513
7,02f95dcd-6657-49c6-9f86-a69bdf9ca5e6,541154,HAL,2023-09-01 17:09:24.247,2023-09-04 09:15:00,1982.1,Announcement attached,Corp. Action,Record Date,230735.753
31,2ea42db2-fd30-42f5-bf0b-f2b587403ea2,541154,HAL,2024-02-01 09:02:32.033,2024-02-01 09:15:00,3021.8,announcement attached,Company Update,General,747.967
32,d2a78992-0c11-4136-91f7-99884bbc5490,541154,HAL,2024-02-01 09:14:21.697,2024-02-01 09:15:00,3021.8,Hindustan Aeronautics Ltdhas informed BSE that...,Board Meeting,Board Meeting,38.303
47,98f25a40-7052-42b4-9102-72041a6119c7,541154,HAL,2024-03-22 17:40:26.457,2024-03-26 09:15:00,3197.7,Announcement as attached,Company Update,Award of Order / Receipt of Order,315273.543
48,66cbfc62-f50d-4dec-aeed-5fe3e28af179,541154,HAL,2024-03-25 14:37:58.517,2024-03-26 09:15:00,3197.7,announcement is attached,Company Update,General,67021.483
69,f1a373f3-4f31-442d-996e-1fb762b078cd,541154,HAL,2024-06-05 16:07:06.327,2024-06-06 09:15:00,4541.4,announcement attached,Company Update,Press Release / Media Release,61673.673

In [135]:
# Create event clusters based on stock + effective market time

events_clustered = events.copy()

events_clustered["event_cluster"] = (
    events_clustered
    .groupby(["ticker", "event_time_correct"])
    .ngroup()
)

# Size of each cluster
events_clustered["cluster_size"] = (
    events_clustered
    .groupby("event_cluster")["NEWSID"]
    .transform("size")
)

print("Total announcements:", len(events_clustered))
print("Unique event clusters:",
      events_clustered["event_cluster"].nunique())

print("\nCluster-size distribution:")
print(
    events_clustered["cluster_size"]
    .value_counts()
    .sort_index()
    .head(20)
)

Total announcements: 2528
Unique event clusters: 1743

Cluster-size distribution:
cluster_size
1    1303
2     568
3     228
4     120
5     105
6      54
7      84
8      48
9      18
Name: count, dtype: int64

In [136]:
# Keep the earliest dissemination announcement within each cluster
independent_events = (
    events_clustered
    .sort_values(["ticker", "event_time_correct", "DissemDT"])
    .drop_duplicates(
        subset=["ticker", "event_time_correct"],
        keep="first"
    )
    .copy()
)

print("Independent events:", len(independent_events))
print("Removed as overlapping/clustered:",
      len(events_clustered) - len(independent_events))

print("\nCluster size:")
print(
    independent_events["cluster_size"]
    .value_counts()
    .sort_index()
)

Independent events: 1743
Removed as overlapping/clustered: 785

Cluster size:
cluster_size
1    1303
2     284
3      76
4      30
5      21
6       9
7      12
8       6
9       2
Name: count, dtype: int64

In [145]:
# Make event_id datatype consistent before merging

event_returns["event_id"] = event_returns["event_id"].astype(str)
independent_events["event_id"] = independent_events["event_id"].astype(str)

# Attach subject taxonomy and cluster information to event returns

event_results = event_returns.merge(
    independent_events[
        [
            "NEWSID",
            "event_id",
            "subject_group",
            "event_cluster",
            "cluster_size"
        ]
    ],
    on="event_id",
    how="left"
)

print("event_results shape:", event_results.shape)
display(event_results.head())

KeyError: 'event_id'

In [ ]:
# Preserve the original events DataFrame index as event_id
independent_events = independent_events.copy()
independent_events["event_id"] = independent_events.index

# Merge the return calculations with the independent-event information
event_results = event_returns.merge(
    independent_events[
        [
            "event_id",
            "NEWSID",
            "ticker",
            "DissemDT",
            "event_time_correct",
            "subject_group",
            "event_cluster",
            "cluster_size"
        ]
    ],
    on=["event_id", "ticker"],
    how="inner"
)

print("Independent event results:", event_results.shape)

display(
    event_results[
        [
            "event_id",
            "ticker",
            "event_time",
            "subject_group",
            "event_cluster",
            "cluster_size",
            "return_5m",
            "return_30m",
            "return_60m"
        ]
    ].head(10)
)

In [ ]:
subject_price_summary = (
    event_results
    .groupby("subject_group")
    .agg(
        n_events=("event_id", "count"),

        mean_5m=("return_5m", "mean"),
        median_5m=("return_5m", "median"),

        mean_30m=("return_30m", "mean"),
        median_30m=("return_30m", "median"),

        mean_60m=("return_60m", "mean"),
        median_60m=("return_60m", "median")
    )
    .sort_values("n_events", ascending=False)
)

display(subject_price_summary)

In [138]:
for horizon in ["5m", "30m", "60m"]:
    event_results[f"direction_{horizon}"] = (
        event_results[f"return_{horizon}"] > 0
    )

direction_summary = (
    event_results
    .groupby("subject_group")
    .agg(
        positive_5m=("direction_5m", "mean"),
        positive_30m=("direction_30m", "mean"),
        positive_60m=("direction_60m", "mean")
    )
)

direction_summary = direction_summary * 100

direction_summary.columns = [
    "positive_5m_pct",
    "positive_30m_pct",
    "positive_60m_pct"
]

display(direction_summary)

NameError: name 'event_results' is not defined

In [ ]:
display(
    subject_price_summary.style.format({
        "mean_5m": "{:.4%}",
        "median_5m": "{:.4%}",
        "mean_30m": "{:.4%}",
        "median_30m": "{:.4%}",
        "mean_60m": "{:.4%}",
        "median_60m": "{:.4%}"
    })
)

# 6. Independent Event Selection

In [ ]:
# Standard deviation and standard error by subject
subject_uncertainty = (
    event_results
    .groupby("subject_group")
    .agg(
        n_events=("event_id", "count"),

        mean_5m=("return_5m", "mean"),
        std_5m=("return_5m", "std"),

        mean_30m=("return_30m", "mean"),
        std_30m=("return_30m", "std"),

        mean_60m=("return_60m", "mean"),
        std_60m=("return_60m", "std")
    )
)

for horizon in ["5m", "30m", "60m"]:
    subject_uncertainty[f"se_{horizon}"] = (
        subject_uncertainty[f"std_{horizon}"] /
        np.sqrt(subject_uncertainty["n_events"])
    )

display(subject_uncertainty)

# 8. Statistical Significance Testing

In [ ]:
from scipy import stats

significance_results = []

for subject, group in event_results.groupby("subject_group"):

    for horizon in ["5m", "30m", "60m"]:

        values = group[f"return_{horizon}"].dropna()

        t_stat, p_value = stats.ttest_1samp(values, 0)

        mean_return = values.mean()
        std_return = values.std(ddof=1)
        n = len(values)

        se = std_return / np.sqrt(n)

        # 95% confidence interval
        ci_low = mean_return - stats.t.ppf(0.975, n - 1) * se
        ci_high = mean_return + stats.t.ppf(0.975, n - 1) * se

        significance_results.append({
            "subject_group": subject,
            "horizon": horizon,
            "n": n,
            "mean_return": mean_return,
            "t_stat": t_stat,
            "p_value": p_value,
            "ci_low": ci_low,
            "ci_high": ci_high
        })

significance_results = pd.DataFrame(significance_results)

display(
    significance_results.sort_values(
        ["horizon", "p_value"]
    )
)

In [ ]:
%pip install scipy

In [ ]:
import scipy
print(scipy.__version__)

# 7. Stock Return Analysis

In [ ]:
from scipy import stats

significance_results = []

for subject, group in event_results.groupby("subject_group"):

    for horizon in ["5m", "30m", "60m"]:

        values = group[f"return_{horizon}"].dropna()

        t_stat, p_value = stats.ttest_1samp(values, 0)

        mean_return = values.mean()
        std_return = values.std(ddof=1)
        n = len(values)

        se = std_return / np.sqrt(n)

        ci_low = mean_return - stats.t.ppf(0.975, n - 1) * se
        ci_high = mean_return + stats.t.ppf(0.975, n - 1) * se

        significance_results.append({
            "subject_group": subject,
            "horizon": horizon,
            "n": n,
            "mean_return": mean_return,
            "t_stat": t_stat,
            "p_value": p_value,
            "ci_low": ci_low,
            "ci_high": ci_high
        })

significance_results = pd.DataFrame(significance_results)

display(
    significance_results.sort_values(
        ["horizon", "p_value"]
    )
)

In [139]:
display(
    significance_results.style.format({
        "mean_return": "{:.4%}",
        "t_stat": "{:.3f}",
        "p_value": "{:.4f}",
        "ci_low": "{:.4%}",
        "ci_high": "{:.4%}"
    })
)

NameError: name 'significance_results' is not defined

# 10. Multiple Testing Correction

In [ ]:
from statsmodels.stats.multitest import multipletests

significance_results["p_value_adj"] = multipletests(
    significance_results["p_value"],
    method="fdr_bh"
)[1]

significance_results["significant_5pct"] = (
    significance_results["p_value_adj"] < 0.05
)

display(
    significance_results.sort_values(
        ["p_value_adj", "horizon"]
    ).style.format({
        "mean_return": "{:.4%}",
        "t_stat": "{:.3f}",
        "p_value": "{:.4f}",
        "p_value_adj": "{:.4f}",
        "ci_low": "{:.4%}",
        "ci_high": "{:.4%}"
    })
)

In [ ]:
import numpy as np
import pandas as pd

# Benjamini-Hochberg FDR correction
p = significance_results["p_value"].to_numpy()
m = len(p)

# Sort p-values
order = np.argsort(p)
sorted_p = p[order]

# BH adjusted p-values
adjusted = sorted_p * m / np.arange(1, m + 1)

# Ensure adjusted p-values are monotonic
adjusted = np.minimum.accumulate(adjusted[::-1])[::-1]

# Put them back in original order
p_adj = np.empty(m)
p_adj[order] = np.minimum(adjusted, 1.0)

significance_results["p_value_adj"] = p_adj

# Significant after FDR correction
significance_results["significant_5pct"] = (
    significance_results["p_value_adj"] < 0.05
)

display(
    significance_results
    .sort_values(["p_value_adj", "horizon"])
    .style.format({
        "mean_return": "{:.4%}",
        "t_stat": "{:.3f}",
        "p_value": "{:.4f}",
        "p_value_adj": "{:.4f}",
        "ci_low": "{:.4%}",
        "ci_high": "{:.4%}"
    })
)

# 8. Statistical Significance Testing

In [ ]:
print(event_windows.columns.tolist())

print("\nEvent windows:")
display(
    event_windows[
        ["ticker", "event_id", "event_minute", "volume"]
    ].head(20)
)

In [ ]:
print("Event minute range:")
print(event_windows["event_minute"].min(),
      event_windows["event_minute"].max())

print("\nRows per event:")
rows_per_event = event_windows.groupby("event_id").size()

print(rows_per_event.describe())

print("\nEvents with missing event minute 0:")
events_without_zero = (
    event_windows.groupby("event_id")["event_minute"]
    .apply(lambda x: 0 not in set(x))
)

print(events_without_zero.sum())

In [ ]:
# Calculate normal volume from the pre-event baseline
baseline_volume = (
    event_windows[
        event_windows["event_minute"].between(-30, -5)
    ]
    .groupby("event_id")["volume"]
    .mean()
    .rename("baseline_volume")
)

# Add baseline volume to every event-window row
event_windows = event_windows.merge(
    baseline_volume,
    on="event_id",
    how="left"
)

# Abnormal volume ratio
event_windows["volume_ratio"] = (
    event_windows["volume"] / event_windows["baseline_volume"]
)

# Abnormal volume percentage
event_windows["abnormal_volume_pct"] = (
    event_windows["volume_ratio"] - 1
) * 100

display(
    event_windows[
        [
            "ticker",
            "event_id",
            "event_minute",
            "volume",
            "baseline_volume",
            "volume_ratio",
            "abnormal_volume_pct"
        ]
    ].head(20)
)

# 9. Trading Volume Analysis

In [ ]:
volume_impact = (
    event_windows[
        event_windows["event_minute"].isin([5, 30, 60])
    ]
    .groupby(["event_id", "ticker", "event_minute"])
    .agg(
        baseline_volume=("baseline_volume", "first"),
        event_volume=("volume", "first"),
        volume_ratio=("volume_ratio", "first"),
        abnormal_volume_pct=("abnormal_volume_pct", "first")
    )
    .reset_index()
)

display(volume_impact.head(15))

In [ ]:
# Keep one row per event with its subject classification
event_subjects = (
    event_results[
        ["event_id", "subject_group"]
    ]
    .drop_duplicates("event_id")
)

# Make sure merge keys have the same type
volume_impact["event_id"] = volume_impact["event_id"].astype(str)
event_subjects["event_id"] = event_subjects["event_id"].astype(str)

# Merge subject classification
volume_results = volume_impact.merge(
    event_subjects,
    on="event_id",
    how="left"
)

print("Volume results shape:", volume_results.shape)
print("Missing subject groups:", volume_results["subject_group"].isna().sum())

display(volume_results.head(10))

In [ ]:
# Get the event IDs that survived the clustering/independence filter
independent_event_ids = (
    event_results["event_id"]
    .astype(str)
    .unique()
)

# Keep only those events in volume data
volume_results = volume_impact[
    volume_impact["event_id"].astype(str).isin(independent_event_ids)
].copy()

# Attach subject group
event_subjects = (
    event_results[
        ["event_id", "subject_group"]
    ]
    .drop_duplicates("event_id")
    .copy()
)

volume_results["event_id"] = volume_results["event_id"].astype(str)
event_subjects["event_id"] = event_subjects["event_id"].astype(str)

volume_results = volume_results.merge(
    event_subjects,
    on="event_id",
    how="left"
)

print("Volume results shape:", volume_results.shape)
print(
    "Missing subject groups:",
    volume_results["subject_group"].isna().sum()
)

In [140]:
volume_summary = (
    volume_results
    .groupby(["subject_group", "event_minute"])
    .agg(
        n_events=("event_id", "nunique"),
        mean_volume_ratio=("volume_ratio", "mean"),
        median_volume_ratio=("volume_ratio", "median"),
        mean_abnormal_volume_pct=("abnormal_volume_pct", "mean"),
        median_abnormal_volume_pct=("abnormal_volume_pct", "median")
    )
    .reset_index()
)

display(
    volume_summary.style.format({
        "mean_volume_ratio": "{:.3f}",
        "median_volume_ratio": "{:.3f}",
        "mean_abnormal_volume_pct": "{:.2f}%",
        "median_abnormal_volume_pct": "{:.2f}%"
    })
)

NameError: name 'volume_results' is not defined

# 9. Trading Volume Analysis

In [ ]:
# Keep only the 1,743 independent events
independent_event_ids = (
    event_results["event_id"]
    .astype(str)
    .unique()
)

volume_results = volume_impact[
    volume_impact["event_id"].astype(str).isin(independent_event_ids)
].copy()

# Get subject group for each independent event
event_subjects = (
    event_results[
        ["event_id", "subject_group"]
    ]
    .drop_duplicates("event_id")
    .copy()
)

# Make event_id types consistent
volume_results["event_id"] = volume_results["event_id"].astype(str)
event_subjects["event_id"] = event_subjects["event_id"].astype(str)

# Merge subject groups
volume_results = volume_results.merge(
    event_subjects,
    on="event_id",
    how="left"
)

print("Volume results shape:", volume_results.shape)
print("Missing subject groups:",
      volume_results["subject_group"].isna().sum())

In [ ]:
volume_summary = (
    volume_results
    .groupby(["subject_group", "event_minute"])
    .agg(
        n_events=("event_id", "nunique"),
        mean_volume_ratio=("volume_ratio", "mean"),
        median_volume_ratio=("volume_ratio", "median"),
        mean_abnormal_volume_pct=("abnormal_volume_pct", "mean"),
        median_abnormal_volume_pct=("abnormal_volume_pct", "median")
    )
    .reset_index()
)

display(
    volume_summary.style.format({
        "mean_volume_ratio": "{:.3f}",
        "median_volume_ratio": "{:.3f}",
        "mean_abnormal_volume_pct": "{:.2f}%",
        "median_abnormal_volume_pct": "{:.2f}%"
    })
)

In [ ]:
volume_window_summary = (
    event_windows
    .groupby("event_id")
    .apply(
        lambda g: pd.Series({
            "baseline_volume": g.loc[
                g["event_minute"].between(-30, -5),
                "volume"
            ].mean(),

            "post_5m_volume": g.loc[
                g["event_minute"].between(1, 5),
                "volume"
            ].mean(),

            "post_30m_volume": g.loc[
                g["event_minute"].between(1, 30),
                "volume"
            ].mean(),

            "post_60m_volume": g.loc[
                g["event_minute"].between(1, 60),
                "volume"
            ].mean()
        })
    )
    .reset_index()
)

# Calculate relative volume
volume_window_summary["volume_ratio_5m"] = (
    volume_window_summary["post_5m_volume"] /
    volume_window_summary["baseline_volume"]
)

volume_window_summary["volume_ratio_30m"] = (
    volume_window_summary["post_30m_volume"] /
    volume_window_summary["baseline_volume"]
)

volume_window_summary["volume_ratio_60m"] = (
    volume_window_summary["post_60m_volume"] /
    volume_window_summary["baseline_volume"]
)

display(volume_window_summary.head(10))

In [ ]:
volume_window_summary = volume_window_summary[
    volume_window_summary["event_id"].astype(str).isin(
        independent_event_ids
    )
].copy()

print("Independent event volume summary:",
      volume_window_summary.shape)

In [ ]:
# Attach subject group to the independent-event volume summary

event_subjects = (
    event_results[
        ["event_id", "subject_group"]
    ]
    .drop_duplicates("event_id")
    .copy()
)

volume_window_summary["event_id"] = (
    volume_window_summary["event_id"].astype(str)
)

event_subjects["event_id"] = (
    event_subjects["event_id"].astype(str)
)

volume_window_summary = volume_window_summary.merge(
    event_subjects,
    on="event_id",
    how="left"
)

print("Shape:", volume_window_summary.shape)
print(
    "Missing subject groups:",
    volume_window_summary["subject_group"].isna().sum()
)

display(volume_window_summary.head())

In [ ]:
volume_subject_summary = (
    volume_window_summary
    .groupby("subject_group")
    .agg(
        n_events=("event_id", "nunique"),

        mean_ratio_5m=("volume_ratio_5m", "mean"),
        median_ratio_5m=("volume_ratio_5m", "median"),

        mean_ratio_30m=("volume_ratio_30m", "mean"),
        median_ratio_30m=("volume_ratio_30m", "median"),

        mean_ratio_60m=("volume_ratio_60m", "mean"),
        median_ratio_60m=("volume_ratio_60m", "median")
    )
    .reset_index()
)

# Convert ratios to abnormal volume percentages
for horizon in ["5m", "30m", "60m"]:
    volume_subject_summary[
        f"mean_abnormal_{horizon}"
    ] = (
        volume_subject_summary[f"mean_ratio_{horizon}"] - 1
    ) * 100

    volume_subject_summary[
        f"median_abnormal_{horizon}"
    ] = (
        volume_subject_summary[f"median_ratio_{horizon}"] - 1
    ) * 100

display(
    volume_subject_summary.style.format({
        "mean_ratio_5m": "{:.3f}",
        "median_ratio_5m": "{:.3f}",
        "mean_ratio_30m": "{:.3f}",
        "median_ratio_30m": "{:.3f}",
        "mean_ratio_60m": "{:.3f}",
        "median_ratio_60m": "{:.3f}",
        "mean_abnormal_5m": "{:.2f}%",
        "median_abnormal_5m": "{:.2f}%",
        "mean_abnormal_30m": "{:.2f}%",
        "median_abnormal_30m": "{:.2f}%",
        "mean_abnormal_60m": "{:.2f}%",
        "median_abnormal_60m": "{:.2f}%"
    })
)

In [141]:
# Create log volume ratios
for horizon in ["5m", "30m", "60m"]:
    volume_window_summary[f"log_ratio_{horizon}"] = np.log(
        volume_window_summary[f"volume_ratio_{horizon}"]
    )

display(
    volume_window_summary[
        [
            "event_id",
            "subject_group",
            "log_ratio_5m",
            "log_ratio_30m",
            "log_ratio_60m"
        ]
    ].head(10)
)

NameError: name 'volume_window_summary' is not defined

In [ ]:
print(
    "Infinite values:",
    np.isinf(
        volume_window_summary[
            ["log_ratio_5m", "log_ratio_30m", "log_ratio_60m"]
        ]
    ).sum().sum()
)

In [ ]:
from scipy import stats

volume_significance = []

for subject, group in volume_window_summary.groupby("subject_group"):

    for horizon in ["5m", "30m", "60m"]:

        values = group[f"log_ratio_{horizon}"].dropna()

        # H0: median/mean log volume ratio = 0
        # Equivalent to: post-event volume = baseline volume
        t_stat, p_value = stats.ttest_1samp(values, 0)

        mean_log = values.mean()

        # Convert log difference back to percentage change
        geometric_change_pct = (np.exp(mean_log) - 1) * 100

        volume_significance.append({
            "subject_group": subject,
            "horizon": horizon,
            "n_events": len(values),
            "mean_log_ratio": mean_log,
            "geometric_mean_volume_change_pct": geometric_change_pct,
            "t_stat": t_stat,
            "p_value": p_value
        })

volume_significance = pd.DataFrame(volume_significance)

volume_significance = volume_significance.sort_values(
    "p_value"
)

display(
    volume_significance.style.format({
        "mean_log_ratio": "{:.4f}",
        "geometric_mean_volume_change_pct": "{:.2f}%",
        "t_stat": "{:.3f}",
        "p_value": "{:.6f}"
    })
)

In [ ]:
# Benjamini-Hochberg FDR correction
volume_significance = volume_significance.copy()

volume_significance = volume_significance.sort_values(
    "p_value"
).reset_index(drop=True)

m = len(volume_significance)

volume_significance["p_value_adj"] = (
    volume_significance["p_value"]
    * m
    / (volume_significance.index + 1)
)

# Enforce monotonicity from largest rank backwards
volume_significance["p_value_adj"] = (
    volume_significance["p_value_adj"]
    .iloc[::-1]
    .cummin()
    .iloc[::-1]
    .clip(upper=1)
)

volume_significance["significant_5pct"] = (
    volume_significance["p_value_adj"] < 0.05
)

display(
    volume_significance.style.format({
        "mean_log_ratio": "{:.4f}",
        "geometric_mean_volume_change_pct": "{:.2f}%",
        "t_stat": "{:.3f}",
        "p_value": "{:.6f}",
        "p_value_adj": "{:.6f}"
    })
)

In [ ]:
volume_significance_final = (
    volume_significance
    .sort_values(["subject_group", "horizon"])
    .reset_index(drop=True)
)

display(volume_significance_final)

In [ ]:
# Prepare return significance results

return_results = significance_results[
    [
        "subject_group",
        "horizon",
        "n",
        "mean_return",
        "t_stat",
        "p_value",
        "p_value_adj",
        "significant_5pct"
    ]
].copy()

return_results = return_results.rename(columns={
    "n": "n_events",
    "mean_return": "mean_return",
    "p_value_adj": "return_p_value_adj",
    "significant_5pct": "return_significant"
})

# Prepare volume significance results

volume_results_final = volume_significance[
    [
        "subject_group",
        "horizon",
        "n_events",
        "geometric_mean_volume_change_pct",
        "t_stat",
        "p_value",
        "p_value_adj",
        "significant_5pct"
    ]
].copy()

volume_results_final = volume_results_final.rename(columns={
    "geometric_mean_volume_change_pct":
        "volume_change_pct",
    "p_value_adj":
        "volume_p_value_adj",
    "significant_5pct":
        "volume_significant"
})

# Merge return and volume results

combined_results = return_results.merge(
    volume_results_final,
    on=["subject_group", "horizon"],
    suffixes=("_return", "_volume")
)

# Direction of return
combined_results["return_direction"] = np.where(
    combined_results["mean_return"] > 0,
    "Positive",
    "Negative"
)

# Direction of volume
combined_results["volume_direction"] = np.where(
    combined_results["volume_change_pct"] > 0,
    "Higher",
    "Lower"
)

display(combined_results)

In [ ]:
combined_summary = combined_results[
    [
        "subject_group",
        "horizon",
        "n_events_return",
        "mean_return",
        "return_p_value_adj",
        "return_significant",
        "volume_change_pct",
        "volume_p_value_adj",
        "volume_significant",
        "return_direction",
        "volume_direction"
    ]
].copy()

display(
    combined_summary.style.format({
        "mean_return": "{:.4%}",
        "volume_change_pct": "{:.2f}%",
        "return_p_value_adj": "{:.6f}",
        "volume_p_value_adj": "{:.6f}"
    })
)

In [ ]:
print("Total independent events:", len(independent_event_results))
print("Unique event IDs:", independent_event_results["event_id"].nunique())

duplicates = independent_event_results[
    independent_event_results["event_id"].duplicated(keep=False)
]

print("Duplicate event IDs:", len(duplicates))
display(duplicates.head(20))

In [ ]:
print("Total independent events:", len(event_results))
print("Unique event IDs:", event_results["event_id"].nunique())

duplicates = event_results[
    event_results["event_id"].duplicated(keep=False)
]

print("Duplicate event IDs:", len(duplicates))
display(duplicates.head(20))

In [ ]:
return_cols = ["return_5m", "return_30m", "return_60m"]

print("Missing returns:")
print(event_results[return_cols].isna().sum())

In [142]:
for col in return_cols:
    print(f"\n{col}")
    print(
        event_results[col].describe(
            percentiles=[0.01, 0.05, 0.5, 0.95, 0.99]
        )
    )

    extreme = event_results[
        event_results[col].abs() > 0.10
    ]

    print("Returns > ±10%:", len(extreme))

NameError: name 'return_cols' is not defined

# 11. Robustness Analysis

In [ ]:
import numpy as np
import pandas as pd

robust_results = []

for subject in event_results["subject_group"].dropna().unique():

    subset = event_results[
        event_results["subject_group"] == subject
    ].copy()

    for horizon in ["5m", "30m", "60m"]:

        col = f"return_{horizon}"
        x = subset[col].dropna()

        if len(x) < 2:
            continue

        # 1% / 99% winsorization
        lower = x.quantile(0.01)
        upper = x.quantile(0.99)

        x_wins = x.clip(lower=lower, upper=upper)

        mean_return = x_wins.mean()
        std_return = x_wins.std(ddof=1)
        n = len(x_wins)

        se = std_return / np.sqrt(n)
        t_stat = mean_return / se if se != 0 else np.nan

        robust_results.append({
            "subject_group": subject,
            "horizon": horizon,
            "n_events": n,
            "original_mean": x.mean(),
            "winsorized_mean": mean_return,
            "difference": mean_return - x.mean(),
            "t_stat_winsorized": t_stat
        })

robust_results = pd.DataFrame(robust_results)

display(robust_results)

In [ ]:
robust_results["mean_change_pct"] = (
    (robust_results["winsorized_mean"] -
     robust_results["original_mean"])
    / robust_results["original_mean"].abs()
) * 100

display(
    robust_results[
        [
            "subject_group",
            "horizon",
            "original_mean",
            "winsorized_mean",
            "mean_change_pct",
            "t_stat_winsorized"
        ]
    ]
)

In [ ]:
# Clean final return significance results

final_return = significance_results.copy()

final_return["mean_return_pct"] = final_return["mean_return"] * 100

final_return = final_return[
    [
        "subject_group",
        "horizon",
        "n",
        "mean_return_pct",
        "t_stat",
        "p_value_adj",
        "significant_5pct"
    ]
].sort_values(
    ["horizon", "mean_return_pct"],
    ascending=[True, False]
)

display(final_return)

In [ ]:
import matplotlib.pyplot as plt

plot_data = final_return.pivot(
    index="subject_group",
    columns="horizon",
    values="mean_return_pct"
)

plot_data = plot_data[["5m", "30m", "60m"]]

ax = plot_data.plot(
    kind="bar",
    figsize=(12, 6)
)

ax.set_title("Average Stock Return Following Corporate Announcements")
ax.set_xlabel("Announcement Category")
ax.set_ylabel("Average Return (%)")
ax.axhline(0, linewidth=0.8)
plt.xticks(rotation=45, ha="right")
plt.legend(title="Event Horizon")
plt.tight_layout()
plt.show()

In [ ]:
%pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt

print("Matplotlib imported successfully")

In [ ]:
import matplotlib.pyplot as plt

plot_data = final_return.pivot(
    index="subject_group",
    columns="horizon",
    values="mean_return_pct"
)

plot_data.plot(kind="bar", figsize=(12, 6))

plt.axhline(0, linewidth=1)
plt.ylabel("Mean Return (%)")
plt.xlabel("Subject Group")
plt.title("Event-Driven Returns by Subject Group")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

In [143]:
plot_data = final_return.pivot(
    index="subject_group",
    columns="horizon",
    values="mean_return_pct"
)[["5m", "30m", "60m"]]

ax = plot_data.T.plot(
    figsize=(12, 6),
    marker="o"
)

ax.axhline(0, linewidth=1)
ax.set_title("Average Stock Return Following Corporate Announcements")
ax.set_xlabel("Event Horizon")
ax.set_ylabel("Average Return (%)")
plt.legend(title="Subject Group", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.show()

NameError: name 'final_return' is not defined

In [ ]:
# Chart 2 — Abnormal volume response

volume_plot = volume_window_summary.groupby(
    ["subject_group", "event_minute"]
)["volume_ratio"].mean().reset_index()

volume_plot["abnormal_volume_pct"] = (
    volume_plot["volume_ratio"] - 1
) * 100

plot_data = volume_plot.pivot(
    index="event_minute",
    columns="subject_group",
    values="abnormal_volume_pct"
)

ax = plot_data.plot(
    figsize=(12, 6),
    marker="o"
)

ax.axhline(0, linewidth=1)
ax.set_title("Abnormal Trading Volume Following Corporate Announcements")
ax.set_xlabel("Event Horizon (minutes)")
ax.set_ylabel("Abnormal Volume (%)")
plt.legend(
    title="Subject Group",
    bbox_to_anchor=(1.02, 1),
    loc="upper left"
)
plt.tight_layout()
plt.show()

In [ ]:
# Check the actual columns first
print(volume_window_summary.columns.tolist())

In [ ]:
# Chart 2 — Abnormal volume response

volume_plot = volume_window_summary.groupby(
    ["subject_group", "minute"]
)["volume_ratio"].mean().reset_index()

volume_plot["abnormal_volume_pct"] = (
    volume_plot["volume_ratio"] - 1
) * 100

plot_data = volume_plot.pivot(
    index="minute",
    columns="subject_group",
    values="abnormal_volume_pct"
)

ax = plot_data.plot(
    figsize=(12, 6),
    marker="o"
)

ax.axhline(0, linewidth=1)
ax.set_title("Abnormal Trading Volume Following Corporate Announcements")
ax.set_xlabel("Event Minute")
ax.set_ylabel("Abnormal Volume (%)")

plt.legend(
    title="Subject Group",
    bbox_to_anchor=(1.02, 1),
    loc="upper left"
)

plt.tight_layout()
plt.show()

In [ ]:
print(volume_window_summary.columns.tolist())
print("\nShape:", volume_window_summary.shape)
print("\nFirst 5 rows:")
display(volume_window_summary.head())

In [ ]:
import matplotlib.pyplot as plt

# Calculate mean volume ratio by subject group
volume_plot = volume_window_summary.groupby(
    "subject_group"
)[
    ["volume_ratio_5m", "volume_ratio_30m", "volume_ratio_60m"]
].mean()

# Convert ratio to abnormal volume %
volume_plot = (volume_plot - 1) * 100

# Plot
ax = volume_plot.plot(
    kind="bar",
    figsize=(12, 6)
)

ax.axhline(0, linewidth=1)

ax.set_title("Abnormal Trading Volume Following Corporate Announcements")
ax.set_xlabel("Announcement Category")
ax.set_ylabel("Abnormal Volume (%)")

plt.xticks(rotation=45, ha="right")
plt.legend(
    ["5m", "30m", "60m"],
    title="Event Horizon"
)

plt.tight_layout()
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Prepare return data
return_plot = final_return[
    ["subject_group", "horizon", "mean_return_pct"]
].copy()

# Prepare volume data
volume_plot = volume_window_summary.groupby(
    "subject_group"
)[
    ["volume_ratio_5m", "volume_ratio_30m", "volume_ratio_60m"]
].mean().reset_index()

# Convert volume ratios into abnormal volume %
volume_plot["5m"] = (volume_plot["volume_ratio_5m"] - 1) * 100
volume_plot["30m"] = (volume_plot["volume_ratio_30m"] - 1) * 100
volume_plot["60m"] = (volume_plot["volume_ratio_60m"] - 1) * 100

volume_long = volume_plot.melt(
    id_vars="subject_group",
    value_vars=["5m", "30m", "60m"],
    var_name="horizon",
    value_name="abnormal_volume_pct"
)

# Combine return + volume
combined = return_plot.merge(
    volume_long,
    on=["subject_group", "horizon"],
    how="inner"
)

print("Combined data:", combined.shape)

# Plot
fig, ax = plt.subplots(figsize=(12, 7))

for horizon in ["5m", "30m", "60m"]:
    data = combined[combined["horizon"] == horizon]

    ax.scatter(
        data["abnormal_volume_pct"],
        data["mean_return_pct"],
        label=horizon,
        s=80
    )

    # Add category labels
    for _, row in data.iterrows():
        ax.annotate(
            row["subject_group"],
            (row["abnormal_volume_pct"], row["mean_return_pct"]),
            fontsize=7,
            xytext=(4, 4),
            textcoords="offset points"
        )

ax.axhline(0, linewidth=1)
ax.axvline(0, linewidth=1)

ax.set_title("Market Reaction: Abnormal Volume vs. Stock Return")
ax.set_xlabel("Abnormal Volume (%)")
ax.set_ylabel("Mean Return (%)")
ax.legend(title="Event Horizon")

plt.tight_layout()
plt.show()

In [ ]:
print("========== FINAL DATA QUALITY CHECK ==========")

print("\nIndependent events:", len(volume_window_summary))
print("Unique event IDs:", volume_window_summary["event_id"].nunique())

print("\nMissing values:")
print(volume_window_summary.isna().sum())

print("\nDuplicate event IDs:",
      volume_window_summary["event_id"].duplicated().sum())

print("\nReturn observations:")
print("5m :", len(return_plot[return_plot["horizon"] == "5m"]))
print("30m:", len(return_plot[return_plot["horizon"] == "30m"]))
print("60m:", len(return_plot[return_plot["horizon"] == "60m"]))

print("\n========== CHECK COMPLETE ==========")

In [144]:
print("===== RETURN DATA CHECK =====")

print("Return dataset shape:", independent_returns.shape)

print("\nUnique event IDs:",
      independent_returns["event_id"].nunique())

print("\nDuplicate event IDs:",
      independent_returns["event_id"].duplicated().sum())

print("\nMissing values:")
print(independent_returns.isna().sum())

print("\nReturn columns:")
print([
    col for col in independent_returns.columns
    if "return" in col.lower()
])

print("\n===== CHECK COMPLETE =====")

===== RETURN DATA CHECK =====

NameError: name 'independent_returns' is not defined

In [ ]:
# Find DataFrames currently available in the notebook

import pandas as pd

dataframes = {}

for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):
        dataframes[name] = obj.shape

print("DataFrames currently available:\n")

for name, shape in dataframes.items():
    print(f"{name}: {shape}")

In [ ]:
print(event_results.columns.tolist())
print("\nShape:", event_results.shape)

display(event_results.head())

# 12. Post-Earnings Announcement Drift (PEAD) Analysis

In [146]:
print("===== PEAD DATA CHECK =====")

financial_events = independent_events[
    independent_events["subject_group"] == "Financial Results"
].copy()

print("Financial Results events:", len(financial_events))
print("\nColumns available:")
print(financial_events.columns.tolist())

print("\nSample events:")
display(
    financial_events[
        ["event_id", "ticker", "event_time", "subject_group"]
    ].head(10)
)

print("\nPrices columns:")
print(prices.columns.tolist())
print("Prices shape:", prices.shape)

===== PEAD DATA CHECK =====
Financial Results events: 218

Columns available:
['NEWSID', 'SCRIP_CD', 'XML_NAME', 'NEWSSUB', 'DT_TM', 'NEWS_DT', 'CRITICALNEWS', 'ANNOUNCEMENT_TYPE', 'QUARTER_ID', 'FILESTATUS', 'ATTACHMENTNAME', 'MORE', 'HEADLINE', 'CATEGORYNAME', 'OLD', 'RN', 'PDFFLAG', 'NSURL', 'SLONGNAME', 'AGENDA_ID', 'News_submission_dt', 'DissemDT', 'TimeDiff', 'Fld_Attachsize', 'SUBCATNAME', 'BSENewsid', 'Investor_Presentation', 'AUDIO_VIDEO_FILE', 'ticker', 'market_timing', 'event_time_correct', 'event_index', 'subject_group', 'event_cluster', 'cluster_size']

Sample events:

KeyError: "['event_id', 'event_time'] not in index"